<table border="1">
    <tr>
        <th>Data</th>        
        <th>Nome</th>
        <th>Empresa</th>
        <th>Telefone</th>
        <th>E-mail</th>
        <th>Assunto</th>
        <th>Mensagem</th>
    </tr>
    <?php
    if ($this->dados->num_rows) {
        foreach ($this->dados->rows as $registro) {
            ?>
            <tr>
                <td><?php echo $registro["data"]; ?></td>
                <td><?php echo utf8_decode($registro["nome"]); ?></td>
                <td><?php echo utf8_decode($registro["empresa"]); ?></td>
                <td><?php echo $registro["fone"]; ?></td>
                <td><?php echo $registro["email"]; ?></td>
                <td><?php echo utf8_decode($registro["assunto"]); ?></td>
                <td><?php echo utf8_decode($registro["mensagem"]); ?></td>
            </tr>
            <?php
        }
    }
    ?>
</table>