
        <div id="qLoverlay"></div>
    
        <!--[if lt IE 9]>
          <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <!-- .#header -->
        <div id="header">
            <nav class="navbar navbar-default" role="navigation">
                <div class="navbar-header">
                    <a class="navbar-brand" href="dashboard" style="text-align: center;"><img class="logo-custom" src="images/logo-realpoker.png" alt="Página Inicial" width="120" /></a>
                </div>
                <div id="navbar-no-collapse" class="navbar-no-collapse">
                    <ul class="nav navbar-nav">
                        
                        <li>
                            <!--Sidebar collapse button-->
                            <a href="#" class="collapseBtn leftbar"><i class="s16 minia-icon-list-3"></i></a>
                        </li>
                        <li style="display:none">
                            <a href="#" class="tipB reset-layout" title="Redefinir posições do painel"><i class="s16 icomoon-icon-history"></i></a>
                        </li>
                        <?php if (isset($this->module_title)): ?>
                        <li class="active">
                            <a href="<?php echo $this->module_link ?>"><span class="s16 <?php echo $this->module_icon ?>"></span> <span class="txt"><?php echo $this->module_title ?></span></a>
                        </li>
                        <?php endif ?>
                        <?php if ($this->permissions['admin-users']['ler'] || $this->permissions['admin-grupos']['ler'] || $this->permissions['admin-empresa']['ler'] || $this->permissions['admin-logs']['ler'] || $this->permissions['admin-backups']['ler']): ?>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="s16 icomoon-icon-cog-2"></i><span class="txt"> Configurações</span>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu left dropdown-form template-settings">
                                <li class="menu" style="width: 100%">
                                    <ul role="menu">
                                        <li><strong>Configurações do Sistema</strong></li>                                        
                                   	    <?php if ($this->permissions['admin-empresa']['ler']): ?>
                                            <li><a href="company"><span class="s16 icomoon-icon-cog-2"></span>Gerais</a></li>
                                            <li><a href="companies"><span class="s16 icomoon-icon-office"></span>Empresas</a></li>
                                            <li><a href="leadorigin"><span class="s16 icomoon-icon-location"></span>Origem do Lead</a></li>
                                        <?php endif ?>
                                        <?php if ($this->permissions['admin-grupos']['ler']): ?>
                                            <li><a href="group"><span class="s16 icomoon-icon-users-2"></span>Grupos de Usuário</a></li>
                                        <?php endif ?>
                                        <?php if ($this->permissions['admin-users']['ler']): ?>
                                            <li><a href="user"><span class="s16 icomoon-icon-users"></span>Usuários</a></li>
                                        <?php endif ?>
                                        <?php if ($this->permissions['admin-grupos']['ler']): ?>
                                            <li><a href="department"><span class="s16 icomoon-icon-office"></span>Departamentos</a></li>
                                        <?php endif ?>
                                        <?php if ($this->permissions['admin-users']['ler']): ?>
                                            <li><a href="userproduction"><span class="s16 icomoon-icon-users"></span>Usuários de Produção</a></li>
                                        <?php endif ?>
                                        <?php if ($this->permissions['admin-notificacoes']['ler']): ?>
                                            <li><a href="notifications"><span class="s16 entypo-icon-email"></span>Notificações</a></li>
                                        <?php endif ?>
                                        <?php if ($this->permissions['admin-logs']['ler']): ?>
                                            <li><a href="log"><span class="s16 icomoon-icon-stack"></span>Logs</a></li>
                                        <?php endif ?>
                                        <?php if ($this->permissions['admin-backups']['ler']): ?>
                                            <li><a href="backup"><span class="s16 icomoon-icon-database"></span>Backups</a></li>
                                        <?php endif ?>
                                        <?php if ($this->permissions['system-updates']['ler']): ?>
                                            <li><a href="updates"><span class="s16 brocco-icon-refresh"></span>Atualizações do sistema</a></li>
                                        <?php endif ?>
                                            
                                        <li><strong>Configurações do Tema</strong>
                                        </li>
                                        <li>
                                            <div class="toggle-custom">
                                                <label class="toggle" data-on="ON" data-off="OFF">
                                                    <input type="checkbox" id="fixed-header-toggle" name="fixed-header-toggle" checked>
                                                    <span class="button-checkbox"></span>
                                                </label>
                                                <label for="fixed-header-toggle">Topo fixo</label>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="toggle-custom">
                                                <label class="toggle" data-on="ON" data-off="OFF">
                                                    <input type="checkbox" id="fixed-left-sidebar" name="fixed-left-sidebar" checked>
                                                    <span class="button-checkbox"></span>
                                                </label>
                                                <label for="fixed-left-sidebar">Lateral fixa</label>
                                            </div>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <?php endif ?>
                    </ul>
                    <ul class="nav navbar-right usernav">

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle avatar" data-toggle="dropdown">
                                <img src="<?php if ($_SESSION['admin_avatar'] != "../uploads/[38x33].") echo $_SESSION['admin_avatar']; else echo 'images/avatar.png'; ?>" alt="" class="image" /> 
                                <span class="txt"><?php echo $_SESSION['admin_nome']; ?></span>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu right">
                                <li class="menu">
                                    <ul>
                                        <li><a href="user/edit/id/<?php echo $_SESSION['admin_id'] ?>"><span class="s16 icomoon-icon-user-plus"></span>Editar dados</a></li>
                                        <li><a href="user/edit"><span class="s16 icomoon-icon-plus"></span>Add user</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li class="admin-logout"><a href="#"><i class="s16 icomoon-icon-exit"></i><span class="txt"> Logout</span></a>
                        </li>
                        
                    </ul>
                </div>
                <!-- /.nav-collapse -->
            </nav>
            <!-- /navbar -->
        </div>

