<?php
    require_once "layouts/headers.phtml";
?>

    <script type="text/javascript">
        var pagina = "<?php echo $this->getModule(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getModule(); ?>/save";
        var retorno = "<?php echo $this->retorno; ?>";
    </script>
    
    </head>  
    
    
    <body>
<?php  require_once "layouts/header.phtml"; ?>

        <!-- / #header -->
        <div id="wrapper">
        <!-- #wrapper -->

<?php  require_once "layouts/sidebar.phtml"; ?>
            
            <!--Body content-->
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <!--Content wrapper-->
                    <div class="heading">
                        <!--  .heading-->
                        <h3><?php echo $this->module_title; ?></h3>

                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li>
                                <a href="#" class="tip" title="Painel">
                                    <i class="s16 icomoon-s-screen-2"></i>
                                </a>
                                <span class="divider">
                                    <i class="s16 icomoon-s-arrow-right-3"></i>
                                </span>
                            </li>
                            <li>
                                <a class="tip" title="<?php echo $this->module_title; ?>" href="<?php echo $this->module_link;?>">
                                    <i class="s16 <?php echo $this->module_icon; ?>"></i>                                    
                                </a>
                            </li>
                            <span class="divider">
                                <i class="s16 icomoon-s-arrow-right-3"></i>
                            </span>
                            <li class="active">Registro</li>
                        </ul>
                    </div>
                    <!-- End  / heading-->
                    <!-- Start .row -->
                  
                    <form name="main" enctype="multipart/form-data" method="post" class="form-horizontal group-border">
                        <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
                        <input type="hidden" name="retorno" value="<?php echo $this->retorno; ?>">
                        <input type="hidden" name="categoria" id="cat" value="<?php echo $this->registro['categoria']; ?>">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <!-- Start .panel -->
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Dados do Desconto</h4>
                                    </div>
                                    <div class="panel-body">
                                        <?php if ($this->id != "") :?>
                                            <div class="form-group">
                                                <label class="col-lg-2 control-label">Data de Cadastro</label>
                                                <div class="col-lg-10">
                                                    <input type="text" name="chave_data" class="form-control" value="<?php echo $this->registro['data'] ?>" disabled />
                                                </div>
                                            </div><!-- End .form-group  -->
                                        <?php endif; ?>

                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="descricao">Descrição:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="descricao" id="descricao" type="text" value="<?php echo $this->registro['descricao'] ?>" />
                                            </div>
                                        </div><!-- End .form-group  -->
                                        
                                        <div class="form-group form-group-vertical">
                                            <label class="col-lg-2 col-md-3 control-label" for="porcentagem">Tipo:</label>
                                            <div class="col-lg-10 col-md-9">
                                                <select class="form-control input-sm" id="porcentagem" name="porcentagem">
                                                    <option value="">Selecione..</option>
                                                    <option <?php if ($this->registro['porcentagem'] == 0) echo "selected"; ?> value="0">Valor Fixo</option>
                                                    <option <?php if ($this->registro['porcentagem'] == 1) echo "selected"; ?> value="1">Porcentagem</option>
                                                </select>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="valor">Valor:</label>
                                            <div class="col-lg-10">
                                                <input onKeyUp="moeda(this);" onKeyPress="return checkIt(event)" class="form-control" name="valor" id="valor" type="text" value="<?php echo $this->formataMoedaShow($this->registro['valor']); ?>" />
                                            </div><!-- End .form-group  -->
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="porcentagem_fabrica">Porcentagem da Fábrica:</label>
                                            <div class="col-lg-10">
                                                <input onKeyUp="moeda(this);" onKeyPress="return checkIt(event)" class="form-control" name="porcentagem_fabrica" id="porcentagem_fabrica" type="text" value="<?php echo $this->formataMoedaShow($this->registro['porcentagem_fabrica']); ?>" />
                                            </div><!-- End .form-group  -->
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="quantidade">A partir de:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="quantidade" id="quantidade" type="text" value="<?php echo $this->registro['quantidade']; ?>" />
                                            </div><!-- End .form-group  -->
                                        </div>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-lg-12 ">
                                <div class="tabs mb20">
                                    <ul id="myTab" class="nav nav-tabs">
                                        <li class="tab_categoria <?php if ($this->registro['categoria'] == 1) echo 'active'; ?>">
                                            <a href="#categorias" data-toggle="tab">Relacionar por Categorias</a>
                                        </li>
                                        <li class="tab_produto <?php if ($this->registro['categoria'] != 1) echo 'active'; ?>">
                                            <a href="#produtos" data-toggle="tab">Relacionar por Produtos</a>
                                        </li>
                                    </ul>
                                    <div id="myTabContent2" class="tab-content">
                                        <div class="tab-pane fade <?php if ($this->registro['categoria'] == 1) echo 'active in'; else echo 'fade'; ?>" id="categorias">
                                            <div class="row">
                                                
                                                <div class="col-lg-12">
                                                
                                                    <div class="form-group">
                                                        <label class="col-lg-2 control-label" for="">Categorias:</label>
                                                        <div class="col-lg-10">
                                                            <div class="leftBox" style="margin:0;">
                                                                <div class="searchBox">
                                                                    <input type="text" id="box3Filter" class="searchField form-control" style="margin:0;" placeholder="filtrar ..."/>
                                                                    <button id="box3Clear" type="button" class="btn">
                                                                        <span class="s14  entypo-icon-close "></span>
                                                                    </button>
                                                                </div>
                                                                <select id="box3View" multiple="multiple" class="multiple nostyle form-control" style="height:300px;">
                                                                    <?php if ($this->categorias->num_rows): ?>
                                                                        <?php foreach ($this->categorias->rows as $categoria): ?>
                                                                            <?php if ($categoria['id_categoria'] == "") : ?>
                                                                                <option value="<?php echo $categoria['id'] ?>"><?php echo $categoria['nome'] ?></option>
                                                                            <?php endif ?>
                                                                        <?php endforeach ?>
                                                                    <?php endif ?>
                                                                </select>
                                                                <br>
                                                                <span>Categorias <span class="label-warning" style="padding:0 2px;">não relacionadas</span> a este desconto</span>
                                                                <br>
                                                                <span id="box3Counter" class="count"></span>
                                                                <div class="dn"><select id="box3Storage" name="box3Storage" class="nostyle"></select></div>
                                                            </div>


                                                            <div class="dualBtn">

                                                                <button id="to4" type="button" class="btn" ><span class="icon12 minia-icon-arrow-right-3"></span></button>
                                                                <button id="allTo4" type="button" class="btn" ><span class="icon12 iconic-icon-last"></span></button>
                                                                <button id="to3" type="button" class="btn marginT5"><span class="icon12 minia-icon-arrow-left-3"></span></button>
                                                                <button id="allTo3" type="button" class="btn marginT5" ><span class="icon12 iconic-icon-first"></span></button>

                                                            </div>

                                                            <div class="rightBox" style="margin:0;">
                                                                <div class="searchBox">
                                                                    <input type="text" id="box4Filter" class="searchField form-control" style="margin:0;" placeholder="filtrar ..." />
                                                                    <button id="box4Clear"  type="button" class="btn" >
                                                                        <span class="s14  entypo-icon-close "></span>
                                                                    </button>
                                                                </div>
                                                                <select id="box4View" multiple="multiple" name="categorias[]" class="multiple nostyle form-control" style="height:300px;">
                                                                    <?php if ($this->categorias->num_rows): ?>
                                                                        <?php foreach ($this->categorias->rows as $categoria): ?>
                                                                            <?php if ($categoria['id_categoria'] != "") : ?>
                                                                                <option value="<?php echo $categoria['id'] ?>"><?php echo $categoria['nome'] ?></option>
                                                                            <?php endif ?>
                                                                        <?php endforeach ?>
                                                                    <?php endif ?>
                                                                </select>
                                                                <br>
                                                                <span>Categorias <span class="label-success white" style="padding:0 2px;">relacionadas</span> a este desconto</span>
                                                                <br>
                                                                <span id="box4Counter" class="count"></span>
                                                                <div class="dn"><select id="box4Storage" class="nostyle"></select></div>
                                                            </div>

                                                        </div>
                                                    </div>
                                                </div>   
                                            </div>
                                        </div>
                                        <div class="tab-pane <?php if ($this->registro['categoria'] != 1) echo 'active in'; else echo 'fade'; ?>" id="produtos">
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    
                                                    <div class="form-group">
                                                        <label class="col-lg-2 control-label" for="">Produtos:</label>
                                                        <div class="col-lg-10">
                                                            <div class="leftBox" style="margin:0;">
                                                                <div class="searchBox">
                                                                    <input type="text" id="box1Filter" class="searchField form-control" style="margin:0;" placeholder="filtrar ..."/>
                                                                    <button id="box1Clear" type="button" class="btn">
                                                                        <span class="s14  entypo-icon-close "></span>
                                                                    </button>
                                                                </div>
                                                                <select id="box1View" multiple="multiple" class="multiple nostyle form-control" style="height:300px;">
                                                                    <?php if ($this->produtos->num_rows): ?>
                                                                        <?php foreach ($this->produtos->rows as $produto): ?>
                                                                            <?php if ($produto['id_produto'] == "") : ?>
                                                                                <option value="<?php echo $produto['id'] ?>"><?php echo $produto['nome'] ?></option>
                                                                            <?php endif ?>
                                                                        <?php endforeach ?>
                                                                    <?php endif ?>
                                                                </select>
                                                                <br>
                                                                <span>Produtos <span class="label-warning" style="padding:0 2px;">não relacionados</span> a este desconto</span>
                                                                <br>
                                                                <span id="box1Counter" class="count"></span>
                                                                <div class="dn"><select id="box1Storage" name="box1Storage" class="nostyle"></select></div>
                                                            </div>


                                                            <div class="dualBtn">

                                                                <button id="to2" type="button" class="btn" ><span class="icon12 minia-icon-arrow-right-3"></span></button>
                                                                <button id="allTo2" type="button" class="btn" ><span class="icon12 iconic-icon-last"></span></button>
                                                                <button id="to1" type="button" class="btn marginT5"><span class="icon12 minia-icon-arrow-left-3"></span></button>
                                                                <button id="allTo1" type="button" class="btn marginT5" ><span class="icon12 iconic-icon-first"></span></button>

                                                            </div>

                                                            <div class="rightBox" style="margin:0;">
                                                                <div class="searchBox">
                                                                    <input type="text" id="box2Filter" class="searchField form-control" style="margin:0;" placeholder="filtrar ..." />
                                                                    <button id="box2Clear"  type="button" class="btn" >
                                                                        <span class="s14  entypo-icon-close "></span>
                                                                    </button>
                                                                </div>
                                                                <select id="box2View" multiple="multiple" name="produtos[]" class="multiple nostyle form-control" style="height:300px;">
                                                                    <?php if ($this->produtos->num_rows): ?>
                                                                        <?php foreach ($this->produtos->rows as $produto): ?>
                                                                            <?php if ($produto['id_produto'] != "") : ?>
                                                                                <option  value="<?php echo $produto['id'] ?>"><?php echo $produto['nome'] ?></option>
                                                                            <?php endif ?>
                                                                        <?php endforeach ?>
                                                                    <?php endif ?>
                                                                </select>
                                                                <br>
                                                                <span>Produtos <span class="label-success white" style="padding:0 2px;">relacionados</span> a este desconto</span>
                                                                <br>
                                                                <span id="box2Counter" class="count"></span>
                                                                <div class="dn"><select id="box2Storage" class="nostyle"></select></div>
                                                            </div>

                                                        </div>
                                                    </div>
                                                        
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        
                        
                        
                        <div class="row">
                            <?php if ($this->id==""): ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['gravar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning "><span class="s24 typ-s-warning"></span>Você não tem permissão para gravar esta função.</span>
                                        </div>
                                    </div><!-- End .form-group  -->   
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="button" class="btn btn-info clickformsubmit">Salvar novo</button>
                                        </div>
                                    </div><!-- End .form-group  -->
                                <?php endif ?>
                            <?php else: ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['editar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning"><span class="s24 icomoon-s-warning "></span>Você não tem permissão para editar esta função.</span>
                                        </div>
                                    </div><!-- End .form-group  -->   
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="button" class="btn btn-info clickformsubmit">Salvar alterações</button>
                                        </div>
                                    </div><!-- End .form-group  -->
                                <?php endif ?>
                            <?php endif ?>
                        </div><!-- End .row -->  
                    </form>
                </div>
                <!-- End contentwrapper -->
            </div>
            <!-- End #content -->
            
            
<?php  require_once "layouts/footer.phtml"; ?>
        
        </div>
        
<?php  require_once "layouts/plugins.phtml"; ?>
        <script type="text/javascript" src="plugins/forms/dualselect/jquery.dualListBox-1.3.min.js"></script>
        <script type="text/javascript">
            
            
            function moeda(z){  
                v = z.value;
                v=v.replace(/\D/g,"")  //permite digitar apenas números
                v=v.replace(/[0-9]{12}/,"inválido")   //limita pra máximo 999.999.999,99
                v=v.replace(/(\d{1})(\d{8})$/,"$1.$2")  //coloca ponto antes dos últimos 8 digitos
                v=v.replace(/(\d{1})(\d{5})$/,"$1.$2")  //coloca ponto antes dos últimos 5 digitos
                v=v.replace(/(\d{1})(\d{1,2})$/,"$1,$2")	//coloca virgula antes dos últimos 2 digitos
                z.value = v;
            }
            
            $(document).ready(function(){
                $("#quantidade").mask("###########");
                $.configureBoxes();
                $.configureBoxes1();
                
                $(".tab_categoria").on("click", function(){
                   $("#cat").val(1); 
                });
                
                $(".tab_produto").on("click", function(){
                   $("#cat").val(0); 
                });
                
            });
        </script>
    </body>
</html>
