
<div class="row">
    <?php 

        $ja_editado = false;
        foreach ($this->produtos as $prod) {
            if($prod['valor_editado'] != $prod['valor_produto']){
                $ja_editado = true;
            }
        }

         
        // verifica se já existe um cupom ativado antes da edição.
        if (!$ja_editado && $this->produtos[0]['mensagem_cupom'] != ""): 
    ?>    
        <div style="text-align: center; margin: 30px; color: red;">Este orçamento não pode ser editado pois já possui um cupom vinculado!</div>
    <?php endif ?>
    <table width="100%">
        <tr>
            <td></td>
            <td class="tal"><strong>PRODUTO</strong></td>
            <td><strong>QTDE.</strong></td>
            <td><strong>VALOR ORIGINAL</strong></td>
            <td><strong>VALOR EDITADO</strong></td>
            <td><strong>TOTAL EDITADO</strong></td>
            <td><strong>UN. A VISTA</strong></td>
            <td><strong>À VISTA</strong></td>
        </tr>
        <?php 
            $total_original = 0;
            $desconto = 0;
            $valor_editado = 0;
            if(count($this->produtos)){
                foreach($this->produtos as $i => $produto){

                    //gambiarra para calcular sempre o valor já com desconto aplicado
                    if($produto['desconto']) $desconto = $produto['desconto'];
                    $total_original += (($produto['valor_produto']-$desconto)*$produto['quantidade']);
                    

                    //gambiarra para sempre apresentar o valor editado calculando o valor do produto já com desconto aplicado
                    $valor_editado = $produto['valor_editado'];
                    if($valor_editado == $produto['valor_produto']) $valor_editado = $valor_editado-$desconto;

        ?>
                    <tr class="calc">
                        <td><?php echo ($i+1); ?></td>
                        <td class="tal"><?php echo $produto['nome_produto']; ?></td>
                        <td data-quantidade="<?php echo $produto['quantidade']; ?>" class="edit_quatidade"><?php echo $produto['quantidade']; ?></td>
                        <td data-valor_produto="<?php echo ($produto['valor_produto']-$desconto); ?>" class="edit_valor_produto">R$ <?php echo $this->formataMoedaShow($produto['valor_produto'] - $desconto); ?></td>
                        <td data-valor_editado="<?php echo $valor_editado; ?>" class="edit_valor_editado">
                            <?php if (!$ja_editado && $this->produtos[0]['mensagem_cupom'] != ""): ?>
                                R$ <input type="text" onKeyUp="moeda(this);" data-id_carrinho="<?php echo $produto['id']; ?>" name="valor_editado[]" class="valor_editado" style="width: 90px;text-align: right;" value="<?php echo $this->formataMoedaShow($valor_editado); ?>" disabled>
                            <?php else: ?>
                                R$ <input type="text" onKeyUp="moeda(this);" data-id_carrinho="<?php echo $produto['id']; ?>" name="valor_editado[]" class="valor_editado" style="width: 90px;text-align: right;" value="<?php echo $this->formataMoedaShow($valor_editado); ?>">
                            <?php endif; ?>
                        </td>
                        <td class="edit_valor_total"></td>
                        <td class="edit_unitario_avista"></td>
                        <td class="edit_total_avista"></td>
                    </tr>
        <?php
                    $desconto = 0;
                }
            }
        ?>
        <tr>
            <td></td>
            <td colspan="4" class="tal"><strong>TOTAL DE DESCONTOS</strong></td>
            <td style="color:red;" class="total_descontos"><strong></strong></td>
            <td style="color:red;" colspan="2" class="total_descontos_avista"><strong></strong></td>
        </tr>
        <tr>
            <td></td>
            <td colspan="2" class="tal"><strong>TOTAL:</strong></td>
            <td class="total_original"><strong></strong></td>
            <td></td>
            <td class="total_editado"><strong></strong></td>
            <td></td>
            <td class="total_avista"><strong></strong></td>
        </tr>
    </table>
    <?php if (!$ja_editado && $this->produtos[0]['mensagem_cupom'] != ""): ?>
        <div style="text-align: center; margin: 30px; color: red;">Este orçamento não pode ser editado pois já possui um cupom vinculado!</div>
    <?php else: ?>
        <div style="text-align: right; margin: 30px;"><button class="btn btn-primary save_discounts" type="button">SALVAR</button></div>
    <?php endif ?>
</div>

<script>

    var pedido = {
        id: <?php echo $this->produtos[0]['id_pedido']; ?>,
        descontos: 0,
        valor_final: 0
    }

    $("input.valor_editado").focus(function() {
       $(this).select();
    });

    $("input.valor_editado").keyup(updateKey);
    $("input.valor_editado").each(updateKey);
    $("button.save_discounts").click(save);

    function updateKey(){
        var quantidade = parseInt($(this).parents("tr").find(".edit_quatidade").data("quantidade"));
        var valor_editado = parseFloat($(this).val().toString().replace('.','').replace(',','.'));
        var valor_produto = parseFloat($(this).parents("tr").find(".edit_valor_produto").data("valor_produto"));
        var total = (valor_editado*quantidade);

        $(this).parents("tr").find(".edit_valor_total").html((total).toLocaleString('pt-br',{style: 'currency', currency: 'BRL'}));
        $(this).parents("tr").find(".edit_unitario_avista").html((valor_editado*0.95).toLocaleString('pt-br',{style: 'currency', currency: 'BRL'}));
        $(this).parents("tr").find(".edit_total_avista").html((total*0.95).toLocaleString('pt-br',{style: 'currency', currency: 'BRL'}));

        $(this).parents("tr").find(".edit_valor_produto").addClass("cortado");

        if(valor_editado == valor_produto){
            $(this).parents("tr").find(".edit_valor_produto").removeClass("cortado");
        }
        calculadora();
    }


    function calculadora(){
        var valor_t = 0;
        var quantidade_t = 0;
        var total_unitario_original = 0;
        var total_unitario_editado = 0;
        var total_geral_original = 0;
        var total_geral_editado = 0;
        var total_geral_avista = 0;
        var total_descontos = 0;
        var total_descontos_avista = 0;

        $("tr.calc").each(function(index){
            quantidade_t = $(this).find("td.edit_quatidade").data("quantidade");
            valor_t = $(this).find("td.edit_valor_produto").data("valor_produto");
            valor_editado_t = parseFloat($(this).find("td input.valor_editado").val().toString().replace('.','').replace(',','.'));

            total_unitario_original += valor_t;
            total_geral_original += (quantidade_t*valor_t);
            total_geral_editado += (quantidade_t*valor_editado_t);

            //console.log((index+1)+" - "+valor_t+ "("+valor_editado_t+")");
        });

        
        total_geral_avista = total_geral_editado*0.95;
        total_descontos = total_geral_original-total_geral_editado;
        total_descontos_avista = total_geral_original-total_geral_avista;

        pedido.descontos = total_descontos;
        pedido.valor_final = total_geral_editado;


        $(".total_descontos strong").html(total_descontos.toLocaleString('pt-br',{style: 'currency', currency: 'BRL'}));
        $(".total_descontos_avista strong").html(total_descontos_avista.toLocaleString('pt-br',{style: 'currency', currency: 'BRL'}));
        $(".total_original strong").html(total_geral_original.toLocaleString('pt-br',{style: 'currency', currency: 'BRL'}));
        $(".total_editado strong").html(total_geral_editado.toLocaleString('pt-br',{style: 'currency', currency: 'BRL'}));
        $(".total_avista strong").html(total_geral_avista.toLocaleString('pt-br',{style: 'currency', currency: 'BRL'}));
    }

    function save(){

        var produtos = [];
        $("input.valor_editado").each(function(index){
            produtos.push({
                "id": $(this).data("id_carrinho"),
                "valor_editado": parseFloat($(this).val().toString().replace('.','').replace(',','.'))
            });
        });

        $.post("proposal2/saveDescontos", {
            "pedido":pedido,
            "produtos":produtos
        }, function(){
            alert("Orçamento Editado com Sucesso");
            $('#modal-discounts').modal('hide');
        });

    }

</script>