<?php
    require_once "layouts/headers.phtml";
?>

    <script type="text/javascript">
        var pagina = "<?php echo $this->getModule(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getModule(); ?>/save";
        var retorno = "<?php echo $this->retorno; ?>";
    </script>

    </head>


    <body>
<?php  require_once "layouts/header.phtml"; ?>

        <!-- / #header -->
        <div id="wrapper">
        <!-- #wrapper -->

<?php  require_once "layouts/sidebar.phtml"; ?>

            <!--Body content-->
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <!--Content wrapper-->
                    <div class="heading">
                        <!--  .heading-->
                        <h3><?php echo $this->module_title; ?></h3>

                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li>
                                <a href="#" class="tip" title="Painel">
                                    <i class="s16 icomoon-s-screen-2"></i>
                                </a>
                                <span class="divider">
                                    <i class="s16 icomoon-s-arrow-right-3"></i>
                                </span>
                            </li>
                            <li>
                                <a class="tip" title="<?php echo $this->module_title; ?>" href="<?php echo $this->module_link;?>">
                                    <i class="s16 <?php echo $this->module_icon; ?>"></i>
                                </a>
                            </li>
                            <span class="divider">
                                <i class="s16 icomoon-s-arrow-right-3"></i>
                            </span>
                            <li class="active">Registro</li>
                        </ul>
                    </div>
                    <!-- End  / heading-->
                    <!-- Start .row -->

                    <form name="main" enctype="multipart/form-data" method="post" class="form-horizontal group-border">
                        <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
                        <input type="hidden" name="retorno" value="<?php echo $this->retorno; ?>">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <!-- Start .panel -->
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Dados do Atendimento</h4>
                                    </div>
                                    <div class="panel-body">
                                        <?php if ($this->id != "") :?>
                                            <div class="form-group">
                                                <label class="col-lg-2 control-label">Data de Cadastro</label>
                                                <div class="col-lg-4">
                                                    <input type="text" class="form-control" value="<?php echo $this->registro['data'] ?>" disabled />
                                                </div>
                                                <label class="col-lg-2 control-label">Última Atualização</label>
                                                <div class="col-lg-4">
                                                    <input type="text" class="form-control" value="<?php echo $this->registro['ultima_atualizacao'] ?>" disabled />
                                                </div>
                                            </div><!-- End .form-group  -->
                                        <?php endif; ?>


                                        <div class="form-group form-group-vertical">
                                            <label class="col-lg-2 col-md-3 control-label" for="id_user">Vendedor:</label>
                                            <div class="col-lg-10 col-md-9">
                                                <select class="form-control input-sm" id="id_user" name="id_user">
                                                    <option value="">Selecione..</option>
                                                    <?php if ($this->users->num_rows) : ?>
                                                        <?php foreach ($this->users->rows as $user) : ?>
                                                            <option <?php if ($user['id'] == $this->registro['id_user'] || ($this->registro['id_user'] == "" && $_SESSION['admin_id'] == $user['id'])) echo "selected"; ?> value="<?php echo $user['id']; ?>"><?php echo $user['nome']; ?></option>
                                                        <?php endforeach; ?>
                                                    <?php endif; ?>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="nome">Nome:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="nome" id="nome" type="text" value="<?php echo $this->registro['nome'] ?>" />
                                            </div>
                                        </div><!-- End .form-group  -->

                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="email">E-mail:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="email" id="email" type="text" value="<?php echo $this->registro['email'] ?>" />
                                            </div>
                                        </div><!-- End .form-group  -->

                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="cnpj">CPF ou CNPJ:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="cpf_cnpj" id="cpf_cnpj" type="text" value="<?php echo $this->registro['cpf_cnpj'] ?>" />
                                            </div>
                                        </div><!-- End .form-group  -->

                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="telefone">Telefone:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="telefone" id="telefone" type="text" value="<?php echo $this->registro['telefone'] ?>" />
                                            </div>
                                        </div><!-- End .form-group  -->

                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <?php if ($this->id==""): ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['gravar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning "><span class="s24 typ-s-warning"></span>Você não tem permissão para gravar esta função.</span>
                                        </div>
                                    </div><!-- End .form-group  -->
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="button" class="btn btn-info clickformsubmit">Salvar novo</button>
                                        </div>
                                    </div><!-- End .form-group  -->
                                <?php endif ?>
                            <?php else: ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['editar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning"><span class="s24 icomoon-s-warning "></span>Você não tem permissão para editar esta função.</span>
                                        </div>
                                    </div><!-- End .form-group  -->
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="button" class="btn btn-info clickformsubmit">Salvar alterações</button>
                                        </div>
                                    </div><!-- End .form-group  -->
                                <?php endif ?>
                            <?php endif ?>
                        </div><!-- End .row -->
                    </form>
                </div>
                <!-- End contentwrapper -->
            </div>
            <!-- End #content -->


<?php  require_once "layouts/footer.phtml"; ?>

        </div>

<?php  require_once "layouts/plugins.phtml"; ?>
<script src="../../js/jquery.inputmask.bundle.min.js"></script>
        <!-- Init plugins only for page -->
        <script type="text/javascript">
            $(document).ready(function(){
                $('#telefone').inputmask({'mask': '(99) 99999999[9]', 'greedy': false});
                $('#cpf_cnpj').inputmask({'mask': ['999.999.999-99', '99.999.999/9999-99' ]});
            });
        </script>
    </body>
</html>
