<?php
    require_once "layouts/headers.phtml";
?>
    <script type="text/javascript">
        var pagina = "<?php echo $this->getModule(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getModule(); ?>/save";
        var retorno = "<?php echo $this->retorno; ?>";
    </script>
</head>

<body class="remessa">
    <?php require_once "layouts/header.phtml"; ?>

    <!-- / #header -->
    <div id="wrapper">
    <!-- #wrapper -->

        <?php  require_once "layouts/sidebar.phtml"; ?>

        <!--Body content-->
        <div id="content" class="page-content clearfix">
            <!--Content wrapper-->
            <div class="contentwrapper">
                <!-- .heading -->
                <div class="heading">
                    <h3><?php echo $this->module_title; ?></h3>
                    <ul class="breadcrumb">
                        <li>Você está aqui:</li>
                        <li>
                            <a href="#" class="tip" title="Painel">
                                <i class="s16 icomoon-icon-screen-2"></i>
                            </a>
                            <span class="divider">
                                <i class="s16 icomoon-icon-arrow-right-3"></i>
                            </span>
                        </li>
                        <li>
                            <a class="tip" title="<?php echo $this->module_title; ?>" href="<?php echo $this->module_link;?>">
                                <i class="s16 <?php echo $this->module_icon; ?>"></i>                                    
                            </a>
                        </li>
                        <span class="divider">
                            <i class="s16 icomoon-icon-arrow-right-3"></i>
                        </span>
                        <li class="active">Registro</li>
                    </ul>
                </div>
                <!-- End .heading-->

                <form name="main" enctype="multipart/form-data" method="post" class="form-horizontal group-border">
                    <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
                    <input type="hidden" name="retorno" value="<?php echo $this->retorno; ?>">

                    <!-- Start .row -->
                    <div class="row">
                        <div class="col-lg-12">
                            <!-- Start .panel -->
                            <div class="panel panel-default toggle">
                                <div class="panel-heading">
                                    <h4 class="panel-title">Dados do pedido</h4>
                                </div>
                                <!-- Start .panel-body -->
                                <div class="panel-body">

                                    <div class="form-group">
                                        <label class="col-lg-2 control-label" for="nome">Pedidos:</label>
                                        <div class="col-lg-10 pedido_ordem">
                                            <a href="/sistema/order/edit/id/42001">42001</a>
                                        </div>
                                    </div><!-- End .form-group  -->

                                    <div class="form-group">
                                        <label class="col-lg-2 control-label" for="nome">Produtos:</label>
                                        <div class="col-lg-10 pedido_ordem">
                                            <a>Mesa de Poker Profissional</a>
                                            <a>Maleta de com 500 Fichas</a>
                                        </div>
                                    </div><!-- End .form-group  -->

                                    <div class="form-group">
                                        <label class="col-lg-2 control-label" for="nome">Nota fiscal:</label>
                                        <div class="col-lg-10">
                                            <input class="form-control" type="text" value="000441" />
                                        </div>
                                    </div><!-- End .form-group  -->
                                </div>
                                <!-- End .panel-body -->
                            </div>
                            <!-- End .panel -->

                            <!-- Start .panel -->
                            <div class="panel panel-default toggle">
                                <div class="panel-heading">
                                    <h4 class="panel-title">Dados da entrega</h4>
                                </div>
                                <!-- Start .panel-body -->
                                <div class="panel-body">
                                    <div class="form-group">
                                        <label class="col-lg-2 control-label" for="nome">Entrega:</label>
                                        <div class="col-lg-10">
                                            <input class="form-control" type="text" value="10/07/2025" />
                                        </div>
                                    </div><!-- End .form-group  -->

                                    <div class="form-group">
                                        <label class="col-lg-2 control-label" for="nome">CEP:</label>
                                        <div class="col-lg-10">
                                            <input class="form-control" type="text" value="74580-340" />
                                        </div>
                                    </div><!-- End .form-group  -->

                                    <div class="form-group">
                                        <label class="col-lg-2 control-label" for="nome">Rua:</label>
                                        <div class="col-lg-10">
                                            <input class="form-control" type="text" value="Rua sp 12" />
                                        </div>
                                    </div><!-- End .form-group  -->

                                    <div class="form-group">
                                        <label class="col-lg-2 control-label" for="nome">Número:</label>
                                        <div class="col-lg-10">
                                            <input class="form-control" type="text" value="s/n" />
                                        </div>
                                    </div><!-- End .form-group  -->

                                    <div class="form-group">
                                        <label class="col-lg-2 control-label" for="nome">Complemento:</label>
                                        <div class="col-lg-10">
                                            <input class="form-control" type="text" value="Q 5 Lt 12, próximo ao pamonharia souza" />
                                        </div>
                                    </div><!-- End .form-group  -->

                                    <div class="form-group">
                                        <label class="col-lg-2 control-label" for="nome">Bairro:</label>
                                        <div class="col-lg-10">
                                            <input class="form-control" type="text" value="Setor Perim" />
                                        </div>
                                    </div><!-- End .form-group  -->

                                    <div class="form-group">
                                        <label class="col-lg-2 control-label" for="nome">Cidade:</label>
                                        <div class="col-lg-10">
                                            <input class="form-control" type="text" value="Goiânia" />
                                        </div>
                                    </div><!-- End .form-group  -->

                                    <div class="form-group">
                                        <label class="col-lg-2 control-label" for="nome">Estado:</label>
                                        <div class="col-lg-10">
                                            <input class="form-control" type="text" value="GO" />
                                        </div>
                                    </div><!-- End .form-group  -->

                                    <div class="form-group">
                                        <label class="col-lg-2 control-label" for="nome">Destinatário:</label>
                                        <div class="col-lg-10">
                                            <input class="form-control" type="text" value="João Felipe" />
                                        </div>
                                    </div><!-- End .form-group  -->

                                    <div class="form-group">
                                        <label class="col-lg-2 control-label" for="nome">Telefone:</label>
                                        <div class="col-lg-10">
                                            <input class="form-control" type="text" value="(27) 99666-1369" />
                                        </div>
                                    </div><!-- End .form-group  -->

                                    <div class="form-group">
                                        <label class="col-lg-2 control-label" for="nome">CPF/CNPJ:</label>
                                        <div class="col-lg-10">
                                            <input class="form-control" type="text" value="088.921.667-35" />
                                        </div>
                                        <div class="col-lg-12">
                                            <button style="margin: 20px 15px 0 auto; display: block;" type="button" class="btn btn-info clickformsubmit">Salvar dados</button>
                                        </div>
                                    </div><!-- End .form-group  -->                                    
                                </div>
                                <!-- End .panel-body -->
                            </div>
                            <!-- End .panel -->

                            <!-- Start .panel -->
                            <div class="panel panel-default toggle">
                                <div class="panel-heading">
                                    <h4 class="panel-title">Dados da embalagem</h4>
                                </div>
                                <!-- Start .panel-body -->
                                <div class="panel-body">
                                    <div class="form-group">
                                        <label class="col-lg-2 control-label" for="telefone_atendente">Volumes:</label>
                                        <div class="col-lg-10 embalagens">
                                            <div class="embalagem">
                                                <h3>
                                                    <span class="name">Suporte da borda</span>
                                                    <span class="order">42001</span>
                                                </h3>
                                                <div>
                                                    <span class="title">Comprimento: </span>
                                                    <span class="value">20cm</span>
                                                </div>
                                                <div>
                                                    <span class="title">Largura: </span>
                                                    <span class="value">10cm</span>
                                                </div>
                                                <div>
                                                    <span class="title">Altura: </span>
                                                    <span class="value">5cm</span>
                                                </div>
                                                <div>
                                                    <span class="title">Peso: </span>
                                                    <span class="value">5kg</span>
                                                </div>
                                                <div>
                                                    <span class="title">Embalagem: </span>
                                                    <span class="value">Parte de cima da mesa</span>
                                                </div>
                                            </div>
                                            <div class="embalagem">
                                                <h3>
                                                    <span class="name">Borda da mesa</span>
                                                    <span class="order">42001</span>
                                                </h3>
                                                <div>
                                                    <span class="title">Comprimento: </span>
                                                    <span class="value">100cm</span>
                                                </div>
                                                <div>
                                                    <span class="title">Largura: </span>
                                                    <span class="value">50cm</span>
                                                </div>
                                                <div>
                                                    <span class="title">Altura: </span>
                                                    <span class="value">15cm</span>
                                                </div>
                                                <div>
                                                    <span class="title">Peso: </span>
                                                    <span class="value">25kg</span>
                                                </div>
                                                <div>
                                                    <span class="title">Embalagem: </span>
                                                    <span class="value">Parte de cima da mesa</span>
                                                </div>
                                            </div>

                                            <div class="embalagem">
                                                <h3>
                                                    <span class="name">Tampa da mesa</span>
                                                    <span class="order">42001</span>
                                                </h3>
                                                <div>
                                                    <span class="title">Comprimento: </span>
                                                    <span class="value">20cm</span>
                                                </div>
                                                <div>
                                                    <span class="title">Largura: </span>
                                                    <span class="value">10cm</span>
                                                </div>
                                                <div>
                                                    <span class="title">Altura: </span>
                                                    <span class="value">5cm</span>
                                                </div>
                                                <div>
                                                    <span class="title">Peso: </span>
                                                    <span class="value">5kg</span>
                                                </div>
                                                <div>
                                                    <span class="title">Embalagem: </span>
                                                    <span class="value">Parte de cima da mesa</span>
                                                </div>
                                            </div>
                                            <div class="embalagem">
                                                <h3>
                                                    <span class="name">Peças de encaixe</span>
                                                    <span class="order">42001</span>
                                                </h3>
                                                <div>
                                                    <span class="title">Comprimento: </span>
                                                    <span class="value">5cm</span>
                                                </div>
                                                <div>
                                                    <span class="title">Largura: </span>
                                                    <span class="value">5cm</span>
                                                </div>
                                                <div>
                                                    <span class="title">Altura: </span>
                                                    <span class="value">5cm</span>
                                                </div>
                                                <div>
                                                    <span class="title">Peso: </span>
                                                    <span class="value">1kg</span>
                                                </div>
                                                <div>
                                                    <span class="title">Embalagem: </span>
                                                    <span class="value">Parte de cima da mesa</span>
                                                </div>
                                            </div>
                                            <div class="embalagem">
                                                <h3>
                                                    <span class="name">Outros volumes</span>
                                                    <span class="order">42001</span>
                                                </h3>
                                                <div>
                                                    <span class="title">Comprimento: </span>
                                                    <span class="value">100cm</span>
                                                </div>
                                                <div>
                                                    <span class="title">Largura: </span>
                                                    <span class="value">50cm</span>
                                                </div>
                                                <div>
                                                    <span class="title">Altura: </span>
                                                    <span class="value">10cm</span>
                                                </div>
                                                <div>
                                                    <span class="title">Peso: </span>
                                                    <span class="value">20kg</span>
                                                </div>
                                                <div>
                                                    <span class="title">Embalagem: </span>
                                                    <span class="value">Parte de baixo da mesa</span>
                                                </div>
                                            </div>
                                            <div class="embalagem">
                                                <h3>
                                                    <span class="name">Maleta com fichas</span>
                                                    <span class="order">42001</span>
                                                </h3>
                                                <div>
                                                    <span class="title">Comprimento: </span>
                                                    <span class="value">25cm</span>
                                                </div>
                                                <div>
                                                    <span class="title">Largura: </span>
                                                    <span class="value">15cm</span>
                                                </div>
                                                <div>
                                                    <span class="title">Altura: </span>
                                                    <span class="value">10cm</span>
                                                </div>
                                                <div>
                                                    <span class="title">Peso: </span>
                                                    <span class="value">5kg</span>
                                                </div>
                                                <div>
                                                    <span class="title">Embalagem: </span>
                                                    <span class="value">Parte de baixo da mesa</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div><!-- End .form-group  -->

                                    <div class="form-group">
                                        <label class="col-lg-2 control-label" for="nome">Embalagens:</label>
                                        <div class="col-lg-10">
                                            <input readonly class="form-control" type="text" value="2" />
                                        </div>
                                    </div><!-- End .form-group  -->

                                    <div class="form-group">
                                        <label class="col-lg-2 control-label" for="telefone_atendente"></label>
                                        <div class="col-lg-10 embalagens">
                                            <div class="embalagem">
                                                <h3>
                                                    <span>Parte de cima da mesa</span>
                                                    <button class="edit"><i class="s16 icomoon-icon-pencil-4"></i></button>
                                                </h3>
                                                <div>
                                                    <span class="title">Comprimento: </span>
                                                    <span class="value">200cm</span>
                                                </div>
                                                <div>
                                                    <span class="title">Largura: </span>
                                                    <span class="value">100cm</span>
                                                </div>
                                                <div>
                                                    <span class="title">Altura: </span>
                                                    <span class="value">15cm</span>
                                                </div>
                                                <div>
                                                    <span class="title">Peso: </span>
                                                    <span class="value">50kg</span>
                                                </div>
                                                <div>
                                                    <button type="button" class="btn btn-warning" style="
                                                        padding: 2px 5px;
                                                        margin: 0 0 5px;
                                                        font-size: 1em;
                                                    ">Refazer checagem</button>
                                                </div>
                                            </div>
                                            <div class="embalagem">
                                                <h3>
                                                    <span>Parte de baixo da mesa</span>
                                                    <button class="edit"><i class="s16 icomoon-icon-pencil-4"></i></button>
                                                </h3>
                                                <div>
                                                    <span class="title">Comprimento: </span>
                                                    <span class="value">100cm</span>
                                                </div>
                                                <div>
                                                    <span class="title">Largura: </span>
                                                    <span class="value">50cm</span>
                                                </div>
                                                <div>
                                                    <span class="title">Altura: </span>
                                                    <span class="value">10cm</span>
                                                </div>
                                                <div>
                                                    <span class="title">Peso: </span>
                                                    <span class="value">20kg</span>
                                                </div>
                                                <div>
                                                    <button type="button" class="btn btn-warning" style="
                                                        padding: 2px 5px;
                                                        margin: 0 0 5px;
                                                        font-size: 1em;
                                                    ">Refazer checagem</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div><!-- End .form-group  -->

                                </div>
                                <!-- End .panel-body -->
                            </div>
                            <!-- End .panel -->

                            <!-- Start .panel -->
                            <div class="panel panel-default toggle">
                                <div class="panel-heading">
                                    <h4 class="panel-title">Orçamentos com transportadoras</h4>
                                </div>
                                <div class="panel-body orcamento">

                                    <table cellpadding="0" cellspacing="0" border="0" class="tabletools table table-striped table-bordered" width="100%">
                                        <thead>
                                            <tr>
                                                <th class="tal" width="100px">Data</th>
                                                <th class="tal" width="100px">Coleta</th>
                                                <th class="tal" width="100px">Valor</th>
                                                <th class="tal">Empresa</th>
                                                <th class="tal">Observação</th>
                                                <th class="tal" width="50px">Ações</th>
                                                <th class="tal" width="50px"><button type="button" class="btn btn-info adicionar_orcamento">Adicionar Orçamento</button></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>30/04/2025</td>
                                                <td>05/07/2025</td>
                                                <td>500,00</td>
                                                <td>IDlog Transportes</td>
                                                <td>-</td>
                                                <td>
                                                    <a><i class="s12 icomoon-icon-pencil"></i></a>
                                                    <a class="bt_system_delete" data-controller="" data-id=""><i class="s12 icomoon-icon-remove"></i></a>
                                                </td>
                                                <td>
                                                   <button type="button" class="btn btn-success">Expedição</button>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>01/05/2025</td>
                                                <td>05/07/2025</td>
                                                <td>450,00</td>
                                                <td>ACCERT</td>
                                                <td>-</td>
                                                <td>
                                                    <a><i class="s12 icomoon-icon-pencil"></i></a>
                                                    <a class="bt_system_delete" data-controller="" data-id=""><i class="s12 icomoon-icon-remove"></i></a>
                                                </td>
                                                <td>
                                                   <button type="button" class="btn btn-success">Expedição</button>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <!-- End .panel -->
                        </div>
                    </div>
                    <!-- End .row -->
                </form>

                <?php require_once "layouts/options.phtml"; ?>
            </div>
            <!-- End contentwrapper -->
        </div>
        <!-- End #content -->

        <?php  require_once "layouts/footer.phtml"; ?>
    </div>

    <div class="modal fade" id="modal-orcamento" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" style="width:50vw; height:90vh;">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">Fazer orçamento</h4>
                </div>
                <div class="modal-body">
                    <form action="javascript:;" enctype="multipart/form-data" method="post" class="form-horizontal group-border">
                        <input type="hidden" name="id_orcamento" />
                        <input type="hidden" class="frete_nome" name="frete_nome" />
                        <input type="hidden" class="frete_prazo" name="frete_prazo" />
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <!-- Start .panel -->
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Dados</h4>
                                    </div>
                                    <div class="panel-body">
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="metodo_pagamento">Transportadora:</label>
                                            <div class="col-lg-10">
                                                <select name="metodo_pagamento" id="metodo_pagamento" class="form-control">
                                                    <option value="">Selecione</option>
                                                    <option value="">IDlog Transportes</option>
                                                    <option value="">ACCERT</option>
                                                    <option value="">ALFA</option>
                                                    <option value="">AMAZON</option>
                                                    <option value="">ATUAL CARGAS</option>
                                                    <option value="">B SILVA TRANSPORTES</option>
                                                    <option value="">BBT TRANSPORTES</option>
                                                </select>
                                            </div>
                                        </div><!-- End .form-group  -->

                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="">Coleta:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="" id=""  type="date" value="" />
                                            </div>
                                        </div><!-- End .form-group  -->

                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="">Valor:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="" id=""  type="text" value="" />
                                            </div>
                                        </div><!-- End .form-group  -->

                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="">Obervação:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="" id=""  type="text" value="" />
                                            </div>
                                        </div><!-- End .form-group  -->
                                    </div>
                                </div>
                            </div>
                        </div><!-- End .panel -->
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-success" data-dismiss="modal">Adicionar Orçamento</button>
                </div>
            </div>
        </div>
    </div>

    <?php  require_once "layouts/plugins.phtml"; ?>

    <!-- Init plugins only for page -->
    <script type="text/javascript">
        $(document).ready(function() {
            $('body').on('click', 'button.adicionar_orcamento', function () {
                $('#modal-orcamento').modal('show');
            });
        });
    </script>

</body>
</html>
