<?php
    require_once "layouts/headers.phtml";
?>
    <script type="text/javascript">
        var pagina = "<?php echo $this->getModule(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getModule(); ?>";
    </script>
</head>

<body>
    <?php require_once "layouts/header.phtml"; ?>

    <!-- / #header -->
    <div id="wrapper">
    <!-- #wrapper -->

        <?php  require_once "layouts/sidebar.phtml"; ?>

        <!--Body content-->
        <div id="content" class="page-content clearfix">
            <!--Content wrapper-->
            <div class="contentwrapper">
                <!-- .heading -->
                <div class="heading">
                    <h3><?php echo $this->module_title; ?></h3>
                    <ul class="breadcrumb">
                        <li>Você está aqui:</li>
                        <li>
                            <a href="#" class="tip" title="Painel">
                                <i class="s16 icomoon-icon-screen-2"></i>
                            </a>
                            <span class="divider">
                                <i class="s16 icomoon-icon-arrow-right-3"></i>
                            </span>
                        </li>
                        <li class="active"><?php echo $this->module_title;?></li>
                    </ul>
                </div>
                <!-- End .heading-->
                <!-- Start .row -->
                <div class="row">
                    <div class="col-lg-12">
                        <!-- Start .panel -->
                        <div class="panel panel-default toggle panelClose">
                            <div class="panel-heading">
                                <h4 class="panel-title"><i class="<?php echo $this->module_icon ?>"></i> Tabela de Remessas
                                    <label class="select-all">Selecionar estes <input type="checkbox" id="apagar_todos"></label>
                                </h4>
                            </div>
                            <!-- Start .panel-body -->
                            <?php
                                $protocolo = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? "https" : "http";
                                $host = $_SERVER['HTTP_HOST'];
                                $path = rtrim(dirname($_SERVER['SCRIPT_NAME']), '/\\');
                                
                                $site_url = "{$protocolo}://{$host}{$path}/";
                            ?>
                            <div class="panel-body">
                                <table width="100%" cellpadding="0" cellspacing="0" border="0" class="tabletools table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th class="tal">Remessa</th>
                                            <th class="tal">Pedidos</th>
                                            <th class="tal">Cliente</th>
                                            <th class="tal">Saída</th>
                                            <th class="tal">Entrega</th>
                                            <th class="tal">Destino</th>
                                            <th class="tal">Orçamentos</th>
                                            <th class="tal">Produção</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td class="tal" style="background: #ffc3c3;"><a href="<?php echo $this->getModule()?>/edit/id/0">5949-1</a></td>
                                            <td class="tal" style="background: #ffc3c3;"><a href="<?php echo $site_url?>sistema/order/edit/id/42001">5949</a></td>
                                            <td class="tal" style="background: #ffc3c3;">Bruno</td>
                                            <td class="tal" style="background: #ffc3c3;">20/05/2025</td>
                                            <td class="tal" style="background: #ffc3c3;">22/05/2025<i title="Data alterada" class="brocco-icon-warning"></i></td>
                                            <td class="tal" style="background: #ffc3c3;">Inhumas / GO</td>
                                            <td class="tal" style="background: #ffc3c3;">3</td>
                                            <td class="tal" style="background: #ffc3c3;">Não</td>
                                        </tr>
                                        <tr>
                                            <td class="tal" style="background: #fdff9e;"><a href="<?php echo $this->getModule()?>/edit/id/0">5950-1</a></td>
                                            <td class="tal" style="background: #fdff9e;">
                                                <a href="<?php echo $site_url?>sistema/order/edit/id/42001">5950</a><br>
                                                <a href="<?php echo $site_url?>sistema/order/edit/id/42001">5951</a>
                                            </td>
                                            <td class="tal" style="background: #fdff9e;">Bruno</td>
                                            <td class="tal" style="background: #fdff9e;">
                                                24/05/2025<br>
                                                26/05/2025
                                            </td>
                                            <td class="tal" style="background: #fdff9e;">28/05/2025</td>
                                            <td class="tal" style="background: #fdff9e;">Goiânia / GO</td>
                                            <td class="tal" style="background: #fdff9e;">4</td>
                                            <td class="tal" style="background: #fdff9e;">Não</td>
                                        </tr>

                                        <tr>
                                            <td class="tal">
                                                5952-1<br>
                                                5952-2
                                            </td>
                                            <td class="tal"><a href="<?php echo $site_url?>sistema/order/edit/id/42001">5952</a></td>
                                            <td class="tal">Bruno</td>
                                            <td class="tal">28/05/2025</td>
                                            <td class="tal">01/06/2025</td>
                                            <td class="tal">Goiânia / GO</td>
                                            <td class="tal">0</td>
                                            <td class="tal">Sim</td>
                                        </tr>
                                    </tbody>
                                </table>

                            </div>
                            <!-- End .panel-body -->
                        </div>
                        <!-- End .panel -->
                    </div>
                </div>
                <!-- End .row -->
                <?php require_once "layouts/options.phtml"; ?>
            </div>
            <!-- End contentwrapper -->
        </div>
        <!-- End #content -->

        <?php  require_once "layouts/footer.phtml"; ?>
    
    </div>

    <?php  require_once "layouts/plugins.phtml"; ?>

    <!-- Table plugins -->
    <script src="plugins/tables/dataTables/jquery.dataTables.js"></script>
    <script src="plugins/tables/dataTables/dataTables.tableTools.js"></script>
    <script src="plugins/tables/dataTables/dataTables.bootstrap.js"></script>
    <script src="plugins/tables/dataTables/dataTables.responsive.js"></script>


    <!-- Init plugins only for page -->
    <script type="text/javascript">
        $(document).ready(function(){

            //--------------- Data tables ------------------//
            if($('table').hasClass('tabletools')){
                $('.tabletools').dataTable( {
                    "oLanguage": {
                        "sSearch": "",
                        "sLengthMenu": "<span>_MENU_</span>",
                        "sProcessing":   "Processando...",                    
                        "sZeroRecords":  "Não foram encontrados resultados",
                        "sInfo":         "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                        "sInfoEmpty":    "Mostrando de 0 até 0 de 0 registros",
                        "sInfoFiltered": "(filtrado de _MAX_ registros no total)",
                        "sInfoPostFix":  "",
                        "sUrl":         "",

                        "oPaginate": {
                            "sFirst":    "Primeiro",
                            "sPrevious": "Anterior",
                            "sNext":     "Seguinte",
                            "sLast":     "Último"
                        }
                    },
                    "sDom": "T<'row'<'col-md-6 col-xs-12 'l><'col-md-6 col-xs-12'f>r>t<'row'<'col-md-4 col-xs-12'i><'col-md-8 col-xs-12'p>>",
                    "aaSorting":[[0,"asc"]], "iDisplayLength": 100,
                    tableTools: {
                        "sSwfPath": "http://cdn.datatables.net/tabletools/2.2.2/swf/copy_csv_xls_pdf.swf",
                        "aButtons": [
                        ]
                    }


                });

            }

        });
    </script>

</body>
</html>
