<?php
    require_once "layouts/headers.phtml";
?>

    <script type="text/javascript">
        var pagina = "<?php echo $this->getModule(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getModule(); ?>/save";
        var retorno = "<?php echo $this->retorno; ?>";
    </script>
    <style type="text/css">
        
        #bt-order-up,#bt-order-down {
            position: relative;
            width: 30px;
            height: 25px;
        }

        #bt-order-up span, #bt-order-down span {
            display: block;
            position: absolute;
            width: 20px;
            height: 20px;
            top: 50%;
            bottom: 50%;
            margin-top: -10px;
            margin-left: 3px;
            transform: rotate(90deg);
            font-size: 20px;
            text-align: center;
        }

        .order-table {
            width: 100%;
            border: 1px solid #000;
            border-collapse: collapse;
        }

        .order-table tr td {
            padding: 3px 10px;
            border-bottom: 1px solid #000;
        }

        .order-table tr td i {
            cursor: pointer;
        }

        .avulso {
            margin-top: 40px;
        }

        .avulso .tit {
            font-size: 18px;
            font-weight: bold;
        }

        .avulso span {
            display: inline-block;
            width: 60px;
            margin-right: 5px;
            text-align: right;
        }

        .avulso .line { margin: 10px 0; }

        #avulso_servico {
            display: inline;
            width: 200px;
        }

        #avulso_tempo {
            display: inline;
            width: 60px;
        }

        #avulso_save {
            margin-left: 68px;
        }

        .apto {
            background-color: #5CFF26;
        }

    </style>
    </head>  
    
    
    <body>
<?php  require_once "layouts/header.phtml"; ?>

        <!-- / #header -->
        <div id="wrapper">
        <!-- #wrapper -->

<?php  require_once "layouts/sidebar.phtml"; ?>
            
            <!--Body content-->
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <!--Content wrapper-->
                    <div class="heading">
                        <!--  .heading-->
                        <h3><?php echo $this->module_title; ?></h3>

                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li>
                                <a href="#" class="tip" title="Painel">
                                    <i class="s16 icomoon-icon-screen-2"></i>
                                </a>
                                <span class="divider">
                                    <i class="s16 icomoon-icon-arrow-right-3"></i>
                                </span>
                            </li>
                            <li>
                                <a class="tip" title="<?php echo $this->module_title; ?>" href="<?php echo $this->module_link;?>">
                                    <i class="s16 <?php echo $this->module_icon; ?>"></i>                                    
                                </a>
                            </li>
                            <span class="divider">
                                <i class="s16 icomoon-icon-arrow-right-3"></i>
                            </span>
                            <li class="active">Registro</li>
                        </ul>
                    </div>

                    <!-- End  / heading-->
                    <!-- Start .row -->
                  
                    <form name="main" enctype="multipart/form-data" method="post" class="form-horizontal group-border">
                        <input type="hidden" name="id" value="<?php echo $this->id; ?>" />                        
                        <input type="hidden" name="retorno" value="<?php echo $this->retorno; ?>">
                        
                        <div class="row">
                            <div class="form-group">
                                <label class="col-lg-1 control-label" for="nome">Equipe:</label>
                                <div class="col-lg-2">
                                    <select class="form-control" id="equipes">
                                        <?php if ($this->equipes->num_rows): ?>
                                            <?php foreach ($this->equipes->rows as $equipe): ?>
                                                <?php if ($this->id=='' || $equipe['id_equipe']!=$this->id): ?>
                                                    <option value="<?php echo $equipe['id'] ?>"><?php echo $equipe['nome'] ?></option>
                                                <?php endif ?>
                                            <?php endforeach ?>
                                        <?php endif ?>
                                    </select>
                                </div>
                                <label class="col-lg-1 control-label" for="nome">Data:</label>
                                <div class="col-lg-1">
                                    <input class="form-control" name="data" id="data" type="text" value="<?php echo date("d/m/Y"); ?>" />
                                </div>
                                <label class="col-lg-2 control-label" for="nome">Pesquisar nº pedido:</label>
                                <div class="col-lg-1">
                                    <input class="form-control" name="pedido" id="pedido" type="text" value="" />
                                </div>
                                <button type="button" class="btn btn-info buscar_pedido">TRAZER PEDIDO</button>
                            </div>
                        </div>
                        <br><br>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <!-- Start .panel -->
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Dados da Equipe</h4>
                                    </div>
                                    <div class="panel-body">
                                        <div class="form-group">
                                            <div class="col-lg-4">
                                                <div id="equipe"></div>
                                                <br><br><button class="btn btn-info imprimir">IMPRIMIR</button>
                                            </div>
                                            <div class="col-lg-8">
                                                <div class="leftBox">
                                                    <h5>Usuários</h5>

                                                    <select id="box1View" multiple="multiple" class="multiple nostyle form-control" style="height:300px;">
                                                        <?php if ($this->users->num_rows): ?>
                                                            <?php foreach ($this->users->rows as $user): ?>
                                                                <?php if ($this->id=='' || $user['id_equipe']!=$this->id): ?>
                                                                    <option value="<?php echo $user['id'] ?>"><?php echo $user['nome'] ?></option>
                                                                <?php endif ?>
                                                            <?php endforeach ?>
                                                        <?php endif ?>
                                                    </select>
                                                    <br>
                                                    <button class="btn btn-info" id="save">SALVAR</button>
                                                    <button id="bt-order-up"><span>&#8249;</span></button>
                                                    <button id="bt-order-down"><span>&#8250;</span></button>
                                                    
                                                    <div class="avulso">
                                                        <div class="tit">Adicionar item manualmente</div>
                                                        <div class="line"><span>Descrição:</span> <input type="text" id="avulso_servico"> </div>
                                                        <div class="line"><span>Tempo:</span> <input type="text" id="avulso_tempo"> </div>
                                                        <button id="avulso_save">ADICIONAR</button>
                                                    </div>
                                                </div>

                                                <div class="dualBtn">

                                                    <button id="to2" type="button" class="btn" ><span class="icon12 minia-icon-arrow-right-3"></span></button>
                                                    <button id="allTo2" type="button" class="btn" ><span class="icon12 iconic-icon-last"></span></button>
                                                    <button id="to1" type="button" class="btn marginT5"><span class="icon12 minia-icon-arrow-left-3"></span></button>
                                                    <button id="allTo1" type="button"class="btn marginT5" ><span class="icon12 iconic-icon-first"></span></button>

                                                </div>

                                                <div class="rightBox">
                                                    <h5>Equipe</h5>
                                                    <select id="box2View" multiple="multiple" name="usuarios[]" class="multiple nostyle form-control" style="height:300px;">
                                                        <?php if ($this->id != ''): ?>
                                                            <?php if ($this->users->num_rows): ?>
                                                                <?php foreach ($this->users->rows as $user): ?>
                                                                    <?php if ($user['id_equipe']==$this->id): ?>
                                                                        <option value="<?php echo $user['id'] ?>"><?php echo $user['nome'] ?></option>
                                                                    <?php endif ?>
                                                                <?php endforeach ?>
                                                            <?php endif ?>
                                                        <?php endif ?>
                                                    </select>
                                                    <br>                                                    
                                                </div>
                                            </div>
                                        </div><!-- End .form-group  -->
                                    </div>
                                </div>
                            </div>                                
                        </div>
                        <?php /* ?>
                        <div class="form-group">
                            <div class=" col-lg-10">
                                <?php if ($this->id==""): ?>
                                    <?php if (!$this->permissions[$this->permissao_ref]['gravar']): ?>
                                        <span class="label label-warning "><span class="icon24 typ-icon-warning"></span>Você não tem permissão para gravar esta função.</span>
                                    <?php else: ?>
                                        <button type="button" class="btn btn-info clickformsubmit">SALVAR EQUIPE</button>
                                    <?php endif ?>
                                <?php else: ?>
                                    <?php if (!$this->permissions[$this->permissao_ref]['editar']): ?>
                                        <span class="label label-warning"><span class="icon24 icomoon-icon-warning "></span>Você não tem permissão para editar esta função.</span>
                                    <?php else: ?>
                                        <button type="button" class="btn btn-info clickformsubmit">SALVAR EQUIPE</button>
                                    <?php endif ?>
                                <?php endif ?>
                            </div>
                        </div><!-- End .form-group  -->
                        <?php */ ?>
                    </form>
                                        
                </div>
                <!-- End contentwrapper -->
            </div>
            <!-- End #content -->
            
            
<?php  require_once "layouts/footer.phtml"; ?>
        
        </div>
        
<?php  require_once "layouts/plugins.phtml"; ?>
        <!-- Init plugins only for page -->        
        <script type="text/javascript" src="plugins/forms/dualselect/jquery.dualListBox-1.3.min.js"></script>
        <script type="text/javascript">
            equipe = "";
            user = 0;
            date_flag = true;

            $(document).ready(function(){
                $.configureBoxes(); 

                $("#pedido, #avulso_tempo").mask('000000');
                $("#data").mask('00/00/0000');
                $("#data").datepicker({
                    dateFormat: 'dd/mm/yy',
                    dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'],
                    dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
                    dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
                    monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
                    monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
                    nextText: 'Próximo',
                    prevText: 'Anterior'
                });

                $("#data").change(getDia);

                $('button').click(function(e){
                    e.preventDefault();
                });

                getEquipe();
                $("#equipes").change(getEquipe);
                $(".buscar_pedido").click(getPedido);

                $("#save").click(postFuncionario);
                $("#bt-order-up").click(orderUp);
                $("#bt-order-down").click(orderDown);

                $("#avulso_save").click(saveAvulso);
                $(".imprimir").click(imprimir);
                
            });

            function getDate(){
                data = $("#data").val();
                data = data.split('/');
                return data[2]+'-'+data[1]+'-'+data[0];
            }

            function imprimir(){
                data = getDate();
                window.open("<?php echo $this->getModule(); ?>/print/date/"+data);
            }

            function getDia(){
                if(date_flag){ //hack para não executar mais de uma vez.
                    date_flag=false;
                    getEquipe();
                }
            }

            function getEquipe(){
                equipe = $("#equipes option:selected").val();
                user = 0;
                $.get("productionorder/getequipe/id/"+equipe, function(data){
                    var funcionarios = JSON.parse(data);
                    $("#equipe").empty();
                    for(i=0;i<funcionarios.length;i++){
                        //$("#equipe").append(funcionarios[i]);
                        $("#equipe").append('<div class="funcionario"><label><input type="radio" name="funcionario" value="'+funcionarios[i].id_user+'">'+funcionarios[i].nome+'</label></div>');
                    }
                    date_flag=true;
                    uniform();
                    $("input[name=funcionario]").change(getFuncionario);
                });
            }

            function getPedido(){
                var pedido = $("#pedido").val();
                if(pedido!=""){
                    $.get("productionorder/getpedido/id/"+pedido+"/equipe/"+equipe+"/user/"+user, function(data){
                        //console.log(data);
                        var servicos = JSON.parse(data);
                        $("#box2View").empty();
                        var apto = "";
                        for(i=0;i<servicos.length;i++){
                            apto="";
                            if(servicos[i].usuario_apto!="") apto = " class='apto'";
                            $("#box2View").append('<option '+apto+' value="'+servicos[i].id_carrinho_produto+'" data-servico="'+servicos[i].id_servico+'"  data-id_atributo="'+servicos[i].id_atributo+'" data-tempo="'+servicos[i].tempo+'" data-id_servico="'+servicos[i].id_servico+'"data-unidade="'+servicos[i].unidade+'">'+servicos[i].servico+'</option>');
                        }
                        uniform();
                    });
                }
            }

            function getFuncionario(){
                data = getDate();
                user = $("input[name=funcionario]:checked").val();
                $.get("productionorder/getfuncionario/user/"+user+"/date/"+data, function(data){
                    var servicos = JSON.parse(data);
                    $("#box1View").empty();
                    for(i=0;i<servicos.length;i++){
                        $("#box1View").append('<option value="'+servicos[i].id_carrinho_produto+'" data-servico="'+servicos[i].id_servico+'"  data-id_atributo="'+servicos[i].id_atributo+'" data-tempo="'+servicos[i].tempo+' "data-id_servico="'+servicos[i].id_servico+'" data-unidade="'+servicos[i].unidade+'">'+servicos[i].servico+'</option>');
                    }
                    uniform();
                    getPedido();
                    montaTabelaFuncionario(servicos);
                    //$(".order-table").remove().clone().appendTo($("input[name=funcionario]:checked").parents(".funcionario"));
                });

            }

            function postFuncionario(){
                var itens = [];
                var ordem = 1;
                data = $("#data").val();
                data = data.split('/');
                data = data[2]+'-'+data[1]+'-'+data[0];
                $("#box1View option").each(function(){
                    item = {
                        id_carrinho_produto: $(this).val(),
                        id_atributo: $(this).attr("data-id_atributo"),
                        id_servico: $(this).attr("data-id_servico"),
                        servico: $(this).text(),
                        tempo: $(this).attr("data-tempo"),
                        unidade: $(this).attr("data-unidade"),
                        ordem: ordem
                    }
                    itens.push(item);
                    ordem++;
                });
                $.post("productionorder/savefuncionario/user/"+user+"/date/"+data, {funcionarios:itens}, getFuncionario);
            }

            function orderUp(){
                var pos = $("#box1View option:selected").index();
                if(pos>0){                    
                    var selected = $("#box1View option:selected").clone().insertBefore("#box1View option:eq("+(pos-1)+")");
                    $("#box1View option:selected").remove();
                    $(selected)[0].selected = 'selected';
                }
            }

            function orderDown(){
                var pos = $("#box1View option:selected").index();
                var len = $("#box1View option").length;
                if(pos<(len-1)){
                    var selected = $("#box1View option:selected").clone().insertAfter("#box1View option:eq("+(pos+1)+")");
                    $("#box1View option:selected").remove();
                    $(selected)[0].selected = 'selected';
                }
            }

            function montaTabelaFuncionario(servicos){
                var inicio = 480; // 8 da manha + 15 min de reunião
                var almoco = 720; // meio dia
                var flag_almoco = false;
                var timer = inicio;
                var tabela = [];

                tabela.push({id:0,servico:"REUNIÃO",tempo:15,inicio:timer});
                timer += tabela[0].tempo;
                tabela[0].fim = timer;

                for(i=0;i<servicos.length;i++){
                    tabela.push({id:servicos[i].id,servico:servicos[i].servico,tempo:parseInt(servicos[i].tempo),inicio:timer,concluido:servicos[i].concluido});
                    len = tabela.length-1;
                    timer += tabela[len].tempo;
                    tabela[len].fim = timer;

                    if(!flag_almoco && timer>almoco){
                        resto = timer-almoco;
                        timer = almoco;
                        tabela[len].fim = timer;
                        tabela[len].tempo = tabela[len].fim-tabela[len].inicio;
                        timer = almoco+75;
                        tabela.push({id:0,servico:"ALMOÇO", tempo:75, inicio:almoco, fim:timer});
                        tabela.push({servico:tabela[len].servico, tempo:resto, inicio:timer, fim:(timer+resto)});
                        timer += resto;
                        flag_almoco = true;
                    }
                }

                if(tabela.length){
                    html='<table class="order-table"><tr><td>Descrição</td><td>Início</td><td>Fim</td><td>f</td></tr>';
                    for(i=0;i<tabela.length;i++){
                        // action = 1 (feito)
                        // action = 2 (nulo)
                        // action = 0 (não feito)
                        circle_color = 'orange';
                        action = 1;
                        console.log(tabela[i].concluido);
                        if(tabela[i].concluido=="0"){
                            circle_color = 'red';
                            action = 2;
                        }
                        if(tabela[i].concluido=="1"){
                            circle_color = 'green';
                            action = 0;
                        }
                        icon = '<i style="color:'+circle_color+'" data-id="'+tabela[i].id+'" data-action="'+action+'" class="concluido brocco-icon-circle"></i>';
                        if(!tabela[i].id) icon = '';
                        html += '<tr><td>'+tabela[i].servico+'</td><td>'+converterHoras(tabela[i].inicio)+'</td><td>'+converterHoras(tabela[i].fim)+'</td><td>'+icon+'</td></tr>';
                    }
                    html+='</table>';
                    $(".order-table").remove();
                    $(html).appendTo($("input[name=funcionario]:checked").parents(".funcionario"));

                    $(".concluido").click(function(){
                        id = $(this).attr('data-id');
                        action = $(this).attr('data-action');
                        $.post("productionorder/setconcluido/id/"+id+"/concluido/"+action, getFuncionario);
                    })
                }
            }

            function converterHoras(num){
                var hours = Math.floor(num / 60);
                var minutes = num % 60;
                return hours.toString().padStart(2,"0") + ":" + minutes.toString().padStart(2,"0");
            }

            function saveAvulso(){
                var servico = $("#avulso_servico").val();
                var tempo = $("#avulso_tempo").val();

                if(servico==""||tempo=="") return false;

                $("#box1View").append('<option value="" data-servico=""  data-id_atributo="" data-tempo="'+tempo+'">'+servico+'</option>');

            }

        </script>
    </body>
</html>
