<?php
    require_once "layouts/headers.phtml";
?>
    <link href="css/supr-theme/jquery.ui.supr.css" rel="stylesheet" type="text/css"/>
    <link href="plugins/misc/qtip/jquery.qtip.css" rel="stylesheet" type="text/css" />  
    
    <link href="plugins/files/elfinder/elfinder.css" type="text/css" rel="stylesheet" />
    <link href="plugins/files/plupload/jquery.ui.plupload/css/jquery.ui.plupload.css" type="text/css" rel="stylesheet" />

    <script type="text/javascript">
        var pagina = "<?php echo $this->getModule(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getModule(); ?>/save";
        var retorno = "<?php echo $this->retorno; ?>";
    </script>
    
    </head>  
    
    
    <body>
<?php  require_once "layouts/header.phtml"; ?>

        <!-- / #header -->
        <div id="wrapper">
        <!-- #wrapper -->

<?php  require_once "layouts/sidebar.phtml"; ?>
            
            <!--Body content-->
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <!--Content wrapper-->
                    <div class="heading">
                        <!--  .heading-->
                        <h3><?php echo $this->module_title; ?></h3>

                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li>
                                <a href="#" class="tip" title="Painel">
                                    <i class="s16 icomoon-icon-screen-2"></i>
                                </a>
                                <span class="divider">
                                    <i class="s16 icomoon-icon-arrow-right-3"></i>
                                </span>
                            </li>
                            <li class="active"><?php echo $this->module_title;?></li>
                        </ul>
                    </div>
                    <!-- End  / heading-->
                    <!-- Start .row -->
                   <div class="row">
                        <div class="col-lg-12">
                            <div class="panel panel-default toggle">
                                <!-- Start .panel -->
                                <div class="panel-heading">
                                    <h4 class="panel-title"><i class="s16 <?php echo $this->module_icon; ?>"></i> Gerenciador e envio de arquivo</h4>
                                </div>
                                <div class="panel-body noPad">
                                    <div id="elfinder"></div>
                                </div>
                            </div><!-- End .panel -->
                        </div><!-- End .span12 -->
                    </div><!-- End .row -->

                    <div class="row">
                        <div class="col-lg-12">
                            <div class="panel panel-default toggle">
                                <!-- Start .panel -->
                                <div class="panel-heading">
                                    <h4 class="panel-title"><i class="s16 <?php echo $this->module_icon; ?>"></i> Gerenciador de envio</h4>
                                </div>
                                <div class="panel-body noPad">
                                    <div id="html4_uploader" style="width: 100%; height: 100%;">O seu navegador não tem suporte HTML 4.</div>
                                </div>

                            </div><!-- End .panel -->

                        </div><!-- End .span12 -->

                    </div><!-- End .row -->
                    
                </div>
                <!-- End contentwrapper -->
            </div>
            <!-- End #content -->
            
            
<?php  require_once "layouts/footer.phtml"; ?>
        
        </div>
        
<?php  require_once "layouts/plugins.phtml"; ?>
        <!-- Init plugins only for page -->
        <script type="text/javascript" src="plugins/files/elfinder/elfinder.min.js"></script>
        <script type="text/javascript" src="plugins/files/plupload/plupload.js"></script>
        <script type="text/javascript" src="plugins/files/plupload/plupload.html4.js"></script>
        <script type="text/javascript" src="plugins/files/plupload/plupload.flash.js"></script>
        <script type="text/javascript" src="plugins/files/plupload/jquery.plupload.queue/jquery.plupload.queue.js"></script>
        <script type="text/javascript">
            $(document).ready(function(){
                 
                //------------- Elfinder file manager  -------------//
                var elf = $('#elfinder').elfinder({
                    lang: 'pt_BR',             // language (OPTIONAL)
                    url : 'System/includes/connector.php'  // connector URL (REQUIRED)
                }).elfinder('instance');

                //------------- Plupload php upload  -------------//
                // Setup html4 version
                $("#html4_uploader").pluploadQueue({
                    // General settings
                    runtimes : 'flash,silverlight,html4', 
                    url : 'System/includes/upload.php',
                    max_file_size : '10mb',
                    max_file_count: 15, // user can add no more then 15 files at a time
                    chunk_size : '1mb',
                    unique_names : false,
                    multiple_queues : true,

                    // Resize images on clientside if we can
                    //resize : {width : 320, height : 240, quality : 80},

                    // Rename files by clicking on their titles
                    rename: false,

                    // Sort files
                    sortable: true,

                    // Flash settings
                    flash_swf_url : 'plugins/files/plupload/plupload.flash.swf',

                    // Specify what files to browse for
                    filters : [
                        {title : "Image files", extensions : "jpg,gif,png"},
                        {title : "Zip files", extensions : "zip,avi,rar"}
                    ],

                    init : {
                        FileUploaded: function(up, file, info) {
                            // Called when all files are either uploaded or failed
                            elf.exec('reload');
                        },
                        UploadComplete: function(up, files) {
                            // Called when all files are either uploaded or failed
                            elf.exec('reload');
                        }
                    }

                });
            });
        </script>
    </body>
</html>
