<?php
    require_once "layouts/headers.phtml";
?>

    <script type="text/javascript">
        var pagina = "<?php echo $this->getModule(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getModule(); ?>/save";
        var retorno = "<?php echo $this->retorno; ?>";
    </script>
    
    </head>  
    
    
    <body>
<?php  require_once "layouts/header.phtml"; ?>

        <!-- / #header -->
        <div id="wrapper">
        <!-- #wrapper -->

<?php  require_once "layouts/sidebar.phtml"; ?>
            
            <!--Body content-->
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <!--Content wrapper-->
                    <div class="heading">
                        <!--  .heading-->
                        <h3><?php echo $this->module_title; ?></h3>

                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li>
                                <a href="#" class="tip" title="Painel">
                                    <i class="s16 icomoon-icon-screen-2"></i>
                                </a>
                                <span class="divider">
                                    <i class="s16 icomoon-icon-arrow-right-3"></i>
                                </span>
                            </li>
                            <li>
                                <a class="tip" title="<?php echo $this->module_title; ?>" href="<?php echo $this->module_link;?>">
                                    <i class="s16 <?php echo $this->module_icon; ?>"></i>                                    
                                </a>
                            </li>
                            <span class="divider">
                                <i class="s16 icomoon-icon-arrow-right-3"></i>
                            </span>
                            <li class="active">Registro</li>
                        </ul>
                    </div>
                    <!-- End  / heading-->
                    <!-- Start .row -->
                  
                    <form name="main" enctype="multipart/form-data" method="post" class="form-horizontal group-border">
                        <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
                        <input type="hidden" name="retorno" value="<?php echo $this->retorno; ?>">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <!-- Start .panel -->
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Dados do SEO</h4>
                                    </div>
                                    <div class="panel-body">
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="seo_title">Título:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="seo_title" id="seo_title" type="text" value="<?php echo $this->registro['seo_title'] ?>" />
                                            </div><!-- End .form-group  -->
                                        </div>
                                    
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="seo_description">Breve Descrição:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="seo_description" id="seo_description" type="text" value="<?php echo $this->registro['seo_description'] ?>" />
                                            </div><!-- End .form-group  -->
                                        </div>
                                    
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="seo_keywords">Palavras Chave:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="seo_keywords" id="seo_keywords" type="text" value="<?php echo $this->registro['seo_keywords'] ?>" />
                                            </div><!-- End .form-group  -->
                                        </div>
                                        
                                        
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="seo_url_breadcrumbs">Breadcrumbs:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="seo_url_breadcrumbs" id="seo_url_breadcrumbs" type="text" value="<?php echo $this->registro['seo_url_breadcrumbs'] ?>" />
                                            </div><!-- End .form-group  -->
                                        </div>
                                        
                                        
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="seo_url">URL Amigável:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="seo_url" id="seo_url" type="text" value="<?php echo $this->registro['seo_url'] ?>" />
                                            </div><!-- End .form-group  -->
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="seo_pagina_conteudo">Conteúdo:</label>
                                            <div class="col-lg-10">
                                                <textarea id="seo_pagina_conteudo" name="seo_pagina_conteudo" class="form-control tinymce" rows="10"><?php echo $this->registro['seo_pagina_conteudo'] ?></textarea>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="seo_scripts">Scripts:</label>
                                            <div class="col-lg-10">
                                                <textarea id="seo_scripts" name="seo_scripts" class="form-control elastic" rows="3"><?php echo stripslashes($this->registro['seo_scripts']) ?></textarea>
                                            </div>
                                        </div>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <?php if ($this->id==""): ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['gravar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning "><span class="icon24 typ-icon-warning"></span>Você não tem permissão para gravar esta função.</span>
                                        </div>
                                    </div><!-- End .form-group  -->   
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="button" class="btn btn-info clickformsubmit">Salvar novo</button>
                                        </div>
                                    </div><!-- End .form-group  -->
                                <?php endif ?>
                            <?php else: ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['editar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning"><span class="icon24 icomoon-icon-warning "></span>Você não tem permissão para editar esta função.</span>
                                        </div>
                                    </div><!-- End .form-group  -->   
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="button" class="btn btn-info clickformsubmit">Salvar alterações</button>
                                        </div>
                                    </div><!-- End .form-group  -->
                                <?php endif ?>
                            <?php endif ?>
                        </div><!-- End .row -->  
                    </form>
                </div>
                <!-- End contentwrapper -->
            </div>
            <!-- End #content -->
            
            
<?php  require_once "layouts/footer.phtml"; ?>
        
        </div>
        
<?php  require_once "layouts/plugins.phtml"; ?>
        <!-- Init plugins only for page -->
        <script src="plugins/forms/tiny_mce/tinymce.min.js"></script>
        <script src="plugins/forms/autosize/jquery.autosize.js"></script>
        <script src="plugins/files/plupload/plupload.js"></script>
        <script src="plugins/files/plupload/plupload.html4.js"></script>
        <script src="plugins/files/plupload/plupload.flash.js"></script>
        <script src="plugins/files/plupload/jquery.plupload.queue/jquery.plupload.queue.js"></script>
        <script type="text/javascript">
            $(document).ready(function(){
                tinymceInit({'galeria':true});                
                $('.elastic').autosize();
            });
        </script>
    </body>
</html>
