<?php
    require_once "layouts/headers.phtml";
?>

    <script type="text/javascript">
        var pagina = "<?php echo $this->getModule(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getModule(); ?>/save";
        var retorno = "<?php echo $this->retorno.$this->id_equipe; ?>";
    </script>
    
    </head>  
    
    
    <body>
<?php  require_once "layouts/header.phtml"; ?>

        <!-- / #header -->
        <div id="wrapper">
        <!-- #wrapper -->

<?php  require_once "layouts/sidebar.phtml"; ?>
            
            <!--Body content-->
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <!--Content wrapper-->
                    <div class="heading">
                        <!--  .heading-->
                        <h3><?php echo $this->module_title; ?></h3>

                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li>
                                <a href="#" class="tip" title="Painel">
                                    <i class="s16 icomoon-icon-screen-2"></i>
                                </a>
                                <span class="divider">
                                    <i class="s16 icomoon-icon-arrow-right-3"></i>
                                </span>
                            </li>
                            <li>
                                <a class="tip" title="<?php echo $this->module_title; ?>" href="<?php echo $this->module_link;?>">
                                    <i class="s16 <?php echo $this->module_icon; ?>"></i>                                    
                                </a>
                            </li>
                            <span class="divider">
                                <i class="s16 icomoon-icon-arrow-right-3"></i>
                            </span>
                            <li class="active">Registro</li>
                        </ul>
                    </div>
                    <!-- End  / heading-->
                    <!-- Start .row -->
                  
                    <form name="main" enctype="multipart/form-data" method="post" class="form-horizontal group-border">
                        <input type="hidden" name="id_usuario" value="<?php echo $this->id_usuario; ?>" />
                        <input type="hidden" name="id_equipe" value="<?php echo $this->id_equipe; ?>" />
                        <input type="hidden" name="retorno" value="<?php echo $this->retorno.$this->id_equipe; ?>">
                        
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <!-- Start .panel -->
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Capacitação do funcionário <u><?php echo $this->usuario; ?></u> (<u><?php echo $this->equipe ?></u>)</h4>
                                    </div>
                                    <div class="panel-body">
                                        <?php foreach ($this->servicos->rows as $servico): ?>
                                            <div class="col-lg-2">
                                                <label class="checkbox"><input type="checkbox" name="servicos[]" class="conj-servicos" value="<?php echo $servico['id'] ?>" <?php if($servico['id_servico']==$servico['id']) echo "checked='checked'"; ?>><?php echo $servico['nome'] ?></label>
                                            </div>
                                        <?php endforeach ?>
                                    </div>
                                </div>
                            </div>                                
                        </div>
                            
                        <div class="form-group">
                            <div class=" col-lg-10">
                                <?php if (!$this->permissions[$this->permissao_ref]['gravar']): ?>
                                    <span class="label label-warning "><span class="icon24 typ-icon-warning"></span>Você não tem permissão para gravar esta função.</span>
                                <?php else: ?>
                                    <button type="button" class="btn btn-info clickformsubmit">SALVAR</button>
                                <?php endif ?>
                            </div>
                        </div><!-- End .form-group  -->
                    </form>
                                        
                </div>
                <!-- End contentwrapper -->
            </div>
            <!-- End #content -->
            
            
<?php  require_once "layouts/footer.phtml"; ?>
        
        </div>
        
<?php  require_once "layouts/plugins.phtml"; ?>
        <!-- Init plugins only for page -->        
        <script type="text/javascript" src="plugins/forms/dualselect/jquery.dualListBox-1.3.min.js"></script>
        <script type="text/javascript">
            $(document).ready(function(){
                $.configureBoxes(); 
            });
        </script>
    </body>
</html>
