
    <script type="text/javascript">
        $(document).ready(function(){
            $(function () {
                //some data
                var d1 = [<?php foreach($this->dados_grafico->rows as $key => $dia){ echo "[$key,".$dia['visitas']."]"; if($key < (count($this->dados_grafico->rows)-1)) echo ",";} ?>];
                var ticks = [<?php foreach($this->dados_grafico->rows as $key => $dia){ echo "[$key,'".$dia['data']."']"; if($key < (count($this->dados_grafico->rows)-1)) echo ",";} ?>];
                //define placeholder class
                var placeholder = $(".<?php echo $this->alvo; ?>");
                //graph options
                var options = {
                        grid: {
                            show: true,
                            aboveData: true,
                            color: "#3f3f3f" ,
                            labelMargin: 5,
                            axisMargin: 0, 
                            borderWidth: 0,
                            borderColor:null,
                            minBorderMargin: 5 ,
                            clickable: true, 
                            hoverable: true,
                            autoHighlight: true,
                            mouseActiveRadius: 20
                        },
                        series: {
                            grow: {
                                active: false,
                                stepMode: "linear",
                                steps: 50,
                                stepDelay: true
                            },
                            lines: {
                                show: true,
                                fill: true,
                                lineWidth: 4,
                                steps: false
                                },
                            points: {
                                show:true,
                                radius: 5,
                                symbol: "circle",
                                fill: true,
                                borderColor: "#fff"
                            }
                        },
                        legend: { 
                            position: "ne", 
                            margin: [0,-25], 
                            noColumns: 0,
                            labelBoxBorderColor: null,
                            labelFormatter: function(label, series) {
                                // just add some space to labes
                                return label+'&nbsp;&nbsp;';
                             }
                        },
                        yaxis: { min: 0 },
                        xaxis: {ticks:ticks, tickDecimals: 0},
                        colors: chartColours,
                        shadowSize:1,
                        tooltip: true, //activate tooltip
                        tooltipOpts: {
                            content: "%s : %y.0",
                            shifts: {
                                x: -30,
                                y: -50
                            }
                        }
                };   

                $.plot(placeholder, [ 

                    {
                        label: "Visitas", 
                        data: d1,
                        lines: {fillColor: "#f2f7f9"},
                        points: {fillColor: "#88bbc8"}
                    }

                ], options);
            });
        });
</script>
