
                                            <div class="col-md-4">
                                            <!-- col-md-3 start here -->
                                                <a href="#" class="chartShortcuts">
                                                    <span class="head">Desktop</span>
                                                    <span class="number"><?php echo $this->desktop ?>%</span>
                                                </a>
                                            </div>
                                            
                                            <div class="col-md-4">
                                            <!-- col-md-3 start here -->
                                                <a href="#" class="chartShortcuts">
                                                    <span class="head">Tablet</span>
                                                    <span class="number"><?php echo $this->tablet ?>%</span>
                                                </a>
                                            </div>
                                            
                                            <div class="col-md-4">
                                            <!-- col-md-3 start here -->
                                                <a href="#" class="chartShortcuts">
                                                    <span class="head">Mobile</span>
                                                    <span class="number"><?php echo $this->mobile ?>%</span>
                                                </a>
                                            </div>

