
    <script type="text/javascript">
        
        $(document).ready(function(){
            $(function () {
                var data = [
                     <?php if (isset($this->paginas_visitadas->rows[0]['nome_produto'])) : ?>
                     { label: "<?php echo $this->intro($this->paginas_visitadas->rows[0]['nome_produto'], 40); ?>",  data: <?php echo $this->paginas_visitadas->rows[0]['faturamento'] ?>, color: "#80B3FF"},
                     <?php endif; ?>
                     <?php if (isset($this->paginas_visitadas->rows[1]['nome_produto'])) : ?>
                     { label: "<?php echo $this->intro($this->paginas_visitadas->rows[1]['nome_produto'], 40); ?>",  data: <?php echo $this->paginas_visitadas->rows[1]['faturamento'] ?>, color: "#7DB4B5"},
                     <?php endif; ?>
                     <?php if (isset($this->paginas_visitadas->rows[2]['nome_produto'])) : ?>
                     { label: "<?php echo $this->intro($this->paginas_visitadas->rows[2]['nome_produto'], 40); ?>",  data: <?php echo $this->paginas_visitadas->rows[2]['faturamento'] ?>, color: "#E0EFF1"},
                     <?php endif; ?>
                     <?php if (isset($this->paginas_visitadas->rows[3]['nome_produto'])) : ?>
                     { label: "<?php echo $this->intro($this->paginas_visitadas->rows[3]['nome_produto'], 40); ?>",  data: <?php echo $this->paginas_visitadas->rows[3]['faturamento'] ?>, color: "#FFC2CE"},
                     <?php endif; ?>
                     <?php if (isset($this->paginas_visitadas->rows[4]['nome_produto'])) : ?>
                     { label: "<?php echo $this->intro($this->paginas_visitadas->rows[4]['nome_produto'], 40); ?>",  data: <?php echo $this->paginas_visitadas->rows[4]['faturamento'] ?>, color: "#FD6E8A"},
                     <?php endif; ?>
                     <?php if (isset($this->paginas_visitadas->rows[5]['nome_produto'])) : ?>
                     { label: "<?php echo $this->intro($this->paginas_visitadas->rows[5]['nome_produto'], 40); ?>",  data: <?php echo $this->paginas_visitadas->rows[5]['faturamento'] ?>, color: "#FF1168"}
                     <?php endif; ?>
                 ];

                 $.plot($(".pieStats"), data, 
                 {
                     series: {
                         pie: { 
                             show: true,
                             highlight: {
                                 opacity: 0.1
                             },
                             stroke: {
                                 color: '#fff',
                                 width: 3
                             },
                             startAngle: 2,
                             label: {
                                 radius:1
                             }
                         },
                         grow: { active: false}
                     },
                     legend: { 
                         position: "ne", 
                         labelBoxBorderColor: null
                     },
                     grid: {
                         hoverable: true,
                         clickable: true
                     },
                     tooltip: true, //activate tooltip
                     tooltipOpts: {
                         content: "%s<br> R$ %y.2",
                         shifts: {
                             x: -30,
                             y: -50
                         }
                     }
                 });
             });
        });
</script>
