<?php
    require_once "layouts/headers.phtml";
?>

    <script type="text/javascript">
        var pagina = "<?php echo $this->getModule(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getModule(); ?>/save";
        var retorno = "<?php echo $this->retorno; ?>";
    </script>
    
    </head>  
    
    
    <body>
<?php  require_once "layouts/header.phtml"; ?>

        <!-- / #header -->
        <div id="wrapper">
        <!-- #wrapper -->

<?php  require_once "layouts/sidebar.phtml"; ?>
            
            <!--Body content-->
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <!--Content wrapper-->
                    <div class="heading">
                        <!--  .heading-->
                        <h3><?php echo $this->module_title; ?></h3>

                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li>
                                <a href="#" class="tip" title="Painel">
                                    <i class="s16 icomoon-icon-screen-2"></i>
                                </a>
                                <span class="divider">
                                    <i class="s16 icomoon-icon-arrow-right-3"></i>
                                </span>
                            </li>
                            <li>
                                <a class="tip" title="<?php echo $this->module_title; ?>" href="<?php echo $this->module_link;?>">
                                    <i class="s16 <?php echo $this->module_icon; ?>"></i>                                    
                                </a>
                            </li>
                            <span class="divider">
                                <i class="s16 icomoon-icon-arrow-right-3"></i>
                            </span>
                            <li class="active">Registro</li>
                        </ul>
                    </div>
                    <!-- End  / heading-->
                    <!-- Start .row -->
                  
                    <form name="main" enctype="multipart/form-data" method="post" class="form-horizontal group-border">
                        <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
                        <input type="hidden" name="retorno" value="<?php echo $this->retorno; ?>">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <!-- Start .panel -->
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Dados do Usuário</h4>
                                    </div>
                                    <div class="panel-body">
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="nome">Nome</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="nome" id="nome" type="text" value="<?php echo $this->registro['nome'] ?>" />
                                            </div><!-- End .form-group  -->
                                        </div>

                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="descricao">Descrição</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="descricao" id="descricao" type="text" value="<?php echo $this->registro['descricao'] ?>" />
                                            </div><!-- End .form-group  -->
                                        </div>

                                        <div class="form-group form-group-vertical">
                                            <label class="col-lg-2 col-md-3 control-label">Departamento:</label>
                                            <div class="col-lg-10 col-md-9">

                                                <div class="list_checkbox_type_1">
                                                <?php
                                                    $ids_departamentos_usuario = [];

                                                    if (!empty($this->departamentos_usuario->rows) && is_array($this->departamentos_usuario->rows)) {
                                                        foreach ($this->departamentos_usuario->rows as $dep_usuario) {
                                                            $ids_departamentos_usuario[] = $dep_usuario['id_departamento'];
                                                        }
                                                    }
                                                ?>

                                                <?php foreach ($this->departamentos->rows as $departamento): ?>
                                                    <?php
                                                        $checked = in_array($departamento['id'], $ids_departamentos_usuario) ? 'checked' : '';
                                                    ?>
                                                    <div>
                                                        <input <?= $checked ?> type="checkbox" name="departamentos[]" class="no_script" id="departamento_<?= $departamento['id'] ?>" value="<?= $departamento['id'] ?>">
                                                        <label for="departamento_<?= $departamento['id'] ?>"><?= $departamento['nome'] ?></label>
                                                    </div>
                                                <?php endforeach; ?>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="email">E-mail</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="email" id="email" type="text" value="<?php echo $this->registro['email'] ?>" />
                                            </div><!-- End .form-group  -->
                                        </div>
                                    
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="telefone">Telefone</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="telefone" id="telefone" type="text" value="<?php echo $this->registro['telefone'] ?>" />
                                            </div><!-- End .form-group  -->
                                        </div>

                                        <div class="form-group form-group-vertical">
                                            <label class="col-lg-2 col-md-3 control-label">Permissões:</label>
                                            <div class="col-lg-10 col-md-9">

                                                <div class="list_checkbox_type_1">
                                                    <div>
                                                        <input <?= $this->registro['permissao'] == 'gerente' ? 'checked' : '' ?> type="radio" name="permissao" class="no_script" id="gerenciamento" value="gerente">
                                                        <label for="gerenciamento">Gerente</label>
                                                    </div>
                                                    <div>
                                                        <input <?= $this->registro['permissao'] == 'atividades' ? 'checked' : '' ?> type="radio" name="permissao" class="no_script" id="atividades" value="atividades">
                                                        <label for="atividades">Atividades</label>
                                                    </div>

                                                    <div>
                                                        <input <?= $this->registro['permissao'] == 'checklists' ? 'checked' : '' ?> type="radio" name="permissao" class="no_script" id="checklists" value="checklists">
                                                        <label for="checklists">Checklists</label>
                                                    </div>

                                                    <div>
                                                        <input <?= $this->registro['permissao'] == 'remessas' ? 'checked' : '' ?> type="radio" name="permissao" class="no_script" id="remessas" value="remessas">
                                                        <label for="remessas">Remessas</label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <!-- Start .panel -->
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Dados de Login</h4>
                                    </div>
                                    <div class="panel-body">
                                    <input class="form-control" name="token" id="token" type="hidden" value="" />

                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="usuario">Usuário</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="usuario" id="usuario" type="text" value="<?php echo $this->registro['usuario'] ?>" />
                                            </div><!-- End .form-group  -->
                                        </div>
                                    
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="senha">Senha</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="senha" id="senha" type="password" value="<?= $this->senha ?>" />
                                            </div><!-- End .form-group  -->
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <?php if ($this->id==""): ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['gravar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning "><span class="icon24 typ-icon-warning"></span>Você não tem permissão para gravar esta função.</span>
                                        </div>
                                    </div><!-- End .form-group  -->   
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="button" class="btn btn-info clickformsubmit">Salvar novo</button>
                                        </div>
                                    </div><!-- End .form-group  -->
                                <?php endif ?>
                            <?php else: ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['editar'] && $_SESSION['admin_id'] != $this->id): ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning"><span class="icon24 icomoon-icon-warning "></span>Você não tem permissão para editar esta função.</span>
                                        </div>
                                    </div><!-- End .form-group  -->   
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="button" class="btn btn-info clickformsubmit">Salvar alterações</button>
                                        </div>
                                    </div><!-- End .form-group  -->
                                <?php endif ?>
                            <?php endif ?>
                        </div><!-- End .row -->  
                    </form>
                </div>
                <!-- End contentwrapper -->
            </div>
            <!-- End #content -->
            
            
<?php  require_once "layouts/footer.phtml"; ?>
        
        </div>
        
<?php  require_once "layouts/plugins.phtml"; ?>
        <!-- Init plugins only for page -->
        <script type="text/javascript">
            $(document).ready(function(){
                if ("<?php echo $this->registro['pi'];?>" != "") {
                    $(".pi").css("display","block");
                }

                $('.hora').mask('00:00');

                $("input[name=almoco]").on("change", function(){
                    $(".horario_almoco").toggle();
                });

                $("input[name=bate_ponto]").on("change", function(){
                    $(".ponto_eletronico").toggle();
                });
            });
        </script>
    </body>
</html>
