<?php
    require_once "layouts/headers.phtml";
?>

    <script type="text/javascript">
        var pagina = "<?php echo $this->getModule(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getModule(); ?>/save";
        var retorno = "<?php echo $this->retorno; ?>";
    </script>
    
    </head>  
    
    
    <body>
<?php  require_once "layouts/header.phtml"; ?>

        <!-- / #header -->
        <div id="wrapper">
        <!-- #wrapper -->

<?php  require_once "layouts/sidebar.phtml"; ?>
            
            <!--Body content-->
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <!--Content wrapper-->
                    <div class="heading">
                        <!--  .heading-->
                        <h3><?php echo $this->module_title; ?></h3>

                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li>
                                <a href="#" class="tip" title="Painel">
                                    <i class="s16 icomoon-icon-screen-2"></i>
                                </a>
                                <span class="divider">
                                    <i class="s16 icomoon-icon-arrow-right-3"></i>
                                </span>
                            </li>
                            <li>
                                <a class="tip" title="<?php echo $this->module_title; ?>" href="<?php echo $this->module_link;?>">
                                    <i class="s16 <?php echo $this->module_icon; ?>"></i>                                    
                                </a>
                            </li>
                            <span class="divider">
                                <i class="s16 icomoon-icon-arrow-right-3"></i>
                            </span>
                            <li class="active">Registro</li>
                        </ul>
                    </div>
                    <!-- End  / heading-->
                    <!-- Start .row -->
                  
                    <form name="main" enctype="multipart/form-data" method="post" class="form-horizontal group-border">
                        <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
                        <input type="hidden" name="retorno" value="<?php echo $this->retorno; ?>">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <!-- Start .panel -->
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Dados do Link</h4>
                                    </div>
                                    
                                    <div class="panel-body">
                                        
                                        <div class="form-group form-group-vertical">
                                            <label class="col-lg-2 col-md-3 control-label" for="id_pai">Menu Link:</label>
                                            <div class="col-lg-10 col-md-9">
                                                <select class="form-control input-sm" id="id_pai" name="id_pai">
                                                    <option value="">Selecione..</option>
                                                    <?php if ($this->links->num_rows) : ?>
                                                        <?php foreach ($this->links->rows as $link) : ?>
                                                            <option <?php if ($this->id == $link['id_pai']) echo 'selected'; ?> value="<?php echo $link['id']; ?>"><?php echo $this->getCategoriaNome($link['id_pai']);?> <?php echo $link['nome']; ?></option>
                                                        <?php endforeach; ?>
                                                    <?php endif; ?>
                                                </select>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="nome">Título:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="nome" id="nome" type="text" value="<?php echo $this->registro['nome'] ?>" />
                                            </div><!-- End .form-group  -->
                                        </div>
                                        
                                        <div class="form-group form-group-vertical">
                                            <label class="col-lg-2 col-md-3 control-label" for="url_pagina">Páginas:</label>
                                            <div class="col-lg-10 col-md-9">
                                                <select class="form-control input-sm url_pagina" id="url_pagina" name="url_pagina">
                                                    <option value="">Selecione..</option>
                                                    <?php if ($this->urls->num_rows) : ?>
                                                        <?php foreach ($this->urls->rows as $url) : ?>
                                                            <option value="<?php echo $this->trataParameter($url['link']); ?>"><?php echo $url['nome']; ?></option>
                                                        <?php endforeach; ?>
                                                    <?php endif; ?>
                                                </select>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="menu_aberto">Menu Aberto:</label>
                                            <div class="col-lg-10">
                                                <label class="pointer" for="menu_aberto1">Sim</label><input <?php if ($this->registro['menu_aberto'] == 1) { echo 'checked'; } ?> class="form-control" name="menu_aberto" id="menu_aberto1" type="radio" value="1" /> 
                                                <label class="pointer" for="menu_aberto2">Não</label><input <?php if ($this->registro['menu_aberto'] == 0) { echo 'checked'; } ?> class="form-control" name="menu_aberto" id="menu_aberto2" type="radio" value="0" />
                                            </div>
                                        </div><!-- End .form-group  -->
                                        
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="fileupload">Imagem:</label>
                                            <div class="col-lg-10">
                                                <label class="fileupload" for="fileupload">
                                                    <?php if ($this->registro['imagem'] == ""): ?>
                                                        <img src="http://placehold.it/300x165" alt="" class="image marginR10"/>
                                                    <?php else: ?>
                                                        <img src="<?php echo $this->getImageFileSized($this->registro['imagem'],300,165); ?>" alt="" class="image marginR10"/>
                                                    <?php endif ?>
                                                </label>
                                                <input type="file" name="fileupload" id="fileupload" class="files btn btn-default"/>
                                                <span class="help-block blue">imagem será apresentada na seguinte proporção 300x165 pixels.</span>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="link">Link:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="link" id="link" type="text" value="<?php echo $this->registro['link'] ?>" />                                  
                                            </div>
                                        </div><!-- End .form-group  -->
                                        
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label noStyle" for="target">Target:</label>
                                            <div class="col-lg-10">
                                                <select name="target" id="target" class="form-control">
                                                    <option value="_self"<?php if($this->registro['target']=="_self") echo " selected='selected'" ?>>Mesma Janela</option>
                                                    <option value="_blank"<?php if($this->registro['target']=="_blank") echo " selected='selected'" ?>>Nova Janela</option>                                                    
                                                </select>
                                            </div>
                                        </div><!-- End .form-group  -->
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <?php if ($this->id==""): ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['gravar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning "><span class="icon24 typ-icon-warning"></span>Você não tem permissão para gravar esta função.</span>
                                        </div>
                                    </div><!-- End .form-group  -->   
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="button" class="btn btn-info clickformsubmit">Salvar novo</button>
                                        </div>
                                    </div><!-- End .form-group  -->
                                <?php endif ?>
                            <?php else: ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['editar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning"><span class="icon24 icomoon-icon-warning "></span>Você não tem permissão para editar esta função.</span>
                                        </div>
                                    </div><!-- End .form-group  -->   
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="button" class="btn btn-info clickformsubmit">Salvar alterações</button>
                                        </div>
                                    </div><!-- End .form-group  -->
                                <?php endif ?>
                            <?php endif ?>
                        </div><!-- End .row -->  
                    </form>
                </div>
                <!-- End contentwrapper -->
            </div>
            <!-- End #content -->
            
            
<?php  require_once "layouts/footer.phtml"; ?>
        
        </div>
        
<?php  require_once "layouts/plugins.phtml"; ?>
        <!-- Init plugins only for page -->
        <script type="text/javascript">
            
            
            /*
            * ORDENA COMBOBOX CATEGORIAS
            * @param {type} combo
            * @returns {COMBO ORDENADA}
            */

          
           function ordenarLista(combo) {
               var lb = document.getElementById(combo);
               arr = new Array();                       

               for(i=0; i<lb.length; i++) {              
                   arr.push({text:lb.options[i].text, value:lb.options[i].value}) 
               }

               arr.sort(function(a, b){
                   var a1= a.text, b1= b.text;
                   if(a1== b1) return 0;
                   return a1> b1? 1: -1;
               });

               for(i=0; i<lb.length; i++) {
                   lb.options[i].text = arr[i]['text'];
                   lb.options[i].value = arr[i]['value'];
               }
               
               <?php if ($this->registro['id_pai'] != "") : ?>
                    $('#id_pai option[value=<?php echo $this->registro['id_pai'];?>]').attr('selected','selected');
                <?php else :?>
                    $('#id_pai option[value=""]').attr('selected','selected');
                <?php endif; ?>
               
           }
           ordenarLista('id_pai');
           
            $(document).ready(function(){
                $(".url_pagina").on("change", function(){
                    var link = $(this).val();
                    $("#link").val(link);
                    uniform();
                });
                
            });
        </script>
    </body>
</html>
