<?php
    require_once "layouts/headers.phtml";
?>

    <link href="plugins/tables/dataTables/jquery.dataTables.css" type="text/css" rel="stylesheet" />
    <link href="plugins/tables/dataTables/TableTools.css" type="text/css" rel="stylesheet" />
    
    <script type="text/javascript">
        var pagina = "<?php echo $this->getModule(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getModule(); ?>";
    </script>
    
    </head>  
    
    
    <body>
<?php  require_once "layouts/header.phtml"; ?>

        <!-- / #header -->
        <div id="wrapper">
        <!-- #wrapper -->

<?php  require_once "layouts/sidebar.phtml"; ?>
            
            <!--Body content-->
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <!--Content wrapper-->
                    <div class="heading">
                        <!--  .heading-->
                        <h3><?php echo $this->module_title; ?></h3>

                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li>
                                <a href="#" class="tip" title="Painel">
                                    <i class="s16 icomoon-icon-screen-2"></i>
                                </a>
                                <span class="divider">
                                    <i class="s16 icomoon-icon-arrow-right-3"></i>
                                </span>
                            </li>
                            <li class="active"><?php echo $this->module_title;?></li>
                        </ul>
                    </div>
                    <!-- End  / heading-->
                    <!-- Start .row -->
                    <div class="row">
                        <div class="col-lg-12">
                            <a href="<?php echo $this->getModule();?>/edit"><button type="button" class="btn btn-default mr5 mb10"><i class="glyphicon glyphicon-plus mr5"></i> Novo registro</button></a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="panel panel-default toggle panelClose">
                                <!-- Start .panel -->
                                <div class="panel-heading">
                                    <h4 class="panel-title">Importar/Exportar</h4>
                                </div>
                                <div class="panel-body">
                                    <div class="form-group">
                                        <form name="main-import-email" enctype="multipart/form-data" method="post" class="form-horizontal group-border" style="display:inline-block; vertical-align: top;">                                                                                
                                            <input type="hidden" name="a" value="csv" />                                    
                                            <input type="hidden" id="data-redirect" value="<?php echo $this->getModule(); ?>">
                                            <div class="panel-body box-header-forms" style="border-style: none">
                                                <input type="file" name="csv" class="files btn btn-default ">
                                                <button type="button" class="btn btn-primary clickformsubmit">Importar e-mails *.csv</button>
                                            </div>
                                        </form>
                                    
                                        <div style="display:inline-block;">
                                            <div class="panel-body box-header-forms" style="border-style: none">
                                                <a style="margin-top: 5px" href="<?php echo $this->system_path.$this->getModule();?>/exportEmails" class="btn btn-info"><span class="icon16 icomoon-icon-file-excel color-white"></span> Exportar *.csv</a>                                  
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="panel panel-default toggle panelClose">
                                <!-- Start .panel -->
                                <div class="panel-heading">
                                    <h4 class="panel-title"><i class="<?php echo $this->module_icon ?>"></i> Tabela de E-mails
                                        <label class="select-all">Selecionar estes <input type="checkbox" id="apagar_todos"></label>
                                    </h4>
                                </div>
                                <div class="panel-body">
                                    <table cellpadding="0" cellspacing="0" border="0" class="tabletools table table-striped table-bordered" width="100%">
                                        <thead>
                                            <tr>
                                                <th class="tal" width="20%">Nome</th>
                                                <th class="tal" width="20%">E-mail</th>
                                                <th class="tal" width="20%">Data de Nascimento</th>
                                                <th class="tal" width="30%">Lista</th>
                                                <th style="min-width: 120px">Ação</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div><!-- End .row -->
                    <?php require_once "layouts/options.phtml"; ?>
                </div>
                <!-- End contentwrapper -->
            </div>
            <!-- End #content -->
            
            
<?php  require_once "layouts/footer.phtml"; ?>
        
        </div>
        
<?php  require_once "layouts/plugins.phtml"; ?>

        <!-- Table plugins -->
        <script src="plugins/tables/dataTables/jquery.dataTables.js"></script>
        <script src="plugins/tables/dataTables/dataTables.tableTools.js"></script>
        <script src="plugins/tables/dataTables/dataTables.bootstrap.js"></script>
        <script src="plugins/tables/dataTables/dataTables.responsive.js"></script>


        <!-- Init plugins only for page -->
        <script type="text/javascript">
            $(document).ready(function(){
                
                if ($("form[name=main-import-email]").length > 0) {

                    $("form[name=main-import-email]").clickform({"validateUrl": "<?php echo $this->system_path;?>/emaillist/importEmail"}, function (data) {
                        redirect = $("#data-redirect").val();                
                        if (data.type == "success") {
                            if (data.retorno) {
                                redirect = data.retorno;
                            }

                            window.location.href = redirect;
                        }

                    });
                }

                var oTable = $('.tabletools').dataTable( {
                   
                    "bProcessing": true,
                    "bServerSide": true,
                    "sAjaxSource": "<?php echo $this->system_path.$this->getModule();?>/datatableEmails",
                    
                    "fnServerData": function ( sSource, aoData, fnCallback, oSettings ) {
                        oSettings.jqXHR = $.ajax( {
                            "dataType": 'json',
                            "type": "POST",
                            "url": sSource,
                            "data": aoData,
                            "success": fnCallback
                        });
                    },
                    "sDom": "<'row'<'col-lg-6'l><'col-lg-6'f>r>t<'row'<'col-lg-6'i><'col-lg-6'p>>",
                    "aaSorting":[[0,"desc"]],
                    "sPaginationType": "bootstrap",
                    "bJQueryUI": false,
                    "bAutoWidth": false,
                    "iDisplayLength": 100,
                    "oLanguage": {
                        "sProcessing":   "<img src='<?php echo $this->system_path; ?>images/loaders/horizontal/006.gif'><br>Processando...",
                        "sLengthMenu":   "_MENU_",
                        "sZeroRecords":  "Não foram encontrados resultados",
                        "sInfo":         "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                        "sInfoEmpty":    "Mostrando de 0 até 0 de 0 registros",
                        "sInfoFiltered": "(filtrado de _MAX_ registros no total)",
                        "sInfoPostFix":  "",
                        "sSearch":       "",
                        "sUrl":          "",
                        "oPaginate": {
                            "sFirst":    "Primeiro",
                            "sPrevious": "Anterior",
                            "sNext":     "Seguinte",
                            "sLast":     "Último"
                        }
                    }                
                });

                /*
                 * HABILITA BUSCA APENAS APÓS TECLAR ENTER
                 */            
                $(".dataTables_filter input").attr('title', "Tecle ENTER Para Pesquisar");
                $(".dataTables_filter input").unbind();
               
                $(".dataTables_filter input").keyup( function (e) {
                    if (e.keyCode == 13) {
                        oTable.fnFilter( this.value);
                    }
                });
                
                setInterval(function(){
                    uniform();                    
                }, 5);
                
                
                
                
                $(".bt_lista_email").click(function (e) {
                    e.preventDefault();
                    if (confirm("Deseja realmente relacionar todos registros selecionados?")) {
                        var registros = $(".del-registros").val().split(','); //valor vindo da input del-registros, array do lista_del
                        var ids = []; //aqui será guardado as ids dos registros que não foram possíveis de serem apagados
                        var mensagem = null; //mensagem, caso exita, será apresentado como alert

                        //caso exista um controller alternativo especificado, ele substituirá o controller padrão da página
                        var controle = $(".data-controller").val();

                        var lista = $("#lista").find("option:selected").val();

                        if (controle)
                            controller = controle;

                        //laço com método post ajax que enviará ao controller os registros (ids) que deverão ser alterados

                            jQuery.ajax({
                                url: "<?php echo $this->system_path.$this->getModule() ?>/relateList",
                                type: 'POST',
                                data: {i: registros, lista: lista},
                                async: true,
                                jsonp: false,
                                success: function (dt) {
                                    if (dt) {
                                        alert(dt);
                                    } else {
                                        window.location.reload();
                                    }
                                },
                                complete: function () {                                
                                }
                            });



                        return true;
                    } else {
                        //caso o usuário desista de apagar os registros selecionados
                        return false;
                    }
                });
            

            });
        </script>
    </body>
</html>
