<?php
    require_once "layouts/headers.phtml";
?>
    <script type="text/javascript">
        var pagina = "<?php echo $this->getModule(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getModule(); ?>";
    </script>
</head>

<body>
    <?php require_once "layouts/header.phtml"; ?>

    <!-- / #header -->
    <div id="wrapper">
    <!-- #wrapper -->

        <?php  require_once "layouts/sidebar.phtml"; ?>

        <!--Body content-->
        <div id="content" class="page-content clearfix">
            <!--Content wrapper-->
            <div class="contentwrapper">
                <!-- .heading -->
                <div class="heading">
                    <h3><?php echo $this->module_title; ?></h3>
                    <ul class="breadcrumb">
                        <li>Você está aqui:</li>
                        <li>
                            <a href="#" class="tip" title="Painel">
                                <i class="s16 icomoon-icon-screen-2"></i>
                            </a>
                            <span class="divider">
                                <i class="s16 icomoon-icon-arrow-right-3"></i>
                            </span>
                        </li>
                        <li class="active"><?php echo $this->module_title;?></li>
                    </ul>
                </div>
                <!-- End .heading-->
                <!-- Start .row -->
                <div class="row">
                    <div class="col-lg-12">
                        <!-- Start .panel -->
                        <div class="panel panel-default toggle panelClose">
                            <div class="panel-heading">
                                <h4 class="panel-title"><i class="<?php echo $this->module_icon ?>"></i> Tabela de pedidos
                                    <label class="select-all">Selecionar estes <input type="checkbox" id="apagar_todos"></label>
                                </h4>
                            </div>
                            <!-- Start .panel-body -->
                            <div class="panel-body">
                                <style>
                                    .tal a{
                                        color: #333333;
                                    }
                                </style>
                                <table width="100%" cellpadding="0" cellspacing="0" border="0" class="tabletools table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th class="tal" style="display:none;"></th>
                                            <th width="100px" class="tal">Remessa</th>
                                            <th width="150px" class="tal">Pedidos</th>
                                            <th class="tal">Departamentos</th>
                                            <th class="tal">Cliente</th>
                                            <th class="tal">Produção</th>
                                            <th class="tal">Saída</th>
                                            <th class="tal">Entrega</th>
                                            <th class="tal">Destino</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach($this->list->rows as $item): ?>
                                            <?php if($item['category'] == "atrasado")
                                                    $bg = "style='background: #f78e8e;'";
                                                elseif($item['category'] == "urgente")
                                                    $bg = "style='background: #fdff9e;'";
                                                else 
                                                    $bg = "";
                                            ?>

                                            <?php foreach($item['items'] as $itemList): ?>
                                                <tr <?= $bg ?>>
                                                    <td class="tal" style="display: none;"></td>
                                                    <td class="tal"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $itemList['id']; ?>"><?= $itemList['titulo'] ?></a></td>
                                                    <td class="tal"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $itemList['id']; ?>"><?= $itemList['pedidos_concat'] ?></a></td>
                                                    <td class="tal"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $itemList['id']; ?>"><?= $itemList['departamentos'] ?></a></td>
                                                    <td class="tal"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $itemList['id']; ?>"><?= $itemList['nome'] ?></a></td>
                                                    <td class="tal"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $itemList['id']; ?>"><?= $itemList['created_at_formatted'] ?></a></td>
                                                    <?php if($itemList['nova_saida_formatted']): ?>
                                                        <td class="tal"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $itemList['id']; ?>"><?= $itemList['nova_saida_formatted'] ?><i title="<?= $itemList['saida_formatted']?>" class="brocco-icon-warning"></i></a></td>
                                                    <?php else: ?>
                                                        <td class="tal"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $itemList['id']; ?>"><?= $itemList['saida_formatted'] ?></a></td>
                                                    <?php endif; ?>
                                                    <?php if($itemList['nova_entrega_formatted']): ?>
                                                        <td class="tal"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $itemList['id']; ?>"><?= $itemList['nova_entrega_formatted'] ?><i title="<?= $itemList['entrega_formatted']?>" class="brocco-icon-warning"></i></a></td>
                                                    <?php else: ?>
                                                        <td class="tal"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $itemList['id']; ?>"><?= $itemList['entrega_formatted'] ?></a></td>
                                                    <?php endif; ?>
                                                    <td class="tal"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $itemList['id']; ?>"><?= $itemList['cidade'] ?> / <?= $itemList['uf'] ?></a></td>
                                                </tr>
                                            <?php endforeach; ?>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                            <!-- End .panel-body -->
                        </div>
                        <!-- End .panel -->
                    </div>
                </div>
                <!-- End .row -->
                <?php require_once "layouts/options.phtml"; ?>
            </div>
            <!-- End contentwrapper -->
        </div>
        <!-- End #content -->

        <?php  require_once "layouts/footer.phtml"; ?>
    
    </div>

    <?php  require_once "layouts/plugins.phtml"; ?>

    <!-- Table plugins -->
    <script src="plugins/tables/dataTables/jquery.dataTables.js"></script>
    <script src="plugins/tables/dataTables/dataTables.tableTools.js"></script>
    <script src="plugins/tables/dataTables/dataTables.bootstrap.js"></script>
    <script src="plugins/tables/dataTables/dataTables.responsive.js"></script>


    <!-- Init plugins only for page -->
    <script type="text/javascript">
        $(document).ready(function(){

            //--------------- Data tables ------------------//
            if($('table').hasClass('tabletools')){
                $('.tabletools').dataTable( {
                    "oLanguage": {
                        "sSearch": "",
                        "sLengthMenu": "<span>_MENU_</span>",
                        "sProcessing":   "Processando...",                    
                        "sZeroRecords":  "Não foram encontrados resultados",
                        "sInfo":         "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                        "sInfoEmpty":    "Mostrando de 0 até 0 de 0 registros",
                        "sInfoFiltered": "(filtrado de _MAX_ registros no total)",
                        "sInfoPostFix":  "",
                        "sUrl":         "",

                        "oPaginate": {
                            "sFirst":    "Primeiro",
                            "sPrevious": "Anterior",
                            "sNext":     "Seguinte",
                            "sLast":     "Último"
                        }
                    },
                    "sDom": "T<'row'<'col-md-6 col-xs-12 'l><'col-md-6 col-xs-12'f>r>t<'row'<'col-md-4 col-xs-12'i><'col-md-8 col-xs-12'p>>",
                    "aaSorting":[[0,"asc"]], "iDisplayLength": 100,
                    tableTools: {
                        "sSwfPath": "http://cdn.datatables.net/tabletools/2.2.2/swf/copy_csv_xls_pdf.swf",
                        "aButtons": [
                        ]
                    }
                });
            }
        });
    </script>
</body>
</html>
