<?php
    require_once "layouts/headers.phtml";
?>

    <script type="text/javascript">
        var pagina = "<?php echo $this->getModule(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getModule(); ?>/save";
        var retorno = "<?php echo $this->retorno; ?>";
    </script>
    
    </head>  
    
    
    <body>
<?php  require_once "layouts/header.phtml"; ?>

        <!-- / #header -->
        <div id="wrapper">
        <!-- #wrapper -->

<?php  require_once "layouts/sidebar.phtml"; ?>
            
            <!--Body content-->
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <!--Content wrapper-->
                    <div class="heading">
                        <!--  .heading-->
                        <h3><?php echo $this->module_title; ?></h3>

                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li>
                                <a href="#" class="tip" title="Painel">
                                    <i class="s16 icomoon-icon-screen-2"></i>
                                </a>
                                <span class="divider">
                                    <i class="s16 icomoon-icon-arrow-right-3"></i>
                                </span>
                            </li>
                            <li>
                                <a class="tip" title="<?php echo $this->module_title; ?>" href="<?php echo $this->module_link;?>">
                                    <i class="s16 <?php echo $this->module_icon; ?>"></i>                                    
                                </a>
                            </li>
                            <span class="divider">
                                <i class="s16 icomoon-icon-arrow-right-3"></i>
                            </span>
                            <li class="active">Registro</li>
                        </ul>
                    </div>
                    <!-- End  / heading-->
                    <!-- Start .row -->
                  
                    <form name="main" enctype="multipart/form-data" method="post" class="form-horizontal group-border">
                        <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
                        <input type="hidden" name="retorno" value="<?php echo $this->retorno; ?>">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <!-- Start .panel -->
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Dados do Banner</h4>
                                    </div>
                                    <div class="panel-body">
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="nome">Título:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="nome" id="nome" type="text" value="<?php echo $this->registro['nome'] ?>" />
                                            </div><!-- End .form-group  -->
                                        </div>
                                    
                                        
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="subtitulo">Subtitulo:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="subtitulo" id="subtitulo" type="text" value="<?php echo $this->registro['subtitulo'] ?>" />
                                            </div><!-- End .form-group  -->
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="titulo_preco">Título do Preço:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="titulo_preco" id="titulo_preco" type="text" value="<?php echo $this->registro['titulo_preco'] ?>" />
                                            </div><!-- End .form-group  -->
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="preco">Preço:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="preco" id="preco" type="text" value="<?php echo $this->registro['preco'] ?>" />
                                            </div><!-- End .form-group  -->
                                        </div>
                                    
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="fileupload">Imagem:</label>
                                            <div class="col-lg-10">
                                                <label class="fileupload" for="fileupload">
                                                    <?php if ($this->registro['imagem'] == ""): ?>
                                                        <img src="http://placehold.it/2000x400" alt="" class="image marginR10"/>
                                                    <?php else: ?>
                                                        <img src="<?php echo $this->getImageFileSized($this->registro['imagem'],930,405); ?>" alt="" class="image marginR10"/>
                                                    <?php endif ?>
                                                </label>
                                                <input type="file" name="fileupload" id="fileupload" class="files btn btn-default"/>
                                                <span class="help-block blue">imagem será apresentada com uma altura de 400 pixels e a largura recomendada é de 2000 pixels.</span>
                                            </div>
                                        </div>
                                        
                                        
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="link">Link:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="link" id="link" type="text" value="<?php echo $this->registro['link'] ?>" />
                                            </div>
                                        </div><!-- End .form-group  -->
                                        
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label noStyle" for="target">Target:</label>
                                            <div class="col-lg-10">
                                                <select name="target" id="target" class="form-control">
                                                    <option value="_blank"<?php if($this->registro['target']=="_blank") echo " selected='selected'" ?>>Nova Janela</option>
                                                    <option value="_self"<?php if($this->registro['target']=="_self") echo " selected='selected'" ?>>Mesma Janela</option>
                                                </select>
                                            </div>
                                        </div><!-- End .form-group  -->
                                        
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="texto_link">Texto do Link:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="texto_link" id="texto_link" type="text" value="<?php echo $this->registro['texto_link'] ?>" />
                                            </div><!-- End .form-group  -->
                                        </div>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <?php if ($this->id==""): ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['gravar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning "><span class="icon24 typ-icon-warning"></span>Você não tem permissão para gravar esta função.</span>
                                        </div>
                                    </div><!-- End .form-group  -->   
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="button" class="btn btn-info clickformsubmit">Salvar novo</button>
                                        </div>
                                    </div><!-- End .form-group  -->
                                <?php endif ?>
                            <?php else: ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['editar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning"><span class="icon24 icomoon-icon-warning "></span>Você não tem permissão para editar esta função.</span>
                                        </div>
                                    </div><!-- End .form-group  -->   
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="button" class="btn btn-info clickformsubmit">Salvar alterações</button>
                                        </div>
                                    </div><!-- End .form-group  -->
                                <?php endif ?>
                            <?php endif ?>
                        </div><!-- End .row -->  
                    </form>
                </div>
                <!-- End contentwrapper -->
            </div>
            <!-- End #content -->
            
            
<?php  require_once "layouts/footer.phtml"; ?>
        
        </div>
        
<?php  require_once "layouts/plugins.phtml"; ?>
        <!-- Init plugins only for page -->
        <script type="text/javascript">
            $(document).ready(function(){
                
            });
        </script>
    </body>
</html>
