<?php
    require_once "layouts/headers.phtml";
?>

    <script type="text/javascript">
        var pagina = "<?php echo $this->getModule(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getModule(); ?>/save";
        var retorno = "<?php echo $this->retorno; ?>";
    </script>
    
    </head>  
    
    
    <body>
<?php  require_once "layouts/header.phtml"; ?>

        <!-- / #header -->
        <div id="wrapper">
        <!-- #wrapper -->

<?php  require_once "layouts/sidebar.phtml"; ?>
            
            <!--Body content-->
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <!--Content wrapper-->
                    <div class="heading">
                        <!--  .heading-->
                        <h3><?php echo $this->module_title; ?></h3>

                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li>
                                <a href="#" class="tip" title="Painel">
                                    <i class="s16 icomoon-s-screen-2"></i>
                                </a>
                                <span class="divider">
                                    <i class="s16 icomoon-s-arrow-right-3"></i>
                                </span>
                            </li>
                            <li>
                                <a class="tip" title="<?php echo $this->module_title; ?>" href="<?php echo $this->module_link;?>">
                                    <i class="s16 <?php echo $this->module_icon; ?>"></i>                                    
                                </a>
                            </li>
                            <span class="divider">
                                <i class="s16 icomoon-s-arrow-right-3"></i>
                            </span>
                            <li class="active">Registro</li>
                        </ul>
                    </div>
                    <!-- End  / heading-->
                    <!-- Start .row -->
                  
                    <form name="main" enctype="multipart/form-data" method="post" class="form-horizontal group-border">
                        <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
                        <input type="hidden" name="retorno" value="<?php echo $this->retorno; ?>">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <!-- Start .panel -->
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Dados do Cliente</h4>
                                    </div>
                                    <div class="panel-body">
                                         <div class="form-group">
                                            <label class="col-lg-3 control-label" for="identificador">Referência:</label>
                                            <div class="col-lg-9" style="margin-top: 7px">
                                                <label for="falta" class="pointer">Falta</label>
                                                <input <?php if ($this->registro['identificador'] == 'falta' OR $this->id == '') echo 'checked'; ?> class="form-control" name="identificador" id="falta" type="radio" value="falta" />
                                                <label for="justificada_nao" class="pointer">Folga</label>
                                                <input <?php if ($this->registro['identificador'] == 'folga') echo 'checked'; ?> class="form-control" name="identificador" id="folga" type="radio" value="folga" />
                                                <label for="venda" class="pointer">Venda</label>
                                                <input <?php if ($this->registro['identificador'] == 'venda') echo 'checked'; ?> class="form-control" name="identificador" id="venda" type="radio" value="venda" />
                                            </div>

                                        </div><!-- End .form-group  -->
                                        
                                        <div class="form-group">
                                            <label class="col-lg-3 control-label" for="id_user">Usuário:</label>
                                            <div class="col-lg-9">
                                                <select id="id_user" name="id_user"  class="form-control">
                                                    <option value="">Selecione</option>
                                                    <?php if($this->users->num_rows) :?>
                                                    <?php foreach ($this->users->rows as $usuario) : ?>
                                                        <option <?php if ($this->registro['id_user'] == $usuario['id']) echo 'selected'; ?> value="<?php echo $usuario['id']; ?>"><?php echo $usuario['nome']; ?></option>                                                        
                                                    <?php endforeach; ?>
                                                    <?php endif; ?>                                                                   
                                                </select>
                                            </div>
                                        </div><!-- End .row -->

                                        <div id="target_falta" class="target" <?php if ($this->registro['identificador'] != 'falta' AND $this->id != '') :?> style="display: none" <?php endif; ?>>
                                        <div class="form-group">
                                            <label class="col-lg-3 control-label">Data da Falta</label>
                                            <div class="col-lg-9">
                                                <input type="text" name="data" class="form-control date" value="<?php echo $this->registro['data'] ?>"/>
                                            </div>
                                        </div><!-- End .form-group  -->

                                        <div class="form-group">
                                            <label class="col-lg-3 control-label" for="justificada">Justificada:</label>
                                            <div class="col-lg-9" style="margin-top: 7px">
                                                <label for="justificada_sim" class="pointer">Sim</label>
                                                <input <?php if ($this->registro['justificada']) echo 'checked'; ?> class="form-control" name="justificada" id="justificada_sim" type="radio" value="1" />
                                                <label for="justificada_nao" class="pointer">Não</label>
                                                <input <?php if (!$this->registro['justificada']) echo 'checked'; ?> class="form-control" name="justificada" id="justificada_nao" type="radio" value="0" />
                                                <p class="text-muted"><small>* com esta opção afirmativa, o funcionário não terá suas horas negativadas pela falta</small></p>
                                            </div>

                                        </div><!-- End .form-group  -->

                                        <div class="form-group">
                                            <label class="col-lg-3 control-label">Motivo</label>
                                            <div class="col-lg-9">
                                                <textarea name="motivo" class="form-control elastic"><?php echo $this->registro['motivo'] ?></textarea>
                                            </div>
                                        </div><!-- End .form-group  -->
                                        </div>

                                        <div id="target_folga" class="target" <?php if ($this->registro['identificador'] != 'folga'): ?> style="display: none" <?php endif; ?>>
                                        <div class="form-group">
                                            <label class="col-lg-3 control-label">Período</label>
                                            <div class="col-lg-1">
                                                <input type="text" name="data_inicio" class="form-control date" value="<?php echo $this->registro['data_inicio'] ?>"/>
                                            </div>
                                            <div class="col-lg-1 text-center">_</div>
                                            <div class="col-lg-1">
                                                <input type="text" name="data_fim" class="form-control date" value="<?php echo $this->registro['data_fim'] ?>"/>
                                            </div>
                                        </div><!-- End .form-group  -->
        
                                        <div class="form-group">
                                            <label class="col-lg-3 control-label">Motivo</label>
                                            <div class="col-lg-9">
                                                <textarea name="motivo" class="form-control elastic"><?php echo $this->registro['motivo'] ?></textarea>
                                            </div>
                                        </div><!-- End .form-group  -->
                                        </div>

                                        <div id="target_venda" class="target" <?php if ($this->registro['identificador'] != 'venda'): ?> style="display: none" <?php endif; ?>>
                                        <div class="form-group">
                                            <label class="col-lg-3 control-label">Quantidade(em minutos):</label>
                                            <div class="col-lg-9">
                                                <input type="text" name="minutos" class="form-control" id="minutos" value="<?php echo $this->registro['minutos'] ?>"/>
                                            </div>
                                        </div><!-- End .form-group  -->

                                        <div class="form-group">
                                            <label class="col-lg-3 control-label">Valor(R$):</label>
                                            <div class="col-lg-9">
                                                <input type="text" name="valor" id="valor" class="form-control" value="<?php echo $this->registro['valor'] ?>"/>
                                            </div>
                                        </div><!-- End .form-group  -->
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <?php if ($this->id==""): ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['gravar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning "><span class="s24 typ-s-warning"></span>Você não tem permissão para gravar esta função.</span>
                                        </div>
                                    </div><!-- End .form-group  -->   
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="button" class="btn btn-info clickformsubmit">Salvar novo</button>
                                        </div>
                                    </div><!-- End .form-group  -->
                                <?php endif ?>
                            <?php else: ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['editar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning"><span class="s24 icomoon-s-warning "></span>Você não tem permissão para editar esta função.</span>
                                        </div>
                                    </div><!-- End .form-group  -->   
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="button" class="btn btn-info clickformsubmit">Salvar alterações</button>
                                        </div>
                                    </div><!-- End .form-group  -->
                                <?php endif ?>
                            <?php endif ?>
                        </div><!-- End .row -->  
                    </form>
                </div>
                <!-- End contentwrapper -->
            </div>
            <!-- End #content -->
            
            
<?php  require_once "layouts/footer.phtml"; ?>
        
        </div>
        
<?php  require_once "layouts/plugins.phtml"; ?>
        <!-- Init plugins only for page -->
        <script type="text/javascript">
            $(document).ready(function(){
                $("#valor").mask('000.000.000.000.000,00', {reverse: true});
            
                $(".date").datepicker({
                    dateFormat: 'dd/mm/yy',
                    dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'],
                    dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
                    dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
                    monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
                    monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
                    nextText: 'Próximo',
                    prevText: 'Anterior'
                }).mask('00/00/0000');

                $("input[name=identificador]").on("change", function(){
                    $(".target").hide();
                    $("#target_"+this.value).show();
                });

                $("textarea[name=motivo]").on("keyup", function(){
                    $("textarea[name=motivo]").val(this.value);
                });
                
            });
        </script>
    </body>
</html>
