<?php
    require_once "layouts/headers.phtml";
?>

    <script type="text/javascript">
        var pagina = "<?php echo $this->getModule(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getModule(); ?>/save";
        var retorno = "<?php echo $this->retorno; ?>";
    </script>
    
    </head>  
    
    
    <body>
<?php  require_once "layouts/header.phtml"; ?>

        <!-- / #header -->
        <div id="wrapper">
        <!-- #wrapper -->

<?php  require_once "layouts/sidebar.phtml"; ?>
            
            <!--Body content-->
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <!--Content wrapper-->
                    <div class="heading">
                        <!--  .heading-->
                        <h3><?php echo $this->module_title; ?></h3>

                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li>
                                <a href="#" class="tip" title="Painel">
                                    <i class="s16 icomoon-s-screen-2"></i>
                                </a>
                                <span class="divider">
                                    <i class="s16 icomoon-s-arrow-right-3"></i>
                                </span>
                            </li>
                            <li>
                                <a class="tip" title="<?php echo $this->module_title; ?>" href="<?php echo $this->module_link;?>">
                                    <i class="s16 <?php echo $this->module_icon; ?>"></i>                                    
                                </a>
                            </li>
                            <span class="divider">
                                <i class="s16 icomoon-s-arrow-right-3"></i>
                            </span>
                            <li class="active">Registro</li>
                        </ul>
                    </div>
                    <!-- End  / heading-->
                    <!-- Start .row -->
                  
                    <form name="main" enctype="multipart/form-data" method="post" class="form-horizontal group-border">
                        <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
                        <input type="hidden" name="retorno" value="<?php echo $this->retorno; ?>">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <!-- Start .panel -->
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Dados da Cidade</h4>
                                    </div>
                                    <div class="panel-body">
                                        
                                        <div class="form-group form-group-vertical">
                                            <label class="col-lg-2 col-md-3 control-label" for="id_estado">Estado:</label>
                                            <div class="col-lg-10 col-md-9">
                                                <select class="form-control input-sm" id="id_estado" name="id_estado">
                                                    <option value="">Selecione..</option>
                                                    <?php if ($this->estados->num_rows) : ?>
                                                        <?php foreach ($this->estados->rows as $estado) : ?>
                                                            <option <?php if ($estado['id'] == $this->registro['id_estado']) echo "selected"; ?> value="<?php echo $estado['id']; ?>"><?php echo $estado['nome']; ?></option>
                                                        <?php endforeach; ?>
                                                    <?php endif; ?>
                                                </select>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="nome">Nome:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="nome" id="nome" type="text" value="<?php echo $this->registro['nome'] ?>" />
                                            </div>
                                        </div><!-- End .form-group  -->
                                        
                                        
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="capital">Capital:</label>
                                            <div class="col-lg-10">
                                                <label class="pointer" for="capital1">Sim</label><input <?php if ($this->registro['capital'] == 1) { echo 'checked'; } ?> class="form-control" name="capital" id="capital1" type="radio" value="1" /> 
                                                <label class="pointer" for="capital2">Não</label><input <?php if ($this->registro['capital'] == 0) { echo 'checked'; } ?> class="form-control" name="capital" id="capital2" type="radio" value="0" />
                                            </div>
                                        </div><!-- End .form-group  -->
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <!-- Start .panel -->
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Faixa de CEP</h4>
                                    </div>
                                    <div class="panel-body">
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="valor_fixo">CEP - Início:</label>
                                            <div class="col-lg-4">
                                                <input class="form-control" name="cep_init" id="cep_init" type="text" value="<?php echo $this->registro['cep_init']; ?>" />
                                                
                                            </div><!-- End .form-group  -->
                                       
                                            <label class="col-lg-2 control-label" for="valor_fixo">CEP - Fim:</label>
                                            <div class="col-lg-4">
                                                <input class="form-control" name="cep_end" id="cep_end" type="text" value="<?php echo $this->registro['cep_end']; ?>" />
                                             
                                            </div><!-- End .form-group  -->
                                        </div>
                                        
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        
                        <div class="row">
                            <?php if ($this->id==""): ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['gravar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning "><span class="s24 typ-s-warning"></span>Você não tem permissão para gravar esta função.</span>
                                        </div>
                                    </div><!-- End .form-group  -->   
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="button" class="btn btn-info clickformsubmit">Salvar novo</button>
                                        </div>
                                    </div><!-- End .form-group  -->
                                <?php endif ?>
                            <?php else: ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['editar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning"><span class="s24 icomoon-s-warning "></span>Você não tem permissão para editar esta função.</span>
                                        </div>
                                    </div><!-- End .form-group  -->   
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="button" class="btn btn-info clickformsubmit">Salvar alterações</button>
                                        </div>
                                    </div><!-- End .form-group  -->
                                <?php endif ?>
                            <?php endif ?>
                        </div><!-- End .row -->  
                    </form>
                </div>
                <!-- End contentwrapper -->
            </div>
            <!-- End #content -->
            
            
<?php  require_once "layouts/footer.phtml"; ?>
        
        </div>
        
<?php  require_once "layouts/plugins.phtml"; ?>
        <script type="text/javascript" src="plugins/forms/dualselect/jquery.dualListBox-1.3.min.js"></script>
        <script type="text/javascript">

            $(document).ready(function(){

                $("#cep_init, #cep_end").mask("##.###-###");
                
            });
        </script>
    </body>
</html>
