<?php
    require_once "layouts/headers.phtml";
    
?>

    <script type="text/javascript">
        var pagina = "<?php echo $this->getModule(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";    
    </script>
    </head>  
    
    
    <body>
<?php  require_once "layouts/header.phtml"; ?>

        <!-- / #header -->
        <div id="wrapper">
        <!-- #wrapper -->

<?php  require_once "layouts/sidebar.phtml"; ?>
            
            <!--Body content-->
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <div class="heading">
                        <!--  .heading-->
                        <h3><?php echo $this->module_title; ?></h3>

                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li>
                                <a href="#" class="tip" title="voltar para o painel">
                                    <i class="s16 icomoon-icon-screen-2"></i>
                                </a>
                                <span class="divider">
                                    <i class="s16 icomoon-icon-arrow-right-3"></i>
                                </span>
                            </li>
                            <li class="active">Painel</li>
                        </ul>
                    </div>
                    <!-- End  / heading-->
                    <!-- 
                    <div class="row">
                        <div class="col-md-12">
                            <div class="panel panel-default toggle panelClose">                                
                                Start .panel
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <i class="icomoon-icon-stats-up"></i> Escolha o período
                                        <input class="datepicker box-header-date de" name="periodo_de" type="text" placeholder="De: " value="<?php echo date("d/m/Y", strtotime($_SESSION['periodo_de'])) ?>">
                                        <input class="datepicker box-header-date ate" name="periodo_ate" type="text" placeholder="Até: " value="<?php echo date("d/m/Y", strtotime($_SESSION['periodo_ate'])) ?>">
                                    </h4>                                    
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                     -->
                    <?php if ($_SESSION['admin_grupo'] != 7): ?>                  
                        <form action="<?php echo $this->getModule(); ?>" name="user" enctype="multipart/form-data" method="post" class="form-horizontal group-border">
                            <div class="row">
                                <div class="col-lg-4">
                                    <div class="panel panel-default toggle">
                                        <!-- Start .panel -->
                                        <div class="panel-heading">
                                            <h4 class="panel-title">Escolha um usuário para visualizar os seus relatórios</h4>
                                        </div>
                                        <div class="panel-body">
                                            <div class="form-group">
                                                <div class="col-lg-4">
                                                    <select name="user" id="user">
                                                        <?php foreach ($this->usuarios as $usuario): ?>
                                                            <option value="<?php echo $usuario['id'] ?>" <?php if($this->user_id == $usuario['id']) echo 'selected="selected"' ?>><?php echo $usuario['nome'] ?></option>
                                                        <?php endforeach ?>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    <?php endif ?>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="panel panel-default toggle panelClose">
                                <!-- Start .panel -->
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <i class="icomoon-icon-stats-up"></i> Quantidade de rodadas por mesa
                                    </h4>
                                </div>
                                <div class="panel-body">
                                    <table class="table table-bordered">
                                        <thead>
                                            <tr>
                                                <th>DIA</th>
                                                <?php $rodadas_qtd = array(); ?>
                                                <?php foreach ($this->charts_estatistica_rodadas as $key => $value): ?>
                                                    <?php 
                                                        $rodadas_qtd[] = json_decode($value['rodadas_qtd_json']);
                                                    ?>
                                                    <th><?php echo $value['nome'] ?></th>
                                                <?php endforeach ?>
                                            </tr>
                                        </thead>
                                        <?php

                                            $output = array();
                                            
                                            $month = date("m");
                                            $day = date("d");
                                            $year = date("Y");

                                            $rows = array();

                                            // monta array com últimos dias
                                            for($i=1; $i<=30; $i++){

                                                $date = date('Y-m-d',mktime(0,0,0,$month,($day-$i),$year));
                                                $date2 = date('d/m',mktime(0,0,0,$month,($day-$i),$year));
                                                $flag = false;

                                                $row = new StdClass();
                                                $row->date = $date2;
                                                $row->cols = array();
                                                foreach ($rodadas_qtd as $value) {
                                                    $flag = 0;
                                                    foreach((array)$value as $k => $v){
                                                        if($date == $k){
                                                            $flag = $v;
                                                        }
                                                    }
                                                    $row->cols[] = $flag;
                                                }
                                                $rows[] = $row;
                                            }

                                        ?>
                                        <tbody>
                                        <?php foreach ($rows as $item): ?>
                                            <tr>
                                                <td><?php echo $item->date; ?></td>
                                                <?php foreach ($item->cols as $qtd): ?>
                                                    <td><?php echo $qtd ?></td>
                                                <?php endforeach ?>
                                            </tr>
                                        <?php endforeach ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-8">
                            <div class="row">
                                <div class="panel panel-default toggle panelClose">
                                    <!-- Start .panel -->
                                    <div class="panel-heading">
                                        <h4 class="panel-title">
                                            <i class="icomoon-icon-stats-up"></i> Gráfico das Mesas
                                        </h4>
                                    </div>
                                    <div class="panel-body">
                                        <div class="visitors-chart" style="height: 230px;width:100%;margin-top:15px; margin-bottom:15px;"></div>
                                    </div>
                                </div>
                            </div>
                            <?php foreach ($this->charts_estatistica_rodadas as $key => $value): ?>
                                <div class="row">
                                    <div class="panel panel-default toggle panelClose">
                                        <!-- Start .panel -->
                                        <div class="panel-heading">
                                            <h4 class="panel-title">
                                                <i class="icomoon-icon-stats-up"></i> <?php echo $value['nome']; ?>
                                            </h4>
                                        </div>
                                        <div class="panel-body">
                                            <div class="linechart<?php echo $key; ?>" style="height: 230px;width:100%;margin-top:15px; margin-bottom:15px;"></div>
                                        </div>
                                    </div>
                                </div>
                            <?php endforeach ?>
                        </div>
                    </div>
                    <?php if (isset($this->charts_estatistica_rodadas)): ?>
                    <?php endif ?>
                                                                                
                </div>
                <!-- End contentwrapper -->
            </div>
            <!-- End #content -->
            
            
<?php  require_once "layouts/footer.phtml"; ?>
        
        </div>
        
<?php  require_once "layouts/plugins.phtml"; ?>

        <!-- Table plugins -->
        <script src="plugins/tables/dataTables/jquery.dataTables.js"></script>
        <script src="plugins/tables/dataTables/dataTables.tableTools.js"></script>
        <script src="plugins/tables/dataTables/dataTables.bootstrap.js"></script>
        <script src="plugins/tables/dataTables/dataTables.responsive.js"></script>

        <!-- Charts plugins -->
        <script src="plugins/charts/flot/jquery.flot.custom.js"></script>
        <script src="plugins/charts/flot/jquery.flot.pie.js"></script>
        <script src="plugins/charts/flot/jquery.flot.resize.js"></script>
        <script src="plugins/charts/flot/jquery.flot.time.js"></script>
        <script src="plugins/charts/flot/jquery.flot.orderBars.js"></script>
        <script src="plugins/charts/flot/jquery.flot.tooltip.min.js"></script>

        <script type="text/javascript" src="plugins/misc/fullcalendar/fullcalendar.min.js"></script><!-- Calendar plugin -->

        <script src="https://code.highcharts.com/highcharts.js"></script>
        <script src="https://code.highcharts.com/modules/exporting.js"></script>
        <script src="https://code.highcharts.com/modules/export-data.js"></script>

        <!-- Init plugins only for page -->
        <script type="text/javascript">
            $(document).ready(function(){


                <?php if ($_SESSION['admin_grupo'] != 7): ?>
                    $("select#user").change(function(e){
                        $("form[name=user]").trigger('submit');
                    });
                <?php endif ?>


                <?php if(isset($this->charts_estatistica_rodadas)): ?>
                    // ----------  RODADAS QUANTIDADE POR DATA
                    var chartColours = ['#88bbc8', '#ed7a53', '#9FC569', '#bbdce3', '#9a3b1b', '#5a8022', '#2c7282'];
                    <?php foreach ($this->charts_estatistica_rodadas as $key => $value): ?>

                        <?php

                            $output = array();
                            
                            $month = date("m");
                            $day = date("d");
                            $year = date("Y");

                            $bd = json_decode($value['rodadas_qtd_json']);

                            $dados = array();

                            // monta array com últimos dias
                            for($i=20; $i>=1; $i--){
                                $date = date('Y-m-d',mktime(0,0,0,$month,($day-$i),$year));
                                $date2 = date('d/m',mktime(0,0,0,$month,($day-$i),$year));
                                $flag = 0;
                                foreach((array)$bd as $k => $v){
                                    if($date == $k){
                                        $flag = $v;
                                    }
                                }
                                $dados[] = array($date2=>$flag);
                            }

                        ?>
                        var d<?php echo $key; ?> = [<?php foreach($dados as $k => $dado){ foreach($dado as $i => $j){ echo '['.$k.','.$j.'],';}} ?>];
                    <?php endforeach ?>
                    var ticks = [<?php foreach($dados as $k => $dado){ foreach($dado as $i => $j){ echo '['.$k.',"'.$i.'"],';}} ?>];


                    //define placeholder class
                    var placeholder = $(".visitors-chart");
                    //graph options
                    var options = {
                            grid: {
                                show: true,
                                aboveData: true,
                                color: "#3f3f3f" ,
                                labelMargin: 5,
                                axisMargin: 0, 
                                borderWidth: 0,
                                borderColor:null,
                                minBorderMargin: 5 ,
                                clickable: true, 
                                hoverable: true,
                                autoHighlight: true,
                                mouseActiveRadius: 20
                            },
                            series: {
                                grow: {
                                    active: false,
                                    stepMode: "linear",
                                    steps: 50,
                                    stepDelay: true
                                },
                                lines: {
                                    show: true,
                                    fill: false,
                                    lineWidth: 4,
                                    steps: false
                                    },
                                points: {
                                    show:false
                                }
                            },
                            legend: { 
                                position: "ne", 
                                margin: [0,-25], 
                                noColumns: 0,
                                labelBoxBorderColor: null,
                                labelFormatter: function(label, series) {
                                    // just add some space to labes
                                    return label+'&nbsp;&nbsp;';
                                 }
                            },
                            yaxis: { min: 0 },
                            xaxis: {ticks:ticks, tickDecimals: 0},
                            colors: chartColours,
                            shadowSize:1,
                            tooltip: true, //activate tooltip
                            tooltipOpts: {
                                content: "%s : %y.0",
                                shifts: {
                                    x: -30,
                                    y: -50
                                }
                            }
                        };
                        console.log(options.xaxis.ticks);
                
                        $.plot(placeholder, [ 
                        <?php foreach ($this->charts_estatistica_rodadas as $key => $value): ?>
                            {
                                label: "<?php echo $value['nome']; ?>", 
                                data: d<?php echo $key; ?>
                            }, 
                        <?php endforeach ?>

                        ], options);

                    <?php foreach ($this->charts_estatistica_rodadas as $key => $value): ?>

                        <?php
                            $rodadas_registros_json = json_decode($value['rodadas_registros_json']);

                            if ($value['tipo']=="Dois Zeros"){
                                $ordem = array(0,28,9,26,30,11,7,20,32,17,5,22,34,15,3,24,36,13,1,37,27,10,25,29,12,8,19,31,18,6,21,33,16,4,23,35,14,2);
                            }else{
                                $ordem = array(0,32,15,19,4,21,2,25,17,34,6,27,13,36,11,30,8,23,10,5,24,16,33,1,20,14,31,9,22,18,29,7,28,12,35,3,26);
                            }

                            $data = array();
                            foreach ($ordem as $ky => $val) {
                                $data[] = array($ky, $rodadas_registros_json[$val]);
                            }
                        ?>

                        var linechart<?php echo $key; ?> = <?php echo json_encode($data); ?>;
                        options.xaxis.ticks = [<?php foreach ($ordem as $k => $val) { echo '['.$k.',"'.str_replace("37", "00", $val).'"],'; } ?>];
                        var placeholder<?php echo $key; ?> = $(".linechart<?php echo $key; ?>");
                        $.plot(placeholder<?php echo $key; ?>, [{label:"<?php echo $value['nome'] ?>", data: linechart<?php echo $key; ?> }],options);

                    <?php endforeach ?>


                <?php endif ?>


            });
        </script>
    </body>
</html>
