<?php
    require_once "layouts/headers.phtml";
?>

    <script type="text/javascript">
        var pagina = "<?php echo $this->getModule(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getModule(); ?>/save";
        var retorno = "<?php echo $this->retorno; ?>";
    </script>
    
    </head>  
    
    
    <body>
<?php  require_once "layouts/header.phtml"; ?>

        <!-- / #header -->
        <div id="wrapper">
        <!-- #wrapper -->

<?php  require_once "layouts/sidebar.phtml"; ?>
            
            <!--Body content-->
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <!--Content wrapper-->
                    <div class="heading">
                        <!--  .heading-->
                        <h3><?php echo $this->module_title; ?></h3>

                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li>
                                <a href="#" class="tip" title="Painel">
                                    <i class="s16 icomoon-s-screen-2"></i>
                                </a>
                                <span class="divider">
                                    <i class="s16 icomoon-s-arrow-right-3"></i>
                                </span>
                            </li>
                            <li>
                                <a class="tip" title="<?php echo $this->module_title; ?>" href="<?php echo $this->module_link;?>">
                                    <i class="s16 <?php echo $this->module_icon; ?>"></i>                                    
                                </a>
                            </li>
                            <span class="divider">
                                <i class="s16 icomoon-s-arrow-right-3"></i>
                            </span>
                            <li class="active">Registro</li>
                        </ul>
                    </div>
                    <!-- End  / heading-->
                    <!-- Start .row -->
                  
                    <form name="main" enctype="multipart/form-data" method="post" class="form-horizontal group-border">
                        <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
                        <input type="hidden" name="retorno" value="<?php echo $this->retorno; ?>">
                        <?php if($_SERVER['REQUEST_METHOD'] == 'POST') :?>
                        <input type="hidden" name="id_user" value="<?php echo $this->registro["id_user"]; ?>" />
                        <input type="hidden" name="almoco" value="<?php echo $this->registro["almoco"]; ?>">
                        <input type="hidden" name="minutos_dia" value="<?php echo $this->registro["minutos_dia"]; ?>">
                        <input type="hidden" name="hora_contrato" value="<?php echo $this->registro["hora_contrato"]; ?>">
                        <input type="hidden" name="ip" value="<?php echo $this->registro["ip"]; ?>">
                        <?php endif; ?>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <!-- Start .panel -->
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Dados do Ponto Eletrônico</h4>
                                    </div>
                                    <div class="panel-body">
                                        
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="funcionario">Funcionário:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="funcionario" id="funcionario" type="text" value="<?php echo $this->registro['funcionario'] ?>" readonly/>
                                            </div>
                                        </div><!-- End .form-group  -->
                                       
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="data">Data:</label>
                                            <div class="col-lg-10">
                                                <input name="data" id="data" type="text" value="<?php echo $this->registro['data'] ?>" <?php if($_SERVER['REQUEST_METHOD'] == 'POST') :?> class="form-control" readonly <?php else :?> class="form-control data" <?php endif; ?>/>
                                            </div>
                                        </div><!-- End .form-group  -->
                                                                                
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="hora">Hora:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control hora" name="hora" id="hora" type="text" value="<?php echo $this->registro['hora'] ?>" />
                                            </div>
                                        </div><!-- End .form-group  -->

                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="identificador">Referencia:</label>
                                            <div class="col-lg-10">
                                                <?php if($_SERVER['REQUEST_METHOD'] == 'POST') :?>
                                                <input class="form-control" name="identificador" id="identificador" type="text" value="<?php echo $this->registro['identificador'] ?>" readonly/>
                                                <?php else :?>
                                                <select id="identificador" name="identificador"  class="form-control">
                                                    <?php foreach ($this->referencias as $key => $value) : ?>
                                                        <option <?php if ($this->registro['identificador'] == $key) echo 'selected'; ?> value="<?php echo $key; ?>"><?php echo $value; ?></option>                                                        
                                                    <?php endforeach; ?>                                                                      
                                                </select>
                                                <?php endif; ?>
                                            </div>
                                        </div><!-- End .row -->

                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <?php if ($this->id==""): ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['gravar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning "><span class="s24 typ-s-warning"></span>Você não tem permissão para gravar esta função.</span>
                                        </div>
                                    </div><!-- End .form-group  -->   
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="button" class="btn btn-info clickformsubmit">Salvar novo</button>
                                        </div>
                                    </div><!-- End .form-group  -->
                                <?php endif ?>
                            <?php else: ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['editar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning"><span class="s24 icomoon-s-warning "></span>Você não tem permissão para editar esta função.</span>
                                        </div>
                                    </div><!-- End .form-group  -->   
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="button" class="btn btn-info clickformsubmit">Salvar alterações</button>
                                        </div>
                                    </div><!-- End .form-group  -->
                                <?php endif ?>
                            <?php endif ?>
                        </div><!-- End .row -->  
                    </form>
                </div>
                <!-- End contentwrapper -->
            </div>
            <!-- End #content -->
            
            
<?php  require_once "layouts/footer.phtml"; ?>
        
        </div>
        
<?php  require_once "layouts/plugins.phtml"; ?>
        <!-- Init plugins only for page -->
        <script type="text/javascript">
            $(document).ready(function(){
                $(".data").datepicker({
                    dateFormat: 'dd/mm/yy',
                    dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'],
                    dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
                    dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
                    monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
                    monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
                    nextText: 'Próximo',
                    prevText: 'Anterior'
                });
                
                $('.hora').mask('00:00:00');
                $('.data').mask('00/00/0000');
                
            });
        </script>
    </body>
</html>
