<?php
    require_once "layouts/headers.phtml";
?>
    <link href="css/supr-theme/jquery.ui.supr.css" rel="stylesheet" type="text/css"/> 
    
    <link href="plugins/files/elfinder/elfinder.css" type="text/css" rel="stylesheet" />
    <link href="plugins/files/plupload/jquery.ui.plupload/css/jquery.ui.plupload.css" type="text/css" rel="stylesheet" />
    
    <link href="plugins/gallery/jpages/jPages.css" rel="stylesheet" type="text/css" />
    <link href="plugins/gallery/pretty-photo/prettyPhoto.css" type="text/css" rel="stylesheet" />   

    <script type="text/javascript">
        var pagina = "<?php echo $this->getModule(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getModule(); ?>/save";
        var retorno = "<?php echo $this->retorno; ?>";
    </script>
    
    </head>  
    
    
    <body>
<?php  require_once "layouts/header.phtml"; ?>

        <!-- / #header -->
        <div id="wrapper">
        <!-- #wrapper -->

<?php  require_once "layouts/sidebar.phtml"; ?>
            
            <!--Body content-->
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <!--Content wrapper-->
                    <div class="heading">
                        <!--  .heading-->
                        <h3><?php echo $this->module_title; ?></h3>

                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li>
                                <a href="#" class="tip" title="Painel">
                                    <i class="s16 icomoon-icon-screen-2"></i>
                                </a>
                                <span class="divider">
                                    <i class="s16 icomoon-icon-arrow-right-3"></i>
                                </span>
                            </li>
                            <li>
                                <a class="tip" title="<?php echo $this->module_title; ?>" href="<?php echo $this->module_link;?>">
                                    <i class="s16 <?php echo $this->module_icon; ?>"></i>                                    
                                </a>
                            </li>
                            <span class="divider">
                                <i class="s16 icomoon-icon-arrow-right-3"></i>
                            </span>
                            <li class="active">Registro</li>
                        </ul>
                    </div>
                    <!-- End  / heading-->
                    <!-- Start .row -->
                  
                    <div class="row">
                        <div class="col-lg-12 ">
                            <div class="tabs mb20">
                                <ul id="myTab" class="nav nav-tabs">
                                    <li>
                                        <a href="#conteudo" data-toggle="tab">Conteúdo</a>
                                    </li>
                                    <?php if ($this->id!=""): ?>
                                    <li class="" style="display:none">
                                        <a href="#fotos" data-toggle="tab">Fotos</a>
                                    </li>
                                    <?php endif; ?>
                                </ul>
                                <div id="myTabContent2" class="tab-content">
                                    <div class="tab-pane fade active in" id="conteudo">
                                        <form name="main" enctype="multipart/form-data" method="post" class="form-horizontal group-border">
                                            <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
                                            <input type="hidden" name="id_seo" value="<?php echo $this->registro['id_seo']; ?>" />
                                            <input type="hidden" name="retorno" value="<?php echo $this->retorno; ?>">
                                            <input type="hidden" name="id_categoria" value="3">
                                            
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <div class="panel panel-default toggle">
                                                        <!-- Start .panel -->
                                                        <div class="panel-heading">
                                                            <h4 class="panel-title">Dados da Página                                               
                                                            </h4>
                                                        </div>
                                                        <div class="panel-body">
                                                            
<!--                                                            <div class="form-group form-group-vertical">
                                                                <label class="col-lg-2 col-md-3 control-label" for="id_categoria">Categoria</label>
                                                                <div class="col-lg-10 col-md-9">
                                                                    <select class="form-control input-sm" id="id_categoria" name="id_categoria">
                                                                        <option value="">Selecione..</option>
                                                                        <?php if ($this->categorias->num_rows) : ?>
                                                                            <?php foreach ($this->categorias->rows as $categoria) : ?>
                                                                                <option <?php if ($categoria['id'] == $this->registro['id_categoria']) echo "selected"; ?> value="<?php echo $categoria['id']; ?>"><?php echo $categoria['nome']; ?></option>
                                                                            <?php endforeach; ?>
                                                                        <?php endif; ?>
                                                                    </select>
                                                                </div>
                                                            </div>-->
                                                            
                                                            <div class="form-group">
                                                                <label class="col-lg-2 control-label" for="nome">Nome:</label>
                                                                <div class="col-lg-10">
                                                                    <input class="form-control" name="nome" id="nome" type="text" value="<?php echo $this->registro['nome'] ?>" />
                                                                </div><!-- End .form-group  -->
                                                            </div>

                                    
                                                            <div class="form-group" style="display:none">
                                                                <label class="col-lg-2 control-label" for="fileupload">Imagem:</label>
                                                                <div class="col-lg-10">
                                                                    <label class="fileupload" for="fileupload">
                                                                        <?php if ($this->registro['imagem'] == ""): ?>
                                                                            <img src="http://placehold.it/559x280" alt="" class="image marginR10"/>
                                                                        <?php else: ?>
                                                                            <img src="<?php echo $this->getImageFileSized($this->registro['imagem'],559,280); ?>" alt="" class="image marginR10"/>
                                                                        <?php endif ?>
                                                                    </label>
                                                                    <input type="file" name="fileupload" id="fileupload" class="files btn btn-default"/>
                                                                    <span class="help-block blue">imagem será apresentada na seguinte proporção 559x280 pixels.</span>
                                                                </div>
                                                            </div>
                                        

                                                            <div class="form-group">
                                                                <label class="col-lg-2 control-label" for="texto">Texto:</label>
                                                                <div class="col-lg-10">
                                                                    <textarea id="texto" name="texto" class="form-control tinymce" rows="10"><?php echo $this->registro['texto'] ?></textarea>
                                                                </div>
                                                            </div>

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <span style="display:none">
                                            <?php require_once "layouts/seo_form.phtml"; ?>
                                            </span>
                                            <div class="row">
                                                <?php if ($this->id==""): ?>
                                                    <?php if (!$this->permissions[$this->permissao_ref]['gravar']): ?>
                                                        <div class="form-group">
                                                            <div class="col-lg-offset-2 col-lg-10">
                                                                <span class="label label-warning "><span class="icon24 typ-icon-warning"></span>Você não tem permissão para gravar esta função.</span>
                                                            </div>
                                                        </div><!-- End .form-group  -->   
                                                    <?php else: ?>
                                                        <div class="form-group">
                                                            <div class="col-lg-offset-2 col-lg-10">
                                                                <button type="button" class="btn btn-info clickformsubmit">Salvar novo</button>
                                                            </div>
                                                        </div><!-- End .form-group  -->
                                                    <?php endif ?>
                                                <?php else: ?>
                                                    <?php if (!$this->permissions[$this->permissao_ref]['editar']): ?>
                                                        <div class="form-group">
                                                            <div class="col-lg-offset-2 col-lg-10">
                                                                <span class="label label-warning"><span class="icon24 icomoon-icon-warning "></span>Você não tem permissão para editar esta função.</span>
                                                            </div>
                                                        </div><!-- End .form-group  -->   
                                                    <?php else: ?>
                                                        <div class="form-group">
                                                            <div class="col-lg-offset-2 col-lg-10">
                                                                <button type="button" class="btn btn-info clickformsubmit">Salvar alterações</button>
                                                            </div>
                                                        </div><!-- End .form-group  -->
                                                    <?php endif ?>
                                                <?php endif ?>
                                            </div><!-- End .row -->  
                                        </form>
                                    </div>
                                    <?php if ($this->id!=""): ?>
                                    <div class="tab-pane fade" id="fotos">
                                        <div id="edita_imagem" style="display:none;">
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="panel panel-default">
                                                    <!-- Start .panel -->
                                                    <div class="panel-heading">
                                                        <h4 class="panel-title"><i class="entypo-icon-images"></i>Galeria de Imagens</h4>
                                                    </div>
                                                    <div class="panel-body noPad">
                                                        <ul id="itemContainer" class="galleryView center sortable">
                                                        </ul>
                                                    </div>
                                                </div><!-- End .span12 -->
                                            </div><!-- End .panel -->
                                        </div><!-- End .row -->
                                        <div class="row">
                                            <div class="col-lg-12 center sortable_save" style="display:none">
                                            	<button type="button" class="btn btn-info sortablesubmit">Salvar nova ordenação</button><br><br>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="panel panel-default toggle">
                                                    <!-- Start .panel -->
                                                    <div class="panel-heading">
                                                        <h4 class="panel-title"><i class="icomoon-icon-upload"></i>Gerenciador de envio</h4>
                                                    </div>
                                                   <div class="panel-body noPad">
                                                        <div id="html4_uploader" style="width: 100%; height: 100%;">O seu navegador não tem suporte HTML 4.</div>
                                                    </div>
                                                </div><!-- End .panel -->
                                            </div><!-- End .span12 -->
                                        </div><!-- End .row -->
                                    </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>
                <!-- End contentwrapper -->
            </div>
            <!-- End #content -->
            
            
<?php  require_once "layouts/footer.phtml"; ?>
        
        </div>
        
<?php  require_once "layouts/plugins.phtml"; ?>
        <!-- Init plugins only for page -->
        <script src="plugins/forms/tiny_mce/tinymce.min.js"></script>
        <script src="plugins/ui/tabdrop/bootstrap-tabdrop.js"></script>
        <script src="js/pages/tabs.js"></script>
        <script type="text/javascript" src="plugins/files/elfinder/elfinder.min.js"></script>
        <script type="text/javascript" src="plugins/files/plupload/plupload.js"></script>
        <script type="text/javascript" src="plugins/files/plupload/plupload.html4.js"></script>
        <script type="text/javascript" src="plugins/files/plupload/plupload.flash.js"></script>
        <script type="text/javascript" src="plugins/files/plupload/jquery.plupload.queue/jquery.plupload.queue.js"></script>
        <script src="plugins/forms/autosize/jquery.autosize.js"></script>
        
        <!-- Gallery plugins -->
        <script type="text/javascript" src="plugins/gallery/pretty-photo/jquery.prettyPhoto.js"></script>
    
        <script type="text/javascript">
            $(document).ready(function(){
                tinymceInit({'galeria':true});      
                $('.elastic').autosize();
                var load_galery_url = "institutional/fotos/id/<?php echo $this->id; ?>"
                $(".galleryView").load(load_galery_url).data("load_galery_url",load_galery_url);
                
                //------------- Plupload php upload  -------------//
                $("#html4_uploader").pluploadQueue({
                    // General settings
                    runtimes : 'flash,silverlight,html4', 
                    url : 'institutional/upload/id/<?php echo $this->id ?>/session/<?php echo $_SESSION["login_session"];?>',
                    max_file_size : '10mb',
                    max_file_count: 15, // user can add no more then 15 files at a time
                    chunk_size : '0',
                    unique_names : false,
                    multiple_queues : true,

                    // Resize images on clientside if we can
                    //resize : {width : 320, height : 240, quality : 80},

                    // Rename files by clicking on their titles
                    rename: false,

                    // Sort files
                    sortable: true,

                    // Flash settings
                    flash_swf_url : 'plugins/files/plupload/plupload.flash.swf',

                    // Specify what files to browse for
                    filters : [
                        {title : "Image files", extensions : "jpg,gif,png"},
                        {title : "Zip files", extensions : "zip,avi"}
                    ],

                    init : {
                        FileUploaded: function(up, file, info) {
                            console.log(up);
                            console.log(file);
                            console.log(info);
                            // Called when all files are either uploaded or failed
                            $(".galleryView").load(load_galery_url);
                        },
                        UploadComplete: function(up, files) {
                            console.log(up);
                            console.log(files);                            
                            // Called when all files are either uploaded or failed
                            $(".galleryView").load(load_galery_url);
                        }
                    }

                });

            });
        </script>
    </body>
</html>
