
                                                                                    <div class="form-group node">
                                                                                        <label class="col-lg-2 control-label" for="deducao_descricao">Cálculo de Fábrica:</label>
                                                                                        <div class="col-lg-4">
                                                                                            <input placeholder="Descrição" class="form-control deducao_descricao" name="deducao_descricao" type="text" value="" />
                                                                                        </div>
                                                                                        <div class="col-lg-4">
                                                                                            <input placeholder="Valor" class="form-control deducao_valor" name="deducao_valor" type="text" value="" />
                                                                                        </div>
                                                                                        <div class="col-lg-2">
                                                                                            
                                                                                            <button type="button" class="btn btn-danger btn-minus-deducao">-</button>
                                                                                            <button type="button" class="btn btn-primary btn-plus-deducao">+</button>
                                                                                            
                                                                                        </div>
                                                                                    </div>