<?php
    require_once "layouts/headers.phtml";
?>

    <script type="text/javascript">
        var pagina = "<?php echo $this->getModule(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getModule(); ?>";
    </script>
    
    </head>  
    
    
    <body>
<?php  require_once "layouts/header.phtml"; ?>

        <!-- / #header -->
        <div id="wrapper">
        <!-- #wrapper -->

<?php  require_once "layouts/sidebar.phtml"; ?>
            <!--Body content-->
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <!--Content wrapper-->
                    <div class="heading">
                        <!--  .heading-->
                        <h3><?php echo $this->module_title; ?></h3>

                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li>
                                <a href="#" class="tip" title="Painel">
                                    <i class="s16 icomoon-icon-screen-2"></i>
                                </a>
                                <span class="divider">
                                    <i class="s16 icomoon-icon-arrow-right-3"></i>
                                </span>
                            </li>
                            <li class="active"><?php echo $this->module_title;?></li>
                        </ul>
                    </div>
                    <!-- End  / heading-->
                    <!-- Start .row -->
                    
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="panel panel-default toggle panelClose">
                                <!-- Start .panel -->
                                <div class="panel-heading">
                                    <h4 class="panel-title"><i class="<?php echo $this->module_icon ?>"></i> Tabela de Pedidos
                                        <label class="select-all">Selecionar estes <input type="checkbox" id="apagar_todos"></label>
                                    </h4>
                                </div>
                                <div class="panel-body">
                                    <?php /* ?>
                                    <table cellpadding="0" cellspacing="0" border="0" class="tabletools table table-striped table-bordered" width="100%">
                                        <thead>
                                            <tr>
                                                <th style="display:none"></th>
                                                <th width="15%" class="tal">Data da Compra</th>
                                                <th class="tal">Nº do Pedido</th>
                                                <th class="tal">Cliente</th>
                                                <th width="10%" class="tal">Previsão de Entrega</th>
                                                <th class="tal">Tipo de Pagamento</th>
                                                <th width="15%" class="tal">Status do Pedido</th>
                                                <th class="tal">Valor Total</th>
                                                <th style="min-width: 120px" class="center">Ação</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php if ($this->list->num_rows) : ?>
                                                <?php foreach($this->list->rows as $registro):?>
                                            <?php 
                                                $valor_total = 0;
                                                $cupom = 0;

                                                $valor_total = $registro['subtotal'] + $registro['valor_frete'] - $registro['descontos'];

                                                if ($registro['valor_cupom']) {
                                                    if ($registro['tipo_cupom'] != 1)
                                                        $cupom = $produto['valor_cupom'];
                                                    else
                                                        $cupom = (($valor_total*$registro['valor_cupom'])/100);
                                                }

                                                $valor_total = $valor_total - $cupom;

                                                if ($registro['avista'] == 1)
                                                    $valor_total = $valor_total - (($valor_total * 5) /100);
                                        
                                            ?>
                                                    <tr>
                                                        <td style="display:none"><?php echo $registro['registro'];?></td>
                                                        <td class="tal"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $registro['id']; ?>"><?php echo $registro['data_compra'];?></a></td>
                                                        <td class="tal"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $registro['id']; ?>"><?php echo $registro['id'];?></a></td>
                                                        <td class="tal"><a class="tip" title="Ir Para o Cliente" href="client/edit/id/<?php echo $registro['id_cliente'];?>" target="_blank"><?php echo $registro['cliente'];?></a></td>
                                                        <td class="tal"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $registro['id']; ?>"><?php echo $registro['prazo_entrega'];?></a></td>
                                                        <td class="tal"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $registro['id']; ?>"><?php echo $this->paymentType($registro['metodo_pagamento']);?></a></td>
                                                        <td class="tal"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $registro['id']; ?>"><?php echo $registro['status'];?></a></td>
                                                        <td class="tal"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $registro['id']; ?>">R$ <?php echo $this->formataMoedaShow($valor_total);?></a></td>
                                                        <td class="center">
                                                            <a target="_blank" href="<?php echo $this->root_path; ?>script/pedido/pdf/?pedido=<?php echo $registro['code']; ?>"><i class="s12 icomoon-icon-file-pdf"></i></a>
                                                            <a href="<?php echo $this->getModule()?>/edit/id/<?php echo $registro['id']; ?>"><i class="s12 icomoon-icon-pencil"></i></a>
                                                            <?php if ($this->permissions[$this->permissao_ref]['excluir']): ?>
                                                                <a class="bt_system_delete" data-controller="<?php echo $this->getModule()?>" data-id="<?php echo $registro['id']; ?>" href="#"><i class="s12 icomoon-icon-remove"></i></a>
                                                                <input type="checkbox" id="del_<?php echo $registro['id']; ?>" value="<?php echo $registro['id']; ?>" class="del-this">
                                                            <?php endif ?>
                                                        </td>
                                                    </tr>
                                                <?php endforeach; ?>
                                            <?php endif; ?>
                                        </tbody>
                                    </table>
                                    <?php */ ?>
                                    <table cellpadding="0" cellspacing="0" border="0" class="tabletools table table-striped table-bordered" width="100%">
                                        <thead>
                                            <tr>
                                                <th style="display:none"></th>
                                                <th class="tal" width="80">Pedido</th>
                                                <th class="tal" width="110">Vendedor</th>
                                                <th class="tal" width="110">Data</th>
                                                <th class="tal" width="180">Cliente</th>
                                                <th class="tal" width="100" style="display:none">CPF</th>
                                                <th class="tal" width="150" style="display:none">Email</th>
                                                <th class="tal" width="120">Telefone</th>
                                                <th class="tal" width="120">Cidade</th>
                                                <th class="tal" width="120">Estado</th>
                                                <th class="tal" width="120">Tipo de Pagamento</th>
                                                <th class="tal" width="120">Status do Pedido</th>
                                                <th class="tal" width="120">Valor Total</th>
                                                <th class="tal" width="120" style="display:none">Nota Fiscal</th>
                                                <th class="tal" width="120">Editando</th>
                                                <th width="100" class="center">Ação</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php if ($this->list->num_rows) : ?>
                                                <?php foreach($this->list->rows as $registro):?>
                                                    <tr>
                                                        <td style="display:none"><?php echo $registro['registro'];?></td>
                                                        <td class="tal" style="border-left:7px solid <?php echo $registro['cor'];?>;"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $registro['id']; ?>"><?php echo $registro['id'];?></a></td>
                                                        <td class="tal"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $registro['id']; ?>"><?php if($registro['vendedor'] == "") echo "sem vendedor";else echo $registro['vendedor'];?></a></td>
                                                        <td class="tal"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $registro['id']; ?>"><?php echo $registro['data_compra'];?></a></td>
                                                        <td class="tal"><a class="tip" title="Ir Para o Cliente" href="client/edit/id/<?php echo $registro['id_cliente'];?>" target="_blank"><?php echo $registro['cliente'];?></a></td>
                                                        <td class="tal" style="display:none"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $registro['id']; ?>"><?php echo $registro['cpf'];?></a></td>
                                                        <td class="tal" style="display:none"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $registro['id']; ?>"><?php echo $registro['email'];?></a></td>
                                                        <td class="tal"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $registro['id']; ?>"><?php echo $registro['telefone'];?></a></td>
                                                        <td class="tal"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $registro['id']; ?>"><?php echo $registro['cidade'];?></a></td>
                                                        <td class="tal"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $registro['id']; ?>"><?php echo $registro['estado'];?></a></td>
                                                        <td class="tal"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $registro['id']; ?>"><?php echo $this->paymentType($registro['metodo_pagamento']); if($registro['payment_method_brand'] != '') echo ' ('.$this->cieloBrands($registro['payment_method_brand']).')'; ?></a></td>
                                                        <td class="tal" style="border-left:7px solid <?php echo $registro['cor'];?>;"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $registro['id']; ?>"><?php echo $registro['status'];?></a></td>
                                                        <td class="tal"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $registro['id']; ?>">R$ <?php echo $this->formataMoedaShow($registro['valor_final']);?></a></td>
                                                        <td class="tal" style="display:none"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $registro['id']; ?>"><?php echo $registro['n_nota'];?></a></td>
                                                        <td class="tal"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $registro['id']; ?>"><?php if($registro['usuario_editando_ultimo_ping'] != '' AND (strtotime(date("Y-m-d H:i:s")) - strtotime($registro['usuario_editando_ultimo_ping'])) < 60) echo $registro['editando'];?></a></td>
                                                        <td class="center">
                                                            <!--<a target="_blank" href="<?php echo $this->root_path; ?>script/pedido/pdf/?pedido=<?php echo $registro['code']; ?>"><i class="s12 icomoon-icon-file-pdf"></i></a>
                                                            <a href="<?php echo $this->getModule()?>/edit/id/<?php echo $registro['id']; ?>"><i class="s12 icomoon-icon-pencil"></i></a>-->
                                                            <?php if ($this->permissions[$this->permissao_ref]['excluir']): ?>
                                                                <a class="bt_system_delete" data-controller="<?php echo $this->getModule()?>" data-id="<?php echo $registro['id']; ?>" href="#"><i class="s12 icomoon-icon-remove"></i></a>
                                                                <input type="checkbox" id="del_<?php echo $registro['id']; ?>" value="<?php echo $registro['id']; ?>" class="del-this">
                                                            <?php endif ?>
                                                        </td>
                                                    </tr>
                                                <?php endforeach; ?>
                                            <?php endif; ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div><!-- End .row -->
                    <?php require_once "layouts/options.phtml"; ?>
                </div>
                <!-- End contentwrapper -->
            </div>
            <!-- End #content -->
            
            
<?php  require_once "layouts/footer.phtml"; ?>
        
        </div>
        
<?php  require_once "layouts/plugins.phtml"; ?>

        <!-- Table plugins -->
        <script src="plugins/tables/dataTables/jquery.dataTables.js"></script>
        <script src="plugins/tables/dataTables/dataTables.tableTools.js"></script>
        <script src="plugins/tables/dataTables/dataTables.bootstrap.js"></script>
        <script src="plugins/tables/dataTables/dataTables.responsive.js"></script>


        <!-- Init plugins only for page -->
        <script type="text/javascript">
            $(document).ready(function(){

                //--------------- Data tables ------------------//
                if($('table').hasClass('tabletools')){
                    $('.tabletools').dataTable( {
                        "oLanguage": {
                            "sSearch": "",
                            "sLengthMenu": "<span>_MENU_</span>",
                            "sProcessing":   "Processando...",                    
                            "sZeroRecords":  "Não foram encontrados resultados",
                            "sInfo":         "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                            "sInfoEmpty":    "Mostrando de 0 até 0 de 0 registros",
                            "sInfoFiltered": "(filtrado de _MAX_ registros no total)",
                            "sInfoPostFix":  "",
                            "sUrl":         "",

                            "oPaginate": {
                                "sFirst":    "Primeiro",
                                "sPrevious": "Anterior",
                                "sNext":     "Seguinte",
                                "sLast":     "Último"
                            }
                        },
                        "sDom": "T<'row'<'col-md-6 col-xs-12 'l><'col-md-6 col-xs-12'f>r>t<'row'<'col-md-4 col-xs-12'i><'col-md-8 col-xs-12'p>>",
                        "aaSorting":[[0,"desc"]],
                         "iDisplayLength": 100,
                        tableTools: {
                            "sSwfPath": "http://cdn.datatables.net/tabletools/2.2.2/swf/copy_csv_xls_pdf.swf",
                            "aButtons": [
                          ]
                        }


                    });

                }

            });
        </script>
    </body>
</html>
