
                                            <div class="form-group node">
                                                <label class="col-lg-2 control-label">Rastreio:</label>
                                                <div class="col-lg-4">
                                                    <input placeholder="Descrição" class="form-control descricao" name="descricao[]" type="text" value="" />
                                                </div>
                                                <div class="col-lg-4">
                                                    <input placeholder="Link" class="form-control link" name="link[]" type="text" value="" />
                                                </div>
                                                <div class="col-lg-2">
                                                    <input class="form-control rastreio_stats" name="rastreio_stats[]" type="hidden" value="0" />
                                                    <button type="button" class="btn btn-danger btn-minus">-</button>
                                                    <button type="button" class="btn btn-primary btn-plus">+</button>
                                                </div>
                                            </div>

