<?php
    require_once "layouts/headers.phtml";
?>

    <script type="text/javascript">
        var pagina = "<?php echo $this->getModule(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getModule(); ?>/save";
        var retorno = "<?php echo $this->retorno; ?>";
    </script>

    </head>


    <body>
<?php  require_once "layouts/header.phtml"; ?>

        <!-- / #header -->
        <div id="wrapper">
        <!-- #wrapper -->

<?php  require_once "layouts/sidebar.phtml"; ?>

            <!--Body content-->
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <!--Content wrapper-->
                    <div class="heading">
                        <!--  .heading-->
                        <h3><?php echo $this->module_title; ?></h3>

                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li>
                                <a href="#" class="tip" title="Painel">
                                    <i class="s16 icomoon-s-screen-2"></i>
                                </a>
                                <span class="divider">
                                    <i class="s16 icomoon-s-arrow-right-3"></i>
                                </span>
                            </li>
                            <li>
                                <a class="tip" title="<?php echo $this->module_title; ?>" href="<?php echo $this->module_link;?>">
                                    <i class="s16 <?php echo $this->module_icon; ?>"></i>
                                </a>
                            </li>
                            <span class="divider">
                                <i class="s16 icomoon-s-arrow-right-3"></i>
                            </span>
                            <li class="active">Registro</li>
                        </ul>
                    </div>
                    <!-- End  / heading-->
                    <!-- Start .row -->

                    <form name="main" enctype="multipart/form-data" method="post" class="form-horizontal group-border">
                        <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
                        <input type="hidden" name="retorno" value="<?php echo $this->retorno; ?>">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <!-- Start .panel -->
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Dados do Cliente</h4>
                                    </div>
                                    <div class="panel-body">
                                        <?php if ($this->id != "") :?>
                                            <div class="form-group">
                                                <label class="col-lg-2 control-label">Data de Cadastro</label>
                                                <div class="col-lg-10">
                                                    <input type="text" name="chave_data" class="form-control" value="<?php echo $this->registro['data'] ?>" disabled />
                                                </div>
                                            </div><!-- End .form-group  -->
                                            <div class="form-group">
                                                <label class="col-lg-2 control-label" for="">Origem:</label>
                                                <div class="col-lg-10">
                                                    <input class="form-control" name="" id="" type="text" value="<?php echo $this->registro['origem'] ?>" disabled />
                                                </div>
                                            </div><!-- End .form-group  -->

                                            <div class="form-group">
                                                <label class="col-lg-2 control-label" for="">UTM:</label>
                                                <div class="col-lg-10">
                                                    <input class="form-control" name="" id="" type="text" value="<?php echo $this->registro['utm'] ?>" disabled />
                                                </div>
                                            </div><!-- End .form-group  -->
                                        <?php endif; ?>


                                        <div class="form-group">
                                            <label class="col-lg-2 col-md-3 control-label">Pessoa:</label>
                                            <div class="col-lg-10 col-md-9">
                                                <select name="pessoa" id="pessoa" class="form-control">
                                                    <option <?php if($this->registro['pessoa']=='1') { echo "selected"; } ; ?> value="1">Pessoa Física</option>
                                                    <option <?php if($this->registro['pessoa']=='2') { echo "selected"; } ; ?> value="2">Pessoa Jurídica</option>
                                                </select>
                                            </div>
                                        </div>

                                        <?php if($this->registro['pessoa']=='2') :?>

                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="razao_social">Razão Social:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="razao_social" id="razao_social" type="text" value="<?php echo $this->registro['razao_social'] ?>" />
                                            </div>
                                        </div><!-- End .form-group  -->

                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="cnpj">CNPJ:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="cnpj" id="cnpj" type="text" value="<?php echo $this->registro['cnpj'] ?>" />
                                            </div>
                                        </div><!-- End .form-group  -->

                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="inscricao_estadual">Inscrição Estadual:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="inscricao_estadual" id="inscricao_estadual" type="text" value="<?php echo $this->registro['inscricao_estadual'] ?>" />
                                            </div>
                                        </div><!-- End .form-group  -->

                                        <?php endif; ?>



                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="nome">Nome:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="nome" id="nome" type="text" value="<?php echo $this->registro['nome'] ?>" />
                                            </div>
                                        </div><!-- End .form-group  -->

                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="telefone">Telefone:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="telefone" id="telefone" type="text" value="<?php echo $this->registro['telefone'] ?>" />
                                            </div>
                                        </div><!-- End .form-group  -->


                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="cpf">CPF:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="cpf" id="cpf" type="text" value="<?php echo $this->registro['cpf'] ?>" />
                                            </div>
                                        </div><!-- End .form-group  -->

                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="email">E-mail:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="email" id="email" type="text" value="<?php echo $this->registro['email'] ?>" />
                                            </div>
                                        </div><!-- End .form-group  -->

                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="senha">Senha</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="senha" id="senha" type="password" value="" />
                                            </div><!-- End .form-group  -->
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-default toggle">
                                    <!-- Start .panel -->
                                    <div class="panel-heading">
                                        <h4 class="panel-title">Endereço</h4>
                                    </div>
                                    <div class="panel-body">
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="cep">CEP:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="cep" id="cep" type="text" value="<?php echo $this->registro['cep'] ?>" />
                                            </div>
                                        </div><!-- End .form-group  -->

                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="endereco">Endereço:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="endereco" id="endereco" type="text" value="<?php echo $this->registro['endereco'] ?>" />
                                            </div>
                                        </div><!-- End .form-group  -->

                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="bairro">Bairro:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="bairro" id="bairro" type="text" value="<?php echo $this->registro['bairro'] ?>" />
                                            </div>
                                        </div><!-- End .form-group  -->

                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="numero">Número:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="numero" id="numero" type="text" value="<?php echo $this->registro['numero'] ?>" />
                                            </div>
                                        </div><!-- End .form-group  -->

                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="complemento">Complemento:</label>
                                            <div class="col-lg-10">
                                                <input class="form-control" name="complemento" id="complemento" type="text" value="<?php echo $this->registro['complemento'] ?>" />
                                            </div>
                                        </div><!-- End .form-group  -->

                                        <div class="form-group form-group-vertical">
                                            <label class="col-lg-2 col-md-3 control-label" for="id_estado">Estado:</label>
                                            <div class="col-lg-10 col-md-9">
                                                <select class="form-control input-sm" id="id_estado" name="id_estado">
                                                    <option value="">Selecione..</option>
                                                    <?php if ($this->estados->num_rows) : ?>
                                                        <?php foreach ($this->estados->rows as $estado) : ?>
                                                            <option <?php if ($estado['id'] == $this->registro['id_estado']) echo "selected"; ?> value="<?php echo $estado['id']; ?>"><?php echo $estado['estado']; ?></option>
                                                        <?php endforeach; ?>
                                                    <?php endif; ?>
                                                </select>
                                            </div>
                                        </div>


                                        <div class="form-group form-group-vertical">
                                            <label class="col-lg-2 col-md-3 control-label" for="id_cidade">Cidade:</label>
                                            <div class="col-lg-10 col-md-9">
                                                <select class="form-control input-sm" id="id_cidade" name="id_cidade">
                                                    <option value="">Selecione..</option>

                                                </select>
                                            </div>
                                        </div>



                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <?php if ($this->id==""): ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['gravar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning "><span class="s24 typ-s-warning"></span>Você não tem permissão para gravar esta função.</span>
                                        </div>
                                    </div><!-- End .form-group  -->
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="button" class="btn btn-info clickformsubmit">Salvar novo</button>
                                        </div>
                                    </div><!-- End .form-group  -->
                                <?php endif ?>
                            <?php else: ?>
                                <?php if (!$this->permissions[$this->permissao_ref]['editar']): ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <span class="label label-warning"><span class="s24 icomoon-s-warning "></span>Você não tem permissão para editar esta função.</span>
                                        </div>
                                    </div><!-- End .form-group  -->
                                <?php else: ?>
                                    <div class="form-group">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button type="button" class="btn btn-info clickformsubmit">Salvar alterações</button>
                                        </div>
                                    </div><!-- End .form-group  -->
                                <?php endif ?>
                            <?php endif ?>
                        </div><!-- End .row -->
                    </form>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-default toggle panelClose">
                            <!-- Start .panel -->
                            <div class="panel-heading">
                                <h4 class="panel-title"><i class="<?php echo $this->module_icon ?>"></i> Tabela de Pedidos
                                    <label style="position:absolute;right:260px;top:3px;">Busca Completa: <input type="checkbox" id="busca_completa"></label>
                                    <label class="select-all">Selecionar estes <input type="checkbox" id="apagar_todos"></label>
                                </h4>
                            </div>
                            <div class="panel-body">

                                <table cellpadding="0" cellspacing="0" border="0" class="tabletools table table-striped table-bordered" width="100%">
                                    <thead>
                                    <tr>
                                        <th class="tal" width="80">Pedido</th>
                                        <th class="tal" width="110">Vendedor</th>
                                        <th class="tal" width="110">Data</th>
                                        <th class="tal" width="180">Cliente</th>
                                        <th class="tal" width="120">Telefone</th>
                                        <th class="tal" width="120">Cidade</th>
                                        <th class="tal" width="120">Estado</th>
                                        <th class="tal" width="120">Tipo de Pagamento</th>
                                        <th class="tal" width="120">Status do Pedido</th>
                                        <th class="tal" width="120">Valor Total</th>
                                        <th class="tal" width="120">Editando</th>
                                        <th width="100" class="center">Ação</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div><!-- End .row -->
                <?php require_once "layouts/options.phtml"; ?>
                <!-- End contentwrapper -->
            </div>

            <!-- End #content -->


<?php  require_once "layouts/footer.phtml"; ?>

        </div>

<?php  require_once "layouts/plugins.phtml"; ?>

<script src="plugins/tables/dataTables/jquery.dataTables.js"></script>
<script src="plugins/tables/dataTables/dataTables.tableTools.js"></script>
<script src="plugins/tables/dataTables/dataTables.bootstrap.js"></script>
<script src="plugins/tables/dataTables/dataTables.responsive.js"></script>
        <!-- Init plugins only for page -->
        <script type="text/javascript">
            $(document).ready(function(){
                console.log('aqui');


                var date_flag = 0;
                $("#busca_completa").change(function(){
                    if($(this).is(':checked')){
                        //id_limit = 1000;
                        date_flag = 1;
                    }else{
                        //id_limit =  last_order_id - 1000;
                        date_flag = 0;
                    }
                });


                var oTable = $('.tabletools').dataTable( {
                    "bProcessing": true,
                    "bServerSide": true,
                    "sAjaxSource": "order/datatable",

                    "fnServerData": function ( sSource, aoData, fnCallback, oSettings ) {
                        //aoData.push({"name":"id_limit","value":id_limit});
                        aoData.push({"name":"date_flag","value":date_flag},{"name": "id_cliente", "value": <?=$this->id?>});
                        console.log(aoData);
                        oSettings.jqXHR = $.ajax( {
                            "dataType": 'json',
                            "type": "POST",
                            "url": sSource,
                            "data": aoData,
                            "success": fnCallback
                        });
                    },
                    "sDom": "<'row'<'col-lg-6'l><'col-lg-6'f>r>t<'row'<'col-lg-6'i><'col-lg-6'p>>",
                    "aaSorting":[[0,"desc"]],
                    "sPaginationType": "bootstrap",
                    "bJQueryUI": false,
                    "bAutoWidth": false,
                    "iDisplayLength": 100,
                    "oLanguage": {
                        "sProcessing":   "<img src='<?php echo $this->system_path; ?>images/loaders/horizontal/006.gif'><br>Processando...",
                        "sLengthMenu":   "_MENU_",
                        "sZeroRecords":  "Não foram encontrados resultados",
                        "sInfo":         "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                        "sInfoEmpty":    "Mostrando de 0 até 0 de 0 registros",
                        "sInfoFiltered": "(filtrado de _MAX_ registros no total)",
                        "sInfoPostFix":  "",
                        "sSearch":       "<span style='font-size:9px;'>Prefixos: <u>s: Pendente</u> (busca somente por status), <u>v: João</u> (busca somente vendedor), <u>c: João</u> (busca somente cliente)</span> ",
                        "sUrl":          "",
                        "oPaginate": {
                            "sFirst":    "Primeiro",
                            "sPrevious": "Anterior",
                            "sNext":     "Seguinte",
                            "sLast":     "Último"
                        }
                    }
                });

                /*
                 * HABILITA BUSCA APENAS APÓS TECLAR ENTER
                 */
                $(".dataTables_filter input").attr('title', "Tecle ENTER Para Pesquisar");
                $(".dataTables_filter input").unbind();
                $(".dataTables_filter input").keyup( function (e) {
                    if (e.keyCode == 13) {
                        oTable.fnFilter( this.value);
                        $.get('<?php echo $this->system_path.$this->getModule();?>/verificasessao', function(data){
                            if(data == 'login'){
                                window.location.reload();
                            }
                        });
                    }
                });


                $("#cpf").mask("###.###.###-##");
                $("#data_nascimento").mask("##/##/####");
                $(".datepicker").datepicker({});



                $(document).on("change", "#id_estado", function (){
                    var id = $(this).val();
                    $("#id_cidade").load("<?php echo $this->getModule();?>/cidades/?id=" + id + "&cidade=" + <?= $this->registro['id_cidade'] ? $this->registro['id_cidade'] : '0'?>, function () {

                    });
                });

                $("#id_estado").trigger("change");



            });
        </script>
    </body>
</html>
