<?php
    require_once "layouts/headers.phtml";
?>

    <script type="text/javascript">
        var pagina = "<?php echo $this->getModule(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getModule(); ?>";
    </script>
    
    </head>  
    
    
    <body>
<?php  require_once "layouts/header.phtml"; ?>

        <!-- / #header -->
        <div id="wrapper">
        <!-- #wrapper -->

<?php  require_once "layouts/sidebar.phtml"; ?>
            
            <!--Body content-->
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <!--Content wrapper-->
                    <div class="heading">
                        <!--  .heading-->
                        <h3><?php echo $this->module_title; ?></h3>

                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li>
                                <a href="#" class="tip" title="Painel">
                                    <i class="s16 icomoon-icon-screen-2"></i>
                                </a>
                                <span class="divider">
                                    <i class="s16 icomoon-icon-arrow-right-3"></i>
                                </span>
                            </li>
                            <li class="active"><?php echo $this->module_title;?></li>
                        </ul>
                    </div>
                    <!-- End  / heading-->
                    <!-- Start .row -->

                    <div class="row">
                        <div class="col-lg-12">
                            <a href="<?php echo $this->getModule();?>/edit"><button type="button" class="btn btn-default mr5 mb10"><i class="glyphicon glyphicon-plus mr5"></i> Novo registro</button></a>
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="panel panel-default toggle panelClose">
                                <!-- Start .panel -->
                                <div class="panel-heading">
                                    <h4 class="panel-title"><i class="<?php echo $this->module_icon ?>"></i> Tabela de Códigos
                                        <label class="select-all">Selecionar estes <input type="checkbox" id="apagar_todos"></label>
                                    </h4>
                                </div>
                                <div class="panel-body">
                                <?php /* ?>
                                    <table cellpadding="0" cellspacing="0" border="0" class="tabletools table table-striped table-bordered" width="100%">
                                        <thead>
                                            <tr>
                                                <th style="display:none"></th>
                                                <th width="20%" class="tal">Código</th>
                                                <th width="40%" class="tal">Mensagem</th>
                                                <th width="20%" class="tal">Tipo</th>
                                                <th width="10%" class="center">Status</th>
                                                <th style="min-width: 120px" class="center">Ação</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php if ($this->list->num_rows) : ?>
                                                <?php foreach($this->list->rows as $registro):?>
                                                    <tr>
                                                        <td style="display:none"><?php echo $registro['id']; ?></td>
                                                        <td class="tal"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $registro['id']; ?>"><?php echo $registro['codigo'];?></a></td>                                                        
                                                        <td class="tal"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $registro['id']; ?>"><?php echo $registro['mensagem'];?></a></td>
                                                        <td class="tal"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $registro['id']; ?>"><?php if ($registro['porcentagem']) echo "Porcentagem"; else echo "Fixo";?></a></td>
                                                        <td class="center">
                                                            <?php if($registro['stats']==0){ ?>
                                                                <a href="#" class="bt_system_stats" data-permit="<?php echo $this->permissao_ref ?>" data-table="<?php echo $this->table; ?>" data-action="ativar" data-id="<?php echo $registro['id']; ?>"><img src="images/status_vermelho.png" alt="Ativar"></a>
                                                            <?php }else{ ?>
                                                                <a href="#" class="bt_system_stats" data-permit="<?php echo $this->permissao_ref ?>" data-table="<?php echo $this->table; ?>" data-action="desativar" data-id="<?php echo $registro['id']; ?>"><img src="images/status_verde.png" alt="Desativar"></a>
                                                            <?php } ?>
                                                        </td>
                                                        <td class="center">
                                                            <a href="<?php echo $this->getModule()?>/edit/id/<?php echo $registro['id']; ?>"><i class="s12 icomoon-icon-pencil"></i></a>
                                                            <?php if ($this->permissions[$this->permissao_ref]['excluir']): ?>
                                                                <a class="bt_system_delete" data-controller="<?php echo $this->getModule()?>" data-id="<?php echo $registro['id']; ?>" href="#"><i class="s12 icomoon-icon-remove"></i></a>
                                                                <input type="checkbox" id="del_<?php echo $registro['id']; ?>" value="<?php echo $registro['id']; ?>" class="del-this">
                                                            <?php endif ?>
                                                        </td>
                                                    </tr>
                                                <?php endforeach; ?>
                                            <?php endif; ?>
                                        </tbody>
                                    </table>

                                <?php */ ?>

                                    <table cellpadding="0" cellspacing="0" border="0" class="tabletools table table-striped table-bordered" width="100%">
                                        <thead>
                                            <th width="20%" class="tal">Código</th>
                                            <th width="40%" class="tal">Mensagem</th>
                                            <th width="20%" class="tal">Tipo</th>
                                            <th width="10%" class="center">Status</th>
                                            <th style="min-width: 120px" class="center">Ação</th>
                                        </thead>
                                        <tbody>
                                            
                                        </tbody>
                                    </table>

                                </div>
                            </div>
                        </div>
                    </div><!-- End .row -->
                    <?php require_once "layouts/options.phtml"; ?>
                </div>
                <!-- End contentwrapper -->
            </div>
            <!-- End #content -->
            
            
<?php  require_once "layouts/footer.phtml"; ?>
        
        </div>
        
<?php  require_once "layouts/plugins.phtml"; ?>

        <!-- Table plugins -->
        <script src="plugins/tables/dataTables/jquery.dataTables.js"></script>
        <script src="plugins/tables/dataTables/dataTables.tableTools.js"></script>
        <script src="plugins/tables/dataTables/dataTables.bootstrap.js"></script>
        <script src="plugins/tables/dataTables/dataTables.responsive.js"></script>


        <!-- Init plugins only for page -->
        <script type="text/javascript">
            $(document).ready(function(){
        
                var oTable = $('.tabletools').dataTable( {
                    "bProcessing": true,
                    "bServerSide": true,
                    "sAjaxSource": "<?php echo $this->system_path.$this->getModule();?>/datatable",

                    "fnServerData": function ( sSource, aoData, fnCallback, oSettings ) {
                        oSettings.jqXHR = $.ajax( {
                            "dataType": 'json',
                            "type": "POST",
                            "url": sSource,
                            "data": aoData,
                            "success": fnCallback
                        });
                    },
                    "sDom": "<'row'<'col-lg-6'l><'col-lg-6'f>r>t<'row'<'col-lg-6'i><'col-lg-6'p>>",
                    "aaSorting":[[0,"desc"]],
                    "sPaginationType": "bootstrap",
                    "bJQueryUI": false,
                    "bAutoWidth": false,
                    "iDisplayLength": 100,
                    "oLanguage": {
                        "sProcessing":   "<img src='<?php echo $this->system_path; ?>images/loaders/horizontal/006.gif'><br>Processando...",
                        "sLengthMenu":   "_MENU_",
                        "sZeroRecords":  "Não foram encontrados resultados",
                        "sInfo":         "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                        "sInfoEmpty":    "Mostrando de 0 até 0 de 0 registros",
                        "sInfoFiltered": "(filtrado de _MAX_ registros no total)",
                        "sInfoPostFix":  "",
                        "sSearch":       "",
                        "sUrl":          "",
                        "oPaginate": {
                            "sFirst":    "Primeiro",
                            "sPrevious": "Anterior",
                            "sNext":     "Seguinte",
                            "sLast":     "Último"
                        }
                    }                
                });

                /*
                 * HABILITA BUSCA APENAS APÓS TECLAR ENTER
                 */            
                $(".dataTables_filter input").attr('title', "Tecle ENTER Para Pesquisar");
                $(".dataTables_filter input").unbind();
                $(".dataTables_filter input").keyup( function (e) {
                    if (e.keyCode == 13) {
                        oTable.fnFilter( this.value);
                    }
                });
            });
        </script>
    </body>
</html>
