<?php
    require_once "layouts/headers.phtml";
?>


    <script type="text/javascript">
        var pagina = "<?php echo $this->getModule(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getModule(); ?>/save";
        var retorno = "<?php echo $this->retorno; ?>";
    </script>
    
    </head>  
    
    
    <body>
<?php  require_once "layouts/header.phtml"; ?>

        <!-- / #header -->
        <div id="wrapper">
        <!-- #wrapper -->

<?php  require_once "layouts/sidebar.phtml"; ?>
            
            <!--Body content-->
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <!--Content wrapper-->
                    <div class="heading">
                        <!--  .heading-->
                        <h3><?php echo $this->module_title; ?></h3>

                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li>
                                <a href="#" class="tip" title="Painel">
                                    <i class="s16 icomoon-icon-screen-2"></i>
                                </a>
                                <span class="divider">
                                    <i class="s16 icomoon-icon-arrow-right-3"></i>
                                </span>
                            </li>
                            <li class="active"><?php echo $this->module_title;?></li>
                        </ul>
                    </div>
                    <!-- End  / heading-->
                    
                    <div class="row">
                        <div class="col-lg-12">
                            <?php if ($this->permissions[$this->permissao_ref]['gravar']): ?>
                                <a href="#"><button type="button" class="btn btn-default mr5 mb10 btn-gerar-backup"><i class="glyphicon glyphicon-plus mr5"></i> Novo registro</button></a>                                
                                <span class="inf-gerar-backup"></span>
                            <?php endif ?>
                            <div class="marginB10"></div>
                        </div>
                    </div>
                    
                    
                    <!-- Start .row -->
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="panel panel-default toggle panelClose">
                                <!-- Start .panel -->
                                <div class="panel-heading">
                                    <h4 class="panel-title"><i class="<?php echo $this->module_icon ?>"></i> Tabela de Backups</h4>
                                </div>
                                <div class="panel-body">
                                    <table cellpadding="0" cellspacing="0" border="0" class="tabletools table table-striped table-bordered" width="100%">
                                        <thead>
                                            <tr>
                                                <th width="20%" class="tal">Data</th>
                                                <th width="70%" class="tal">Arquivo</th>
                                                <th style="min-width: 120px" class="center">Ação</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php if($this->list->num_rows){ ?>
                                                <?php foreach($this->list->rows as $registro){ 
                                                    $registro['arquivo_rename'] = explode("/",$registro['arquivo']);
                                                    $registro['arquivo_rename'] = end($registro['arquivo_rename']);
                                                    $registro['arquivo_rename'] = explode(".",$registro['arquivo_rename']);
                                                    $registro['arquivo_rename'] = $registro['arquivo_rename'][0];
                                                    ?>
                                                    <tr>
                                                        <td class="tal"><a href="<?php echo $this->getModule(); ?>/get/id/<?php echo $registro['id']; ?>"><?php echo $registro['data']; ?></a></td>
                                                        <td class="tal"><a href="<?php echo $this->getModule(); ?>/get/id/<?php echo $registro['id']; ?>"><?php echo $registro['arquivo_rename']; ?></a></td>
                                                        <td class="center">
                                                            <?php if ($this->permissions[$this->permissao_ref]['excluir']): ?>
                                                                <a href="#" id="<?php echo $registro['id']; ?>" class="del_backup"><span class="icon12 icomoon-icon-remove"></span></a>                                                                
                                                            <?php endif ?>
                                                        </td>
                                                    </tr>
                                                <?php } ?>
                                            <?php } ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>
                <!-- End contentwrapper -->
            </div>
            <!-- End #content -->
            
            
<?php  require_once "layouts/footer.phtml"; ?>
        
        </div>
        
<?php  require_once "layouts/plugins.phtml"; ?>
        <!-- Table plugins -->
        <script src="plugins/tables/dataTables/jquery.dataTables.js"></script>
        <script src="plugins/tables/dataTables/dataTables.tableTools.js"></script>
        <script src="plugins/tables/dataTables/dataTables.bootstrap.js"></script>
        <script src="plugins/tables/dataTables/dataTables.responsive.js"></script>
        <script type="text/javascript">
            $(document).ready(function(){

                //--------------- Data tables ------------------//
                if($('table').hasClass('tabletools')){
                    $('.tabletools').dataTable( {
                        "oLanguage": {
                            "sSearch": "",
                            "sLengthMenu": "<span>_MENU_</span>",
                            "sProcessing":   "Processando...",                    
                            "sZeroRecords":  "Não foram encontrados resultados",
                            "sInfo":         "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                            "sInfoEmpty":    "Mostrando de 0 até 0 de 0 registros",
                            "sInfoFiltered": "(filtrado de _MAX_ registros no total)",
                            "sInfoPostFix":  "",
                            "sUrl":         "",

                            "oPaginate": {
                                "sFirst":    "Primeiro",
                                "sPrevious": "Anterior",
                                "sNext":     "Seguinte",
                                "sLast":     "Último"
                            }
                        },
                        "sDom": "T<'row'<'col-md-6 col-xs-12 'l><'col-md-6 col-xs-12'f>r>t<'row'<'col-md-4 col-xs-12'i><'col-md-8 col-xs-12'p>>",
                        "aaSorting":[[0,"asc"]], "iDisplayLength": 100,
                        tableTools: {
                            "sSwfPath": "http://cdn.datatables.net/tabletools/2.2.2/swf/copy_csv_xls_pdf.swf",
                            "aButtons": [
                          ]
                        }


                    });

                }
                
                $(".btn-gerar-backup").on("click", function(){
                    $(".gera-info").remove();
                    $(".inf-gerar-backup").html("<img alt='' class='gera-info' align='absmiddle' style='padding-left:10px' src='images/loaders/circular/055.gif'/> <scpan class='small gera-info'>Aguarde, estamos gerando novo backup do banco de dados...</span>");
                    $.post( "scripts/cronjob_backups.php", function( data ) {                    
                            if (data.result === true) {
                                window.location.href = "<?php echo $this->getModule();?>";
                            } else {
                                $(".gera-info").remove();
                                $(".inf-gerar-backup").html("<span class='small gera-info' style='padding-left: 10px'><span class='s16 cut-icon-alert'></span> Geração do backup do banco de dados falhou!</span>");
                            }
                        }, "json");
                });

                $(".del_backup").on("click", function() {
                    var id = $(this).attr("id");
                    $(".gera-info").remove();
                    $.post("backup/del/id/" + id, function( data ) {
                        if (data.result == true) {
                            window.location.href = "<?php echo $this->getModule();?>";
                        } else {
                            $(".inf-gerar-backup").html("<span class='small gera-info' style='padding-left: 10px'><span class='s16 cut-icon-alert'></span> Houve uma falha ao tentar apagar o backup do banco de dados!</span>");
                        }
                    }, "json");
                });

            });
        </script>
    </body>
</html>
