<?php
    require_once "layouts/headers.phtml";
?>
    <script type="text/javascript">
        var pagina = "<?php echo $this->getModule(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getModule(); ?>/save";
        var retorno = "<?php echo $this->retorno; ?>";
    </script>
</head>

<body>
    <?php require_once "layouts/header.phtml"; ?>

    <!-- / #header -->
    <div id="wrapper">
    <!-- #wrapper -->

        <?php  require_once "layouts/sidebar.phtml"; ?>

        <!--Body content-->
        <div id="content" class="page-content clearfix">
            <!--Content wrapper-->
            <div class="contentwrapper">
                <!-- .heading -->
                <div class="heading">
                    <h3><?php echo $this->module_title; ?></h3>
                    <ul class="breadcrumb">
                        <li>Você está aqui:</li>
                        <li>
                            <a href="#" class="tip" title="Painel">
                                <i class="s16 icomoon-icon-screen-2"></i>
                            </a>
                            <span class="divider">
                                <i class="s16 icomoon-icon-arrow-right-3"></i>
                            </span>
                        </li>
                        <li>
                            <a class="tip" title="<?php echo $this->module_title; ?>" href="<?php echo $this->module_link;?>">
                                <i class="s16 <?php echo $this->module_icon; ?>"></i>                                    
                            </a>
                        </li>
                        <span class="divider">
                            <i class="s16 icomoon-icon-arrow-right-3"></i>
                        </span>
                        <li class="active">Registro</li>
                    </ul>
                </div>
                <!-- End .heading-->

                <form name="main" enctype="multipart/form-data" method="post" class="form-horizontal group-border">
                    <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
                    <input type="hidden" name="retorno" value="<?php echo $this->retorno; ?>">

                    <!-- Start .row -->
                    <div class="row">
                        <div class="col-lg-12">
                            <!-- Start .panel -->
                            <div class="panel panel-default toggle panelClose">
                                <div class="panel-heading">
                                    <h4 class="panel-title">Transportadora</h4>
                                </div>
                                <!-- Start .panel-body -->
                                <div class="panel-body">

                                    <div class="form-group">
                                        <label class="col-lg-2 control-label" for="nome">Nome:</label>
                                        <div class="col-lg-10">
                                            <input class="form-control" name="nome" id="nome" type="text" value="<?php echo $this->registro['nome']; ?>"/>
                                        </div>
                                    </div><!-- End .form-group  -->

                                </div>
                                <!-- End .panel-body -->
                            </div>
                            <!-- End .panel -->

                            <!-- Start .panel -->
                            <div class="panel panel-default toggle panelClose">
                                <div class="panel-heading">
                                    <h4 class="panel-title">Atendente</h4>
                                </div>
                                <!-- Start .panel-body -->
                                <div class="panel-body">

                                    <div class="form-group">
                                        <label class="col-lg-2 control-label" for="atendente">Nome:</label>
                                        <div class="col-lg-10">
                                            <input class="form-control" name="atendente" id="atendente" type="text" value="<?php echo $this->registro['atendente']; ?>"/>
                                        </div>
                                    </div><!-- End .form-group  -->

                                    <div class="form-group">
                                        <label class="col-lg-2 control-label" for="telefone_atendente">Telefone:</label>
                                        <div class="col-lg-10">
                                            <input class="form-control telefone" name="telefone_atendente" id="telefone_atendente" type="text" value="<?php echo $this->registro['telefone_atendente']; ?>"/>
                                        </div>
                                    </div><!-- End .form-group  -->

                                    <div class="form-group">
                                        <label class="col-lg-2 control-label" for="email_atendente">Email:</label>
                                        <div class="col-lg-10">
                                            <input class="form-control" name="email_atendente" id="email_atendente" type="text" value="<?php echo $this->registro['email_atendente']; ?>"/>
                                        </div>
                                    </div><!-- End .form-group  -->

                                </div>
                                <!-- End .panel-body -->
                            </div>
                            <!-- End .panel -->

                            <!-- Start .panel -->
                            <div class="panel panel-default toggle panelClose">
                                <div class="panel-heading">
                                    <h4 class="panel-title">Gerente</h4>
                                </div>
                                <!-- Start .panel-body -->
                                <div class="panel-body">

                                    <div class="form-group">
                                        <label class="col-lg-2 control-label" for="gerente">Nome:</label>
                                        <div class="col-lg-10">
                                            <input class="form-control" name="gerente" id="gerente" type="text" value="<?php echo $this->registro['gerente']; ?>"/>
                                        </div>
                                    </div><!-- End .form-group  -->

                                    <div class="form-group">
                                        <label class="col-lg-2 control-label" for="telefone_gerente">Telefone:</label>
                                        <div class="col-lg-10">
                                            <input class="form-control telefone" name="telefone_gerente" id="telefone_gerente" type="text" value="<?php echo $this->registro['telefone_gerente']; ?>"/>
                                        </div>
                                    </div><!-- End .form-group  -->

                                    <div class="form-group">
                                        <label class="col-lg-2 control-label" for="email_gerente">Email:</label>
                                        <div class="col-lg-10">
                                            <input class="form-control" name="email_gerente" id="email_gerente" type="text" value="<?php echo $this->registro['email_gerente']; ?>"/>
                                        </div>
                                    </div><!-- End .form-group  -->

                                </div>
                                <!-- End .panel-body -->
                            </div>
                            <!-- End .panel -->
                        </div>
                    </div>
                    <!-- End .row -->

                    <!-- Start .row -->
                    <div class="row">
                    <?php if ($this->id == ""): ?>
                        <?php if (!$this->permissions[$this->permissao_ref]['gravar']): ?>
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <span class="label label-warning "><span class="s24 typ-s-warning"></span>Você não tem permissão para gravar esta função.</span>
                                </div>
                            </div><!-- End .form-group  -->   
                        <?php else: ?>
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <button type="button" class="btn btn-info clickformsubmit">Salvar novo</button>
                                </div>
                            </div><!-- End .form-group  -->
                        <?php endif ?>
                    <?php else: ?>
                        <?php if (!$this->permissions[$this->permissao_ref]['editar']): ?>
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <span class="label label-warning"><span class="s24 icomoon-s-warning "></span>Você não tem permissão para editar esta função.</span>
                                </div>
                            </div><!-- End .form-group  -->   
                        <?php else: ?>
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <button type="button" class="btn btn-info clickformsubmit">Salvar alterações</button>
                                </div>
                            </div><!-- End .form-group  -->
                        <?php endif ?>
                    <?php endif ?>
                    </div>
                    <!-- End .row -->
                </form>

                <?php require_once "layouts/options.phtml"; ?>
            </div>
            <!-- End contentwrapper -->
        </div>
        <!-- End #content -->

        <?php  require_once "layouts/footer.phtml"; ?>
    </div>

    <?php  require_once "layouts/plugins.phtml"; ?>

    <!-- Init plugins only for page -->
    <!-- <script type="text/javascript">
        $(document).ready(function() {
            //
        });
    </script> -->

</body>
</html>
