<?php
    require_once "layouts/headers.phtml";
?>
    <script type="text/javascript">
        var pagina = "<?php echo $this->getModule(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
        var controller = "<?php echo $this->getModule(); ?>";
    </script>
</head>

<body>
    <?php require_once "layouts/header.phtml"; ?>

    <!-- / #header -->
    <div id="wrapper">
    <!-- #wrapper -->

        <?php  require_once "layouts/sidebar.phtml"; ?>

        <!--Body content-->
        <div id="content" class="page-content clearfix">
            <!--Content wrapper-->
            <div class="contentwrapper">
                <!-- .heading -->
                <div class="heading">
                    <h3><?php echo $this->module_title; ?></h3>
                    <ul class="breadcrumb">
                        <li>Você está aqui:</li>
                        <li>
                            <a href="#" class="tip" title="Painel">
                                <i class="s16 icomoon-icon-screen-2"></i>
                            </a>
                            <span class="divider">
                                <i class="s16 icomoon-icon-arrow-right-3"></i>
                            </span>
                        </li>
                        <li class="active"><?php echo $this->module_title;?></li>
                    </ul>
                </div>
                <!-- End .heading-->
                <!-- Start .row -->
                <div class="row">
                    <div class="col-lg-12">
                        <a href="<?php echo $this->getModule();?>/edit"><button type="button" class="btn btn-default mr5 mb10"><i class="glyphicon glyphicon-plus mr5"></i> Novo registro</button></a>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <!-- Start .panel -->
                        <div class="panel panel-default toggle panelClose">
                            <div class="panel-heading">
                                <h4 class="panel-title"><i class="<?php echo $this->module_icon ?>"></i> Tabela de Transportadoras
                                    <label class="select-all">Selecionar estes <input type="checkbox" id="apagar_todos"></label>
                                </h4>
                            </div>
                            <!-- Start .panel-body -->
                            <div class="panel-body">
                                <table width="100%" cellpadding="0" cellspacing="0" border="0" class="tabletools table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th width="17%" class="tal">Nome</th>
                                            <th width="15%" class="tal">Atendente</th>
                                            <th width="13%" class="tal">Telefone</th>
                                            <th width="10%" class="tal">Email</th>
                                            <th width="15%" class="tal">Gerente</th>
                                            <th width="13%" class="tal">Telefone</th>
                                            <th width="10%" class="tal">Email</th>
                                            <th style="min-width: 120px" class="center">Ação</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php if ($this->list && $this->list->num_rows) :?>
                                        <?php foreach ($this->list->rows as $registro) :?>
                                            <tr>
                                                <td class="tal"><a href="<?php echo $this->getModule()?>/edit/id/<?php echo $registro['id']; ?>"><?php echo $registro['nome']; ?></a></td>
                                                <td class="tal"><?php echo $registro['atendente']; ?></td>
                                                <td class="tal"><?php echo $registro['telefone_atendente']; ?></td>
                                                <td class="tal"><?php echo $registro['email_atendente']; ?></td>
                                                <td class="tal"><?php echo $registro['gerente']; ?></td>
                                                <td class="tal"><?php echo $registro['telefone_gerente']; ?></td>
                                                <td class="tal"><?php echo $registro['email_gerente']; ?></td>
                                                <td class="center">
                                                    <a href="<?php echo $this->getModule()?>/edit/id/<?php echo $registro['id']; ?>"><i class="s12 icomoon-icon-pencil"></i></a>
                                                    <?php if ($this->permissions[$this->permissao_ref]['excluir']) :?>
                                                        <a class="bt_system_delete" data-controller="<?php echo $this->getModule()?>" data-id="<?php echo $registro['id']; ?>" href="#"><i class="s12 icomoon-icon-remove"></i></a>
                                                        <input type="checkbox" id="del_<?php echo $registro['id']; ?>" value="<?php echo $registro['id']; ?>" class="del-this">
                                                    <?php endif; ?>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                        <?php endif; ?>
                                    </tbody>
                                </table>

                            </div>
                            <!-- End .panel-body -->
                        </div>
                        <!-- End .panel -->
                    </div>
                </div>
                <!-- End .row -->
                <?php require_once "layouts/options.phtml"; ?>
            </div>
            <!-- End contentwrapper -->
        </div>
        <!-- End #content -->

        <?php  require_once "layouts/footer.phtml"; ?>
    
    </div>

    <?php  require_once "layouts/plugins.phtml"; ?>

    <!-- Table plugins -->
    <script src="plugins/tables/dataTables/jquery.dataTables.js"></script>
    <script src="plugins/tables/dataTables/dataTables.tableTools.js"></script>
    <script src="plugins/tables/dataTables/dataTables.bootstrap.js"></script>
    <script src="plugins/tables/dataTables/dataTables.responsive.js"></script>


    <!-- Init plugins only for page -->
    <script type="text/javascript">
        $(document).ready(function(){

            //--------------- Data tables ------------------//
            if($('table').hasClass('tabletools')){
                $('.tabletools').dataTable( {
                    "oLanguage": {
                        "sSearch": "",
                        "sLengthMenu": "<span>_MENU_</span>",
                        "sProcessing":   "Processando...",                    
                        "sZeroRecords":  "Não foram encontrados resultados",
                        "sInfo":         "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                        "sInfoEmpty":    "Mostrando de 0 até 0 de 0 registros",
                        "sInfoFiltered": "(filtrado de _MAX_ registros no total)",
                        "sInfoPostFix":  "",
                        "sUrl":         "",

                        "oPaginate": {
                            "sFirst":    "Primeiro",
                            "sPrevious": "Anterior",
                            "sNext":     "Seguinte",
                            "sLast":     "Último"
                        }
                    },
                    "sDom": "T<'row'<'col-md-6 col-xs-12 'l><'col-md-6 col-xs-12'f>r>t<'row'<'col-md-4 col-xs-12'i><'col-md-8 col-xs-12'p>>",
                    "aaSorting":[[0,"asc"]], "iDisplayLength": 100,
                    tableTools: {
                        "sSwfPath": "http://cdn.datatables.net/tabletools/2.2.2/swf/copy_csv_xls_pdf.swf",
                        "aButtons": [
                        ]
                    }


                });

            }

        });
    </script>

</body>
</html>
