<?php
    require_once "layouts/headers.phtml";

?>

    <script type="text/javascript">
        var pagina = "<?php echo $this->getModule(); ?>";
        var permissao = "<?php echo $this->permissao_ref; ?>";
    </script>


<style>
    /* Checkbox de mostrar orçamentos completos (ganho e perda) */


    /* Cores dos status */
    [data-key="ganho"] {
        color: #00a736;
        font-weight: bold;
    }
    [data-key="orcamento"] {
        color: #f4be51;
        font-weight: bold;
    }

    [data-key="perda"] {
        color: #ff2d38;
        font-weight: bold;
    }

    [data-key="venda"] {
        color: silver;
        font-weight: bold;
    }


    .svg-map {
        width: 450px;
        float: left;
    }
    /*#svg-map path { fill:#0094d9 }*/
    .svg-map text { fill:#fff; font:12px Arial-BoldMT, sans-serif; cursor:pointer }
    .svg-map text.price { display: none; }
    .svg-map a{ text-decoration:none }
    .svg-map a:hover { cursor:pointer; text-decoration:none }
    .svg-map a:hover path{ fill:#003399 !important }
    .svg-map a text.price { display: block; fill:#fff; font:12px Arial-BoldMT, sans-serif; cursor:pointer }
    .svg-map .circle { fill:#66ccff }
    .svg-map a:hover .circle { fill:#003399 !important; cursor:pointer }

    .mapa_brasil {
        width: 100%; 
        float: left;
    }
    .painel_dados {
        width: 200px;
        height: 60px;
        float: left;
        margin-left: -100px;
    }
    .painel_dados .valor {
        font-size: 22px;
    }
    .painel_dados .estado {
        font-size: 18px;
    }

</style>
    </head>


    <body>
<?php  require_once "layouts/header.phtml"; ?>

        <!-- / #header -->
        <div id="wrapper">
        <!-- #wrapper -->

<?php  require_once "layouts/sidebar.phtml"; ?>

            <!--Body content-->
            <div id="content" class="page-content clearfix">
                <div class="contentwrapper">
                    <div class="heading">
                        <!--  .heading-->
                        <h3><?php echo $this->module_title; ?></h3>

                        <ul class="breadcrumb">
                            <li>Você está aqui:</li>
                            <li>
                                <a href="#" class="tip" title="voltar para o painel">
                                    <i class="s16 icomoon-icon-screen-2"></i>
                                </a>
                                <span class="divider">
                                    <i class="s16 icomoon-icon-arrow-right-3"></i>
                                </span>
                            </li>
                            <li class="active">Painel</li>
                        </ul>
                    </div>
                    <!-- End  / heading-->
                    <div class="row">
                        <div class="col-md-12">
                            <div class="panel panel-default">
                                <!-- Start .panel -->
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <i class="icomoon-icon-stats-up"></i> Escolha o período
                                        <input class="datepicker box-header-date de" name="periodo_de" type="text" placeholder="De: " value="<?php echo date("d/m/Y", strtotime($_SESSION['periodo_de'])) ?>">
                                        <input class="datepicker box-header-date ate" name="periodo_ate" type="text" placeholder="Até: " value="<?php echo date("d/m/Y", strtotime($_SESSION['periodo_ate'])) ?>">
                                        <button class="box-header-date filtrar_periodo">OK</button>
                                    </h4>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-2 col-xs-6">
                            <!-- col-md-3 start here -->
                            <a href="#" class="chartShortcuts">
                                <span class="default" style="color:#4a4af8;">Pedidos Realizados: <br>
                                <?php echo $this->pedidos_realizados['quantidade'] ?> (R$ <?php echo number_format($this->pedidos_realizados['total'], 2, ',', '.'); ?>)</span>
                            </a>
                        </div>
                        <div class="col-sm-2 col-xs-6">
                            <!-- col-md-3 start here -->
                            <a href="#" class="chartShortcuts">
                                <span class="default" style="color:#ffad06;">Pedidos Pendentes: <br>
                                <?php echo $this->pedidos_pendentes['quantidade'] ?> (R$ <?php echo number_format($this->pedidos_pendentes['total'], 2, ',', '.'); ?>)</span>
                            </a>
                        </div>
                        <div class="col-sm-2 col-xs-6">
                            <!-- col-md-3 start here -->
                            <a href="#" class="chartShortcuts">
                                <span class="default" style="color:#ff0303;">Pedidos Cancelados: <br>
                                <?php echo $this->pedidos_cancelados['quantidade'] ?> (R$ <?php echo number_format($this->pedidos_cancelados['total'], 2, ',', '.'); ?>)</span>
                            </a>
                        </div>
                        <div class="col-sm-2 col-xs-6">
                            <!-- col-md-3 start here -->
                            <a href="#" class="chartShortcuts">
                                <span class="default" style="color:#00aa20;">Pedidos Faturados: <br>
                                <?php echo $this->pedidos_faturados['quantidade'] ?> (R$ <?php echo number_format($this->pedidos_faturados['total'], 2, ',', '.'); ?>)</span>
                            </a>
                        </div>
                        <div class="col-sm-2 col-xs-6">
                            <!-- col-md-3 start here -->
                            <a href="#" class="chartShortcuts">
                                <span class="default" style="color:#0040ff;">Faturamento Real: <br>
                                R$ <?php echo number_format(($this->pedidos_faturados['total']-$this->bonificacoes['total']), 2, ',', '.'); ?></span>
                            </a>
                        </div>
                        <div class="col-sm-2 col-xs-6">
                            <!-- col-md-3 start here -->
                            <a href="#" class="chartShortcuts">
                                <span class="default" style="color:#ff0362;">Cupons: <br>
                                R$ <?php echo number_format($this->pedidos_faturados['total_cupons'], 2, ',', '.'); ?> (<?php
                                 if($this->pedidos_faturados['total_cupons'] && $this->pedidos_faturados['total']) echo number_format($this->pedidos_faturados['total_cupons'] / ($this->pedidos_faturados['total']-$this->bonificacoes['total']) * 100, 2, ',', '.') ?>%)</span>
                            </a>
                        </div>
                    </div>
                    <!--Content wrapper-->
                    <div class="row">
                        <div class="col-lg-12"><br><strong>Os gráficos abaixo NÃO contabilizam pedidos com o status: Pendente, Pagamento NÃO AUTORIZADO, Cancelados, Aguargando Pagamentos e Crédito Transferido</strong> <br><br> </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="panel panel-default toggle panelClose">
                                <!-- Start .panel -->
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <i class="icomoon-icon-stats-up"></i> Mapa
                                    </h4>
                                    <div class="pull-right" style="margin-right: 70px;margin-top: 4px">
                                        <select name="tipo_cliente_mapa" class="tipo_cliente_mapa form-control input-sm">
                                            <option value="todos">Todos</option>
                                                <?php foreach ($this->charts_tipo_cliente as $tipo) : ?>
                                                    <option <?php if ($tipo['tipo_cliente'] == $this->tipo_cliente_mapa) {
                                                        echo "selected";
                                                    } ?> value="<?php echo $tipo['tipo_cliente']; ?>"><?php echo $tipo['tipo_cliente']; ?></option>
                                                <?php endforeach; ?>
                                        </select>
                                    </div>

                                </div>
                                <div class="panel-body">
                                    <div class="col-xs-6">
                                        <div class="mapa_brasil">
                                            <svg version="1.1" class="svg-map" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="450px" height="460px" viewBox="0 0 450 460" enable-background="new 0 0 450 460" xml:space="preserve">
                                                <g>
                                                    <?php echo $this->chart_faturamento_mapa; ?>
                                                </g>
                                            </svg>
                                            <div class="painel_dados">
                                                <div class="estado"></div>
                                                <div class="valor"></div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-xs-6">
                                        <div class="mapa_brasil">
                                            <svg version="1.1" class="svg-map" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="450px" height="460px" viewBox="0 0 450 460" enable-background="new 0 0 450 460" xml:space="preserve">
                                                <g>
                                                    <?php echo $this->chart_clientes_mapa; ?>
                                                </g>
                                            </svg>
                                            <div class="painel_dados">
                                                <div class="estado"></div>
                                                <div class="valor"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div><!-- End .row -->

                    <div class="row">
                        <div class="col-lg-12">
                            <div class="panel panel-default chart">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <i class="s16 icomoon-icon-bars"></i>
                                        <span>Faturamento por categoria de produto (R$)</span>
                                    </h4>
                                </div>
                                <div class="panel-body">
                                    <div class="charts_faturamento_categoria" style="height: 330px;width:100%;">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="row">
                        <div class="col-lg-12">
                            <div class="panel panel-default chart toggle">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <i class="s16 icomoon-icon-bars"></i>
                                        <span>Quantidade por categoria de produto</span>
                                    </h4>
                                </div>
                                <div class="panel-body">
                                    <div class="charts_quantidade_categoria" style="height: 330px;width:100%;">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-4">
                            <div class="panel panel-default chart">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <i class="s16 icomoon-icon-bars"></i>
                                        <span>Vendas por Vendedor</span>
                                    </h4>
                                </div>
                                <div class="panel-body">
                                    <div class="charts_vendas_vendedor" style="height: 230px;width:100%;">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="panel panel-default chart">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <i class="s16 icomoon-icon-bars"></i>
                                        <span>Pedidos (Aguardando pós vendas)</span>
                                    </h4>
                                </div>
                                <div class="panel-body">
                                    <div class="charts_vendedor_entregue" style="height: 230px;width:100%;">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="panel panel-default chart">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <i class="s16 icomoon-icon-bars"></i>
                                        <span>Pedidos Pendentes por Vendedor</span>
                                    </h4>
                                </div>
                                <div class="panel-body">
                                    <div class="charts_vendedor_pendente" style="height: 230px;width:100%;">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <?php

                            $marketing_financeiro = 0;
                            $marketing_por_vendas = 0;
                            if(isset($this->charts_marketing_financeiro_meses_anteriores)){
                                foreach ($this->charts_marketing_financeiro_meses_anteriores as $key => $value) {
                                    $marketing_financeiro = $marketing_financeiro+$value['total'];
                                    $marketing_por_vendas = $marketing_financeiro / $this->pedidos_faturados_6meses['quantidade'];
                                }
                            }

                            $ticket_medio_clubes = 0;
                            $ticket_medio_home = 0;
                            $ticket_medio_cassino = 0;
                            foreach ($this->charts_tipo_cliente_meses_anteriores as $key => $value) {
                                if($value['tipo_cliente'] == 'Home Game') $ticket_medio_home = $value['total']/$value['quantidade'];
                                if($value['tipo_cliente'] == 'Clube de Poker') $ticket_medio_clubes = $value['total']/$value['quantidade'];
                                if($value['tipo_cliente'] == 'Cassino Temático') $ticket_medio_cassino = $value['total']/$value['quantidade'];
                            }                            

                        ?>
                        <div class="col-md-3 col-md-3 col-sm-3 col-xs-6">
                            <!-- col-md-3 start here -->
                            <a href="#" class="chartShortcuts">
                                <span class="default" style="color:#ffad06;">Custo de Vendas (6 meses): <br>
                                    <?php /* ?>
                                <?php echo $this->pedidos_realizados['quantidade'] ?> (R$ <?php echo number_format($marketing_por_vendas, 2, ',', '.'); ?>)</span>  */?>

                                R$ <?php echo number_format($marketing_por_vendas, 2, ',', '.'); ?></span>
                            </a>
                        </div>
                        <div class="col-md-3 col-md-3 col-sm-3 col-xs-6">
                            <!-- col-md-3 start here -->
                            <a href="#" class="chartShortcuts">
                                <span class="default" style="color:#4a4af8;">Ticket médio Clubes (6 meses): <br>
                                <?php
                                ?>
                                R$ <?php echo number_format($ticket_medio_clubes, 2, ',', '.'); ?></span>
                            </a>
                        </div>
                        <div class="col-md-3 col-md-3 col-sm-3 col-xs-6">
                            <!-- col-md-3 start here -->
                            <a href="#" class="chartShortcuts">
                                <span class="default" style="color:#00aa20;">Ticket médio Home Game (6 meses): <br>
                                R$ <?php echo number_format($ticket_medio_home, 2, ',', '.'); ?></span>
                            </a>
                        </div>
                        <div class="col-md-3 col-md-3 col-sm-3 col-xs-6">
                            <!-- col-md-3 start here -->
                            <a href="#" class="chartShortcuts">
                                <span class="default" style="color:#ff0303;">Ticket médio Cassinos (6 meses): <br>
                                R$ <?php echo number_format($ticket_medio_cassino, 2, ',', '.'); ?></span>
                            </a>
                        </div>
                    </div>

                    <div class="row">
                        <?php

                            $marketing_financeiro = 0;
                            $marketing_por_vendas = 0;
                            if(isset($this->charts_marketing_financeiro)){
                                foreach ($this->charts_marketing_financeiro as $key => $value) {
                                    $marketing_financeiro = $marketing_financeiro+$value['total'];
                                    $marketing_por_vendas = $marketing_financeiro / $this->pedidos_faturados['quantidade'];
                                }
                            }

                            $ticket_medio_clubes = 0;
                            $ticket_medio_home = 0;
                            $ticket_medio_cassino = 0;
                            if(isset($this->charts_tipo_cliente)){
                                foreach ($this->charts_tipo_cliente as $key => $value) {
                                    if($value['tipo_cliente'] == 'Home Game') $ticket_medio_home = $value['total']/$value['quantidade'];
                                    if($value['tipo_cliente'] == 'Clube de Poker') $ticket_medio_clubes = $value['total']/$value['quantidade'];
                                    if($value['tipo_cliente'] == 'Cassino Temático') $ticket_medio_cassino = $value['total']/$value['quantidade'];
                                }
                            }

                            

                        ?>
                        <div class="col-md-3 col-md-3 col-sm-3 col-xs-6">
                            <!-- col-md-3 start here -->
                            <a href="#" class="chartShortcuts">
                                <span class="default" style="color:#ffad06;">Custo de Vendas: <br>
                                    <?php /* ?>
                                <?php echo $this->pedidos_realizados['quantidade'] ?> (R$ <?php echo number_format($marketing_por_vendas, 2, ',', '.'); ?>)</span>  */?>

                                R$ <?php echo number_format($marketing_por_vendas, 2, ',', '.'); ?></span>
                            </a>
                        </div>
                        <div class="col-md-3 col-md-3 col-sm-3 col-xs-6">
                            <!-- col-md-3 start here -->
                            <a href="#" class="chartShortcuts">
                                <span class="default" style="color:#4a4af8;">Ticket médio Clubes: <br>
                                <?php
                                ?>
                                R$ <?php echo number_format($ticket_medio_clubes, 2, ',', '.'); ?></span>
                            </a>
                        </div>
                        <div class="col-md-3 col-md-3 col-sm-3 col-xs-6">
                            <!-- col-md-3 start here -->
                            <a href="#" class="chartShortcuts">
                                <span class="default" style="color:#00aa20;">Ticket médio Home Game: <br>
                                R$ <?php echo number_format($ticket_medio_home, 2, ',', '.'); ?></span>
                            </a>
                        </div>
                        <div class="col-md-3 col-md-3 col-sm-3 col-xs-6">
                            <!-- col-md-3 start here -->
                            <a href="#" class="chartShortcuts">
                                <span class="default" style="color:#ff0303;">Ticket médio Cassinos: <br>
                                R$ <?php echo number_format($ticket_medio_cassino, 2, ',', '.'); ?></span>
                            </a>
                        </div>
                    </div>

                    <div class="row"></div>

                    <div class="row">
                        <div class="col-lg-6">
                            <div class="panel panel-default chart">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <i class="s16 icomoon-icon-bars"></i>
                                        <span>Marketing</span>
                                    </h4>
                                </div>
                                <div class="panel-body">
                                    <div class="charts_faturamento_marketing" style="height: 240px;width:100%;">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="panel panel-default chart">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <i class="s16 icomoon-icon-bars"></i>
                                        <span>Pedidos por Tipo de Cliente (R$)</span>
                                    </h4>
                                </div>
                                <div class="panel-body">
                                    <div class="charts_tipo_cliente" style="height: 240px;width:100%;">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="panel panel-default toggle panelClose">
                                <!-- Start .panel -->
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <i class="icomoon-icon-stats-up"></i> Faturamento por data do pedido (R$)
                                    </h4>

                                </div>
                                <div class="panel-body">
                                    <div class="vital-stats">
                                        <!-- Vital stats -->
                                        <div class="faturamento_dia" style="height: 230px;width:100%;margin-top:15px; margin-bottom:15px;"></div>
                                    </div>
                                    <!-- / Vital stats -->
                                </div>

                            </div>
                        </div>
                    </div><!-- End .row -->

                    <div class="row">
                        <div class="col-md-12">
                            <div class="panel panel-default toggle panelClose">
                                <!-- Start .panel -->
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <i class="icomoon-icon-stats-up"></i> Pedidos
                                    </h4>
                                </div>
                                <div class="panel-body">
                                    <div class="vital-stats">
                                        <!-- Vital stats -->
                                        <div class="vendas_dia" style="height: 230px;width:100%;margin-top:15px; margin-bottom:15px;"></div>
                                    </div>
                                    <!-- / Vital stats -->
                                </div>

                            </div>
                        </div>
                    </div><!-- End .row -->
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="panel panel-default chart">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <i class="s16 icomoon-icon-bars"></i>
                                        <span>Origem de pedidos</span>
                                    </h4>
                                </div>
                                <div class="panel-body">
                                    <div class="charts_origem_pedido" style="height: 240px;width:100%;">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="panel panel-default chart">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <i class="s16 icomoon-icon-bars"></i>
                                        <span>Origem de contato</span>
                                    </h4>
                                </div>
                                <div class="panel-body">
                                    <div class="charts_origem_contato" style="height: 240px;width:100%;">
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="panel panel-default toggle panelClose">
                                <!-- Start .panel -->
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <i class="icomoon-icon-stats-up"></i> Ponto de Contato
                                    </h4>
                                    <div class="pull-right" style="margin-right: 70px;margin-top: 4px">
                                        <select name="id_vendedor" class="vendedor form-control input-sm">
                                            <option value="todos">Todos</option>
                                            <?php if ($this->users->num_rows) : ?>
                                                <?php foreach ($this->users->rows as $user) : ?>
                                                    <option <?php if ($user['id'] == $this->id_vendedor) {
                                                        echo "selected";
                                                    } ?> value="<?php echo $user['id']; ?>"><?php echo $user['nome']; ?></option>
                                                <?php endforeach; ?>
                                            <?php endif; ?>
                                        </select>
                                    </div>

                                </div>
                                <div class="panel-body">
                                    <div class="vital-stats">
                                        <!-- Vital stats -->
                                        <div class="ponto_cotato" style="height: 230px;width:100%;margin-top:15px; margin-bottom:15px;"></div>
                                    </div>
                                    <!-- / Vital stats -->
                                </div>

                            </div>
                        </div>
                    </div><!-- End .row -->

                    <div class="row">


                      
                        <div class="col-lg-8">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th><!-- Nomes dos vendedores--></th>
                                    <th class="tal" data-key="orcamento">Orçamento</th>
                                    <th class="tal" data-key="perda">Perdidos</th>
                                    <th class="tal" data-key="ganho">Ganhos</th>
                                    <th class="tal" data-key="venda">Venda</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($this->totais_pedidos as $key => $total): ?>
                                <?php
                                    $perda =  isset($total['perda']['quantidade']) ? $total['perda']['quantidade']: 0;
                                    $ganho =  isset($total['ganho']['quantidade']) ? $total['ganho']['quantidade'] : 0;
                                    $quantidade = isset($total['orcamento']['quantidade']) ? $total['orcamento']['quantidade']: 0;
                                    $totais = $perda + $ganho + $quantidade;
                                    ?>
                                    <tr>
                                        <td class="tal col-sm-2"><?= $key ?></td>
                                        <td class="tal col-sm-3" data-key="orcamento"> <?= isset($total['orcamento']['quantidade'] ) ? $total['orcamento']['quantidade'] : 0 ?>  (<?= (isset($total['orcamento']['quantidade']) and $total['orcamento']['quantidade']) > 0 ? number_format(($total['orcamento']['quantidade'] / $totais * 100),0) : 0 ?>%) - R$ <?= $this->formataMoedaShow(isset($total['orcamento']['valor']) ? $total['orcamento']['valor'] : 0) ?></td>
                                        <td class="tal col-sm-3" data-key="perda"> <?= isset($total['perda']['quantidade']) ? $total['perda']['quantidade'] : 0 ?>  (<?=  (isset($total['perda']['quantidade']) and $total['perda']['quantidade']) > 0 ? number_format(($total['perda']['quantidade'] / $totais * 100),0) : 0?>%) - R$ <?= $this->formataMoedaShow(isset($total['perda']['valor']) ? $total['perda']['valor'] : 0) ?></td>
                                        <td class="tal col-sm-3" data-key="ganho"> <?= isset($total['ganho']['quantidade']) ? $total['ganho']['quantidade'] : 0 ?>  (<?=  (isset($total['ganho']['quantidade']) and $total['ganho']['quantidade']) > 0 ? number_format(($total['ganho']['quantidade'] / $totais * 100),0) : 0?> %) - R$ <?= $this->formataMoedaShow(isset($total['ganho']['valor']) ? $total['ganho']['valor'] : 0) ?></td>
                                        <td class="tal col-sm-1" data-key="venda"> <?= (isset($total['ganho']['quantidade']) and $total['total_dias']) > 0 ? round($total['total_dias'] /$total['ganho']['quantidade']) . ' dia(s)' : 0 . ' dia(s)' ?></td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>

                            </table>
                        </div>
                        <div class="col-lg-4">
                            <div class="panel panel-default chart">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <i class="s16 icomoon-icon-bars"></i>
                                        <span>Motivos de Perda</span>
                                    </h4>
                                </div>
                                <div class="panel-body">
                                    <div class="charts_motivo_perda" style="height: 240px;width:100%;">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <!-- End contentwrapper -->
            </div>
            <!-- End #content -->


<?php  require_once "layouts/footer.phtml"; ?>

        </div>

<?php  require_once "layouts/plugins.phtml"; ?>

        <!-- Table plugins -->
        <script src="plugins/tables/dataTables/jquery.dataTables.js"></script>
        <script src="plugins/tables/dataTables/dataTables.tableTools.js"></script>
        <script src="plugins/tables/dataTables/dataTables.bootstrap.js"></script>
        <script src="plugins/tables/dataTables/dataTables.responsive.js"></script>

        <!-- Charts plugins -->
        <script src="plugins/charts/flot/jquery.flot.custom.js"></script>
        <script src="plugins/charts/flot/jquery.flot.pie.js"></script>
        <script src="plugins/charts/flot/jquery.flot.resize.js"></script>
        <script src="plugins/charts/flot/jquery.flot.time.js"></script>
        <script src="plugins/charts/flot/jquery.flot.orderBars.js"></script>
        <script src="plugins/charts/flot/jquery.flot.tooltip.min.js"></script>

        <script type="text/javascript" src="plugins/misc/fullcalendar/fullcalendar.min.js"></script><!-- Calendar plugin -->

        <!-- Init plugins only for page -->
        <script type="text/javascript">
            var chartColours = ['#88bbc8', '#ed7a53', '#9FC569', '#5a8022', '#2c7282', '#bbdce3', '#9a3b1b'];
            $(document).ready(function(){

                $(".datepicker").mask("##/##/####");
                $(".datepicker").datepicker({});

                $(".svg-map a").hover(function(e){
                    e.preventDefault();
                    $(this).parents(".mapa_brasil").find(".painel_dados .valor").text($(this).attr("data-valor"));
                    $(this).parents(".mapa_brasil").find(".painel_dados .estado").text($(this).attr("data-estado"));
                    console.log("Estado: "+$(this).attr("data-estado")+" Valor: "+$(this).attr("data-valor"));
                });;

                $("button.filtrar_periodo").on("click", function(){

                    var periodo_de = $("input[name='periodo_de']").val();
                    var periodo_ate = $("input[name='periodo_ate']").val();
                    var vendedor =  $('select[name="id_vendedor"] option:selected').val();
                    var tipo_cliente = $('select[name="tipo_cliente_mapa"] option:selected').val();

                    var de = periodo_de.split("/");
                    var ate = periodo_ate.split("/");

                    de = de[2] + '-' + de[1] + '-' + de[0];
                    ate = ate[2] + '-' + ate[1] + '-' + ate[0];

                    if (ate < de) {
                        alert('A data final não pode ser menor que a data inicial!');
                    } else {
                        if (periodo_de.length && periodo_ate.length){
                            window.location.href = system_path+"dashboard?de="+de+"&ate="+ate+"&id_vendedor="+vendedor+"&tipo_cliente="+tipo_cliente;
                        }
                    }

                });

                $('body').on('change', 'select.vendedor,select.tipo_cliente_mapa', function () {

                    $("button.filtrar_periodo").click()
                });

                <?php if(isset($this->charts_vendas_vendedor)){ ?>

                    $(function () {

                        var data = [];
                        var ticks = [];
                        <?php foreach ($this->charts_vendas_vendedor as $key => $value) { ?>
                            ticks.push([<?php echo $key; ?>,"<?php echo $this->charts_vendas_vendedor[$key]['vendedor'] ?>"]);
                            data.push([<?php echo $key; ?>,<?php echo $this->charts_vendas_vendedor[$key]['total'] ?>]);
                        <?php } ?>

                        //var dataset = [{'data':data}];
                        dataset = [];
                        data.forEach(function(val, i){
                            dataset.push({"label":ticks[i][1]+" (R$ "+formatMoney(val[1])+")","data": [val]});
                        });

                        var options = {
                                bars: {
                                    show:true,
                                    barWidth: 0.5,
                                    fill:1,
                                    align: "center"
                                },
                                yaxis: {
                                    tickFormatter: function (v, axis) {
                                        return "R$ "+formatMoney(v);
                                    }
                                },
                                xaxis: {
                                    axisLabel: "Vendedores",
                                    axisLabelUseCanvas: true,
                                    axisLabelFontSizePixels: 12,
                                    axisLabelFontFamily: 'Verdana, Arial',
                                    axisLabelPadding: 10,
                                    ticks: ticks
                                },
                                grid: {
                                    show: true,
                                    aboveData: false,
                                    color: "#3f3f3f" ,
                                    labelMargin: 5,
                                    axisMargin: 0,
                                    borderWidth: 0,
                                    borderColor:null,
                                    minBorderMargin: 5 ,
                                    clickable: true,
                                    hoverable: true,
                                    autoHighlight: false,
                                    mouseActiveRadius: 20
                                },
                                series: {
                                    grow: {active:false}
                                },
                                legend: { position: "ne" },
                                colors: chartColours,
                                tooltip: true, //activate tooltip
                                tooltipOpts: {
                                    content: "%y",
                                    shifts: {
                                        x: -30,
                                        y: -50
                                    }
                                }
                        };

                        $.plot($(".charts_vendas_vendedor"), dataset, options);
                    });

                <?php } ?>

                <?php if(isset($this->charts_faturamento_categoria)){ ?>

                    $(function () {

                        var data = [];
                        var ticks = [];
                        <?php foreach ($this->charts_faturamento_categoria as $key => $value) { ?>
                            ticks.push([<?php echo $key; ?>,"<?php echo $this->charts_faturamento_categoria[$key]['categoria'] ?>"]);
                            data.push([<?php echo $key; ?>,<?php echo $this->charts_faturamento_categoria[$key]['total'] ?>]);
                        <?php } ?>

                        ticks.push([<?php echo COUNT($this->charts_faturamento_categoria); ?>,"Cupons"]);
                        data.push([<?php echo COUNT($this->charts_faturamento_categoria); ?>,<?php echo $this->charts_faturamento_cupom['cupom'] * (-1); ?>]);

                        ticks.push([<?php echo COUNT($this->charts_faturamento_categoria)+1; ?>,"Fretes"]);
                        data.push([<?php echo COUNT($this->charts_faturamento_categoria)+1; ?>,<?php echo $this->charts_faturamento_cupom['frete'] ?>]);


                        //var dataset = [{'data':data}];
                        dataset = [];
                        data.forEach(function(val, i){
                            dataset.push({"label":ticks[i][1]+" (R$ "+formatMoney(val[1])+")","data": [val]});
                        });

                        var options = {
                                bars: {
                                    show:true,
                                    barWidth: 0.5,
                                    fill:1,
                                    align: "center"
                                },
                                yaxis: {
                                    tickFormatter: function (v, axis) {
                                        return "R$ "+formatMoney(v);
                                    }
                                },
                                xaxis: {
                                    axisLabel: "Categorias",
                                    axisLabelUseCanvas: true,
                                    axisLabelFontSizePixels: 12,
                                    axisLabelFontFamily: 'Verdana, Arial',
                                    axisLabelPadding: 10,
                                    ticks: ticks
                                },
                                grid: {
                                    show: true,
                                    aboveData: false,
                                    color: "#3f3f3f" ,
                                    labelMargin: 5,
                                    axisMargin: 0,
                                    borderWidth: 0,
                                    borderColor:null,
                                    minBorderMargin: 5 ,
                                    clickable: true,
                                    hoverable: true,
                                    autoHighlight: false,
                                    mouseActiveRadius: 20
                                },
                                series: {
                                    grow: {active:false}
                                },
                                legend: { position: "ne" },
                                colors: chartColours,
                                tooltip: true, //activate tooltip
                                tooltipOpts: {
                                    content: "%y",
                                    shifts: {
                                        x: -30,
                                        y: -50
                                    }
                                }
                        };

                        $.plot($(".charts_faturamento_categoria"), dataset, options);
                    });

                <?php } ?>

                <?php if(isset($this->charts_quantidade_categoria)){ ?>

                    $(function () {

                        var data = [];
                        var ticks = [];
                        <?php foreach ($this->charts_quantidade_categoria as $key => $value) { ?>
                            ticks.push([<?php echo $key; ?>,"<?php echo $this->charts_quantidade_categoria[$key]['categoria'] ?>"]);
                            data.push([<?php echo $key; ?>,<?php echo $this->charts_quantidade_categoria[$key]['total'] ?>]);
                        <?php } ?>

                        //var dataset = [{'data':data}];
                        dataset = [];
                        data.forEach(function(val, i){
                            dataset.push({"label":val[1]+" "+ticks[i][1],"data": [val]});
                        });

                        var options = {
                                bars: {
                                    show:true,
                                    barWidth: 0.5,
                                    fill:1,
                                    align: "center"
                                },
                                xaxis: {
                                    axisLabel: "Categorias",
                                    axisLabelUseCanvas: true,
                                    axisLabelFontSizePixels: 12,
                                    axisLabelFontFamily: 'Verdana, Arial',
                                    axisLabelPadding: 10,
                                    ticks: ticks
                                },
                                grid: {
                                    show: true,
                                    aboveData: false,
                                    color: "#3f3f3f" ,
                                    labelMargin: 5,
                                    axisMargin: 0,
                                    borderWidth: 0,
                                    borderColor:null,
                                    minBorderMargin: 5 ,
                                    clickable: true,
                                    hoverable: true,
                                    autoHighlight: false,
                                    mouseActiveRadius: 20
                                },
                                series: {
                                    grow: {active:false}
                                },
                                legend: { position: "ne" },
                                colors: chartColours,
                                tooltip: true, //activate tooltip
                                tooltipOpts: {
                                    content: "%y",
                                    shifts: {
                                        x: -30,
                                        y: -50
                                    }
                                }
                        };

                        $.plot($(".charts_quantidade_categoria"), dataset, options);
                    });

                    $(".charts_quantidade_categoria").parents(".panel-default").find(".panel-minimize").click();

                <?php } ?>

                <?php if (isset($this->chart_ponto_contatos) && isset($this->chart_ponto_contatos_total)){ ?>
                $(function () {
                    //some data
                    <?php
                    $begin = new DateTime($_SESSION['periodo_de']);
                    $end = new DateTime($_SESSION['periodo_ate']);

                    $interval = DateInterval::createFromDateString('1 day');
                    $period = new DatePeriod($begin, $interval, $end);

                    $ponto_contatos = [];
                    $totalContatoRecorrente = 0;
                    $totalPontoContato = 0;
                    $totalNovoContato = 0;
                    foreach ($period as $dt) {
                        $data_match = $dt->format("Y-m-d");
                        $data = $dt->format("d/m");
                        $array = ["data"=>$data,"pontos_contato"=>0,"novo_contato"=>0,"contato_recorrente"=>0];

                        foreach($this->chart_ponto_contatos as $val){
                            if($val["data"]==$data_match){
                                $totalContatoRecorrente += $val["contato_recorrente"];
                                $array["contato_recorrente"] = $val["contato_recorrente"];
                            }
                        }
                        foreach ($this->chart_ponto_contatos_total as $val) {
                            if($val["data"]==$data_match){
                                $totalPontoContato +=  $val["total"];
                                $array["pontos_contato"] = $val["total"];
                            }
                        }
                        foreach ($this->chart_ponto_contatos as $val) {
                            if($val["data"]==$data_match){
                                $totalNovoContato += $val["novo_contato"];
                                $array["novo_contato"] = $val["novo_contato"];
                            }
                        }
                        array_push($ponto_contatos, $array);

                    }
                    ?>

                    var totalContatoRecorrente = <?=$totalContatoRecorrente?>;
                    var totalPontoContato = <?=$totalPontoContato?>;
                    var totalNovoContato = <?=$totalNovoContato?>;



                    var pontos_contato = [<?php foreach($ponto_contatos as $key => $dia){ echo "[$key,".$dia['pontos_contato']."]"; if($key < (count($ponto_contatos)-1)) echo ",";} ?>];

                    var novo_contato = [<?php foreach($ponto_contatos as $key => $dia){ echo "[$key,".$dia['novo_contato']."]"; if($key < (count($ponto_contatos)-1)) echo ",";} ?>];

                    var contato_recorrente = [<?php foreach($ponto_contatos as $key => $dia){ echo "[$key,".$dia['contato_recorrente']."]"; if($key < (count($ponto_contatos)-1)) echo ",";} ?>];

                    var tickPontoContato = [<?php foreach($ponto_contatos as $key => $dia){ echo "[$key,'".$dia['data']."']"; if($key < (count($ponto_contatos)-1)) echo ",";} ?>];


                    //define placeholder class
                    var placeholder = $(".ponto_cotato");
                    //graph options
                    var options = {
                        grid: {
                            show: true,
                            aboveData: true,
                            color: "#3f3f3f" ,
                            labelMargin: 5,
                            axisMargin: 0,
                            borderWidth: 0,
                            borderColor:null,
                            minBorderMargin: 5 ,
                            clickable: true,
                            hoverable: true,
                            autoHighlight: true,
                            mouseActiveRadius: 20
                        },
                        series: {
                            grow: {
                                active: false,
                                stepMode: "linear",
                                steps: 50,
                                stepDelay: true
                            },
                            lines: {
                                show: true,
                                fill: false,
                                lineWidth: 4,
                                steps: false
                            },
                            points: {
                                show:true,
                                radius: 5,
                                symbol: "circle",
                                fill: true,
                                borderColor: "#fff"
                            }
                        },
                        legend: {
                            position: "ne",
                            margin: [0,-25],
                            noColumns: 0,
                            labelBoxBorderColor: null,
                            labelFormatter: function(label, series) {
                                // just add some space to labes
                                return label+'&nbsp;&nbsp;';
                            }
                        },
                        yaxis: {
                            min: 0
                        },
                        xaxis: {ticks:tickPontoContato, tickDecimals: 0},
                        colors: chartColours,
                        shadowSize:0.5,
                        tooltip: true, //activate tooltip
                        tooltipOpts: {
                            content: "%y",
                            shifts: {
                                x: -30,
                                y: -50
                            }
                        }
                    };

                    //VENDAS

                    $.plot(".ponto_cotato", [
                        {
                            label: "Contato Recorrente (" + totalContatoRecorrente + ")",
                            data: contato_recorrente,
                            lines: {fillColor: "#f2f7f9"},
                            points: {fillColor: "#88bbc8"},
                            showTooltip: true
                        },
                        {
                            label: "Novo Contato (" + totalNovoContato + ")",
                            data: novo_contato,
                            lines: {fillColor: "#f2f7f9"},
                            points: {fillColor: "#f77758"}
                        },

                        {
                            label: "Pontos de Contato (" + totalPontoContato + ")",
                            data: pontos_contato ,
                            lines: {fillColor: "#f2f7f9"},
                            points: {fillColor: "#5a8022"}
                        }

                    ], options);




                });
                <?php } ?>

                <?php if (isset($this->charts_faturamento_dia)){ ?>
                    $(function () {
                        //some data
                        <?php
                            $begin = new DateTime($_SESSION['periodo_de']);
                            $end = new DateTime($_SESSION['periodo_ate']);

                            $interval = DateInterval::createFromDateString('1 day');
                            $period = new DatePeriod($begin, $interval, $end);

                            $faturamento_dia = [];
                            $faturamento_dia_novo = [];
                            $faturamento_dia_recorrente = [];

                            $TotalFaturamento_dia = 0;
                            $TotalFaturamento_dia_novo = 0;
                            $TotalFaturamento_dia_recorrente  = 0;
                            
                            $TotalValor_dia = 0;
                            $TotalValor_dia_novo = 0;
                            $TotalValor_dia_recorrente  = 0;

                            foreach ($period as $dt) {
                                $data_match = $dt->format("Y-m-d");
                                $data = $dt->format("d/m");
                                $array = ["data"=>$data,"faturamento"=>0,"vendas"=>0];
                                foreach($this->charts_faturamento_dia as $val){
                                    if($val["data_match"]==$data_match){
                                        $array["faturamento"] = $val["faturamento"];
                                        $array["vendas"] = $val["vendas"];
                                        $TotalFaturamento_dia += $val["vendas"];
                                        $TotalValor_dia += $val["faturamento"];
                                    }
                                }
                               
                                array_push($faturamento_dia, $array);

                                $array = ["data"=>$data,"faturamento"=>0,"vendas"=>0];
                                foreach($this->charts_faturamento_dia_novo as $val){
                                    if($val["data_match"]==$data_match){
                                        $array["faturamento"] = $val["faturamento"];
                                        $array["vendas"] = $val["vendas"];
                                        $TotalFaturamento_dia_novo += $val["vendas"];
                                        $TotalValor_dia_novo += $val["faturamento"];
                                    }
                                }
                                array_push($faturamento_dia_novo, $array);
                                
                                $array = ["data"=>$data,"faturamento"=>0,"vendas"=>0];
                                foreach($this->charts_faturamento_dia_recorrente as $val){
                                    if($val["data_match"]==$data_match){
                                        $array["faturamento"] = $val["faturamento"];
                                        $array["vendas"] = $val["vendas"];
                                        $TotalFaturamento_dia_recorrente += $val["vendas"];
                                        $TotalValor_dia_recorrente += $val["faturamento"];
                                    }
                                }
                                array_push($faturamento_dia_recorrente, $array);
                            }

                            // var_dump();
                        ?>

                        var total_pedidos = [<?php foreach($faturamento_dia as $key => $dia){ echo "[$key,".$dia['vendas']."]"; if($key < (count($faturamento_dia)-1)) echo ",";} ?>];
                        var total_pedidos_novo = [<?php foreach($faturamento_dia_novo as $key => $dia){ echo "[$key,".$dia['vendas']."]"; if($key < (count($faturamento_dia_novo)-1)) echo ",";} ?>];
                        var total_pedidos_recorrente = [<?php foreach($faturamento_dia_recorrente as $key => $dia){ echo "[$key,".$dia['vendas']."]"; if($key < (count($faturamento_dia_recorrente)-1)) echo ",";} ?>];

                        var total_range_pedidos = <?=$TotalFaturamento_dia?>;
                        var total_range_pedidos_novo = <?=$TotalFaturamento_dia_novo?>;
                        var total_range_pedidos_recorrente= <?=$TotalFaturamento_dia_recorrente?>;

                        var total_faturamento = [<?php foreach($faturamento_dia as $key => $dia){ echo "[$key,".$dia['faturamento']."]"; if($key < (count($faturamento_dia)-1)) echo ",";} ?>];
                        var total_faturamento_novo = [<?php foreach($faturamento_dia_novo as $key => $dia){ echo "[$key,".$dia['faturamento']."]"; if($key < (count($faturamento_dia_novo)-1)) echo ",";} ?>];
                        var total_faturamento_recorrente = [<?php foreach($faturamento_dia_recorrente as $key => $dia){ echo "[$key,".$dia['faturamento']."]"; if($key < (count($faturamento_dia_recorrente)-1)) echo ",";} ?>];

                        var total_range_faturamento = <?=$TotalValor_dia?>;
                        var total_range_faturamento_novo = <?=$TotalValor_dia_novo?>;
                        var total_range_faturamento_recorrente= <?=$TotalValor_dia_recorrente?>;

                        var ticks = [<?php foreach($faturamento_dia as $key => $dia){ echo "[$key,'".$dia['data']."']"; if($key < (count($faturamento_dia)-1)) echo ",";} ?>];


                        //define placeholder class
                        var placeholder = $(".faturamento_dia");
                        //graph options
                        var options = {
                                grid: {
                                    show: true,
                                    aboveData: true,
                                    color: "#3f3f3f" ,
                                    labelMargin: 5,
                                    axisMargin: 0,
                                    borderWidth: 0,
                                    borderColor:null,
                                    minBorderMargin: 5 ,
                                    clickable: true,
                                    hoverable: true,
                                    autoHighlight: true,
                                    mouseActiveRadius: 20
                                },
                                series: {
                                    grow: {
                                        active: false,
                                        stepMode: "linear",
                                        steps: 50,
                                        stepDelay: true
                                    },
                                    lines: {
                                        show: true,
                                        fill: false,
                                        lineWidth: 4,
                                        steps: false
                                        },
                                    points: {
                                        show:true,
                                        radius: 5,
                                        symbol: "circle",
                                        fill: true,
                                        borderColor: "#fff"
                                    }
                                },
                                legend: {
                                    position: "ne",
                                    margin: [0,-25],
                                    noColumns: 0,
                                    labelBoxBorderColor: null,
                                    labelFormatter: function(label, series) {
                                        // just add some space to labes
                                        return label+'&nbsp;&nbsp;';
                                     }
                                },
                                yaxis: {
                                    min: 0
                                },
                                xaxis: {ticks:ticks, tickDecimals: 0},
                                colors: chartColours,
                                shadowSize:1,
                                tooltip: true, //activate tooltip
                                tooltipOpts: {
                                    content: "%y",
                                    shifts: {
                                        x: -30,
                                        y: -50
                                    }
                                }
                        };

                        //VENDAS

                            $.plot(".vendas_dia", [
                                {
                                    label: "Pedido Recorrente ("+total_range_pedidos_recorrente+")",
                                    data: total_pedidos_recorrente,
                                    lines: {fillColor: "#f2f7f9"},
                                    points: {fillColor: "#88bbc8"},
                                },
                                {
                                    label: "Pedido Novo ("+total_range_pedidos_novo+")",
                                    data: total_pedidos_novo,
                                    lines: {fillColor: "#f2f7f9"},
                                    points: {fillColor: "#f77758"}
                                },
                                {
                                    label: "Pedidos ("+total_range_pedidos+")",
                                    data: total_pedidos,
                                    lines: {fillColor: "#f2f7f9"},
                                    points: {fillColor: "#5a8022"}
                                },

                            ], options);



                        //FATURAMENTO
                            options.yaxis.tickFormatter = function (v, axis) {
                                return "R$ "+formatMoney(v);
                            }
                            $.plot(".faturamento_dia", [
                                {
                                    label: "Faturamento Recorrente ("+ new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL'
                                        }).format(total_range_faturamento_recorrente)+")",
                                    data: total_faturamento_recorrente,
                                    lines: {fillColor: "#f2f7f9"},
                                    points: {fillColor: "#88bbc8"},
                                },
                                {
                                    label: "Faturamento Novo ("+ new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL'
                                        }).format(total_range_faturamento_novo)+")",
                                    data: total_faturamento_novo,
                                    lines: {fillColor: "#f2f7f9"},
                                    points: {fillColor: "#f77758"}
                                },
                                {
                                    label: "Faturamento ("+ new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL'
                                        }).format(total_range_faturamento)+")",
                                    data: total_faturamento,
                                    lines: {fillColor: "#f2f7f9"},
                                    points: {fillColor: "#5a8022"}
                                },

                            ], options);

                    });
                <?php } ?>

                <?php if(isset($this->charts_pendentes_vendedor)){ ?>

                    $(function () {

                        var data = [];
                        var ticks = [];
                        <?php foreach ($this->charts_pendentes_vendedor as $key => $value) { ?>
                            ticks.push([<?php echo $key; ?>,"<?php echo $this->charts_pendentes_vendedor[$key]['vendedor'] ?>"]);
                            data.push([<?php echo $key; ?>,<?php echo $this->charts_pendentes_vendedor[$key]['total'] ?>]);
                        <?php } ?>

                        //var dataset = [{'data':data}];
                        dataset = [];
                        data.forEach(function(val, i){
                            dataset.push({"label":ticks[i][1]+"(R$ "+formatMoney(val[1])+")","data": [val]});
                        });

                        var options = {
                                bars: {
                                    show:true,
                                    barWidth: 0.5,
                                    fill:1,
                                    align: "center"
                                },
                                yaxis: {
                                    tickFormatter: function (v, axis) {
                                        return "R$ "+formatMoney(v);
                                    }
                                },
                                xaxis: {
                                    axisLabel: "Vendedores",
                                    axisLabelUseCanvas: true,
                                    axisLabelFontSizePixels: 12,
                                    axisLabelFontFamily: 'Verdana, Arial',
                                    axisLabelPadding: 10,
                                    ticks: ticks
                                },
                                grid: {
                                    show: true,
                                    aboveData: false,
                                    color: "#3f3f3f" ,
                                    labelMargin: 5,
                                    axisMargin: 0,
                                    borderWidth: 0,
                                    borderColor:null,
                                    minBorderMargin: 5 ,
                                    clickable: true,
                                    hoverable: true,
                                    autoHighlight: false,
                                    mouseActiveRadius: 20
                                },
                                series: {
                                    grow: {active:false}
                                },
                                legend: { position: "ne" },
                                colors: chartColours,
                                tooltip: true, //activate tooltip
                                tooltipOpts: {
                                    content: "%y",
                                    shifts: {
                                        x: -30,
                                        y: -50
                                    }
                                }
                        };

                        $.plot($(".charts_vendedor_pendente"), dataset, options);
                    });

                <?php } ?>
                <?php if(isset($this->charts_entregue_vendedor)){ ?>

                    $(function () {

                        var data = [];
                        var ticks = [];
                        <?php foreach ($this->charts_entregue_vendedor as $key => $value) { ?>

                            ticks.push([<?php echo $key; ?>,"<?php echo $this->charts_entregue_vendedor[$key]['vendedor'] ?>"]);
                            data.push([<?php echo $key; ?>,<?php echo $this->charts_entregue_vendedor[$key]['quantidade'] ?>]);
                        <?php } ?>

                        //var dataset = [{'data':data}];

                        dataset = [];
                        data.forEach(function(val, i){
                            dataset.push({"label":"("+val[1]+") - "+ticks[i][1],"data": [val]});
                        });

                        var options = {
                                bars: {
                                    show:true,
                                    barWidth: 0.5,
                                    fill:1,
                                    align: "center"
                                },
                                yaxis: {
                                    minTickSize: 1,
                                    tickDecimals: 0
                                },
                                xaxis: {
                                    axisLabel: "Vendedores",
                                    axisLabelUseCanvas: true,
                                    axisLabelFontSizePixels: 12,
                                    axisLabelFontFamily: 'Verdana, Arial',
                                    axisLabelPadding: 10,
                                    ticks: ticks
                                },
                                grid: {
                                    show: true,
                                    aboveData: false,
                                    color: "#3f3f3f" ,
                                    labelMargin: 5,
                                    axisMargin: 0,
                                    borderWidth: 0,
                                    borderColor:null,
                                    minBorderMargin: 5 ,
                                    clickable: true,
                                    hoverable: true,
                                    autoHighlight: false,
                                    mouseActiveRadius: 20
                                },
                                series: {
                                    bars: {
                                        show:true,
                                        barWidth: 0.3,
                                        fill:1,
                                        lineWidth: 0,
                                        align:"center"
                                    }
                                },
                                legend: { position: "ne" },
                                colors: chartColours,
                                tooltip: true, //activate tooltip
                                tooltipOpts: {
                                    content: "%y",
                                    shifts: {
                                        x: -30,
                                        y: -50
                                    }
                                }
                        };

                        $.plot($(".charts_vendedor_entregue"), dataset, options);
                    });

                <?php } ?>

                <?php if(isset($this->chart_motivo_desistencia)){ ?>

                var data = [];
                <?php
                $total = 0;
                foreach ($this->chart_motivo_desistencia as $key => $value) {
                    $total = $total + $value['total'];
                }
                ?>
                <?php foreach ($this->chart_motivo_desistencia as $key => $value) { ?>
                <?php
                $color = '';
                if($value['descricao'] == 'Parou de responder') $color = ',color: "#88bbc8"';
                if($value['descricao'] == 'Concorrente com menor preço') $color = ',color: "#ed7a53"';
                if($value['descricao'] == 'Concorrente outros motivos') $color = ',color: "#9FC569"';
                if($value['descricao'] == 'Desistiu da Compra') $color = ',color: "#5a8022"';
                if($value['descricao'] == 'Intenção de comprar depois') $color = ',color: "#2c7282"';
                $valor = number_format($value['total'], 2, ',', '.');
                $porcentagem = number_format(($value['total'] / $total * 100),0);
                ?>
                data.push({label: "<?php echo '('.$value['total'].') '.$value['descricao']; ?>", data: <?php echo $porcentagem ?><?php echo $color; ?>});
                <?php } ?>

                $.plot($(".charts_motivo_perda"), data,
                    {
                        series: {
                            pie: {
                                show: true,
                                highlight: {
                                    opacity: 0.1
                                },
                                stroke: {
                                    color: '#fff',
                                    width: 3
                                },
                                startAngle: 2,
                                label: {
                                    radius:1
                                }
                            },
                            grow: { active: false}
                        },
                        legend: {
                            position: "ne",
                            labelBoxBorderColor: null
                        },
                        grid: {
                            hoverable: true,
                            clickable: true
                        },
                        tooltip: true, //activate tooltip
                        tooltipOpts: {
                            content: function(label, val1){
                                return val1+"%";
                            },
                            shifts: {
                                x: -30,
                                y: -50
                            }
                        }
                    });
                <?php } ?>


                <?php if(isset($this->chart_origem_contatos)){ ?>

                    var data = [];
                    <?php
                        $total = 0;
                        foreach ($this->chart_origem_contatos as $key => $value) {
                            $total = $total + $value['total'];
                        }
                    ?>

                    <?php if($total != 0) {?>

                        <?php foreach ($this->chart_origem_contatos as $key => $value) { ?>
                            <?php
                                // $valor = number_format($value['total'], 2, ',', '.');
                                $porcentagem = number_format(($value['total'] / $total * 100),0);
                            ?>
                            data.push({label: "<?php echo '('.$value['total'].') '.$value['origem_nome']; ?>", data: <?php echo $porcentagem ?>});
                        <?php } ?>

                        $.plot($(".charts_origem_contato"), data,
                        {
                            series: {
                                pie: {
                                    show: true,
                                    highlight: {
                                        opacity: 0.1
                                    },
                                    stroke: {
                                        color: '#fff',
                                        width: 3
                                    },
                                    startAngle: 2,
                                    label: {
                                        radius:1
                                    }
                                },
                                grow: { active: false}
                            },
                            legend: {
                                position: "ne",
                                labelBoxBorderColor: null
                            },
                            grid: {
                                hoverable: true,
                                clickable: true
                            },
                            tooltip: true, //activate tooltip
                            tooltipOpts: {
                                content: function(label, val1){
                                    return val1+"%";
                                },
                                shifts: {
                                    x: -30,
                                    y: -50
                                }
                            }
                        });
                    <?php } ?>
                <?php } ?>

                <?php if(isset($this->chart_origem_pedidos)){ ?>

                    var data = [];
                    <?php
                        $total = 0;
                        foreach ($this->chart_origem_pedidos as $key => $value) {
                            $total = $total + $value['total'];
                        }
                    ?>
                    <?php if($total != 0) {?>
                        <?php foreach ($this->chart_origem_pedidos as $key => $value) { ?>
                            <?php
                                // $valor = number_format($value['total'], 2, ',', '.');
                                $porcentagem = number_format(($value['total'] / $total * 100),0);
                            ?>
                            data.push({label: "<?php echo '('.$value['total'].') '.$value['origem_nome']; ?>", data: <?php echo $porcentagem ?>});
                        <?php } ?>

                        $.plot($(".charts_origem_pedido"), data,
                        {
                            series: {
                                pie: {
                                    show: true,
                                    highlight: {
                                        opacity: 0.1
                                    },
                                    stroke: {
                                        color: '#fff',
                                        width: 3
                                    },
                                    startAngle: 2,
                                    label: {
                                        radius:1
                                    }
                                },
                                grow: { active: false}
                            },
                            legend: {
                                position: "ne",
                                labelBoxBorderColor: null
                            },
                            grid: {
                                hoverable: true,
                                clickable: true
                            },
                            tooltip: true, //activate tooltip
                            tooltipOpts: {
                                content: function(label, val1){
                                    return val1+"%";
                                },
                                shifts: {
                                    x: -30,
                                    y: -50
                                }
                            }
                        });
                    <?php } ?>
                <?php } ?>






                <?php if(isset($this->charts_tipo_cliente)){ ?>

                    var data = [];
                    <?php
                        $total = 0;
                        foreach ($this->charts_tipo_cliente as $key => $value) {
                            $total = $total + $value['total'];
                        }
                    ?>
                    <?php foreach ($this->charts_tipo_cliente as $key => $value) { ?>
                        <?php
                            $color = '';
                            if($value['tipo_cliente'] == 'Home Game') $color = ',color: "#00aa20"';
                            if($value['tipo_cliente'] == 'Clube de Poker') $color = ',color: "#4a4af8"';
                            if($value['tipo_cliente'] == 'Cassino Temático') $color = ',color: "#ff0303"';
                            $valor = number_format($value['total'], 2, ',', '.');
                            $porcentagem = number_format(($value['total'] / $total * 100),0);
                        ?>
                        data.push({label: "<?php echo '('.$value['quantidade'].') '.$value['tipo_cliente']; ?> R$ <?php echo $valor; ?>", data: <?php echo $porcentagem ?><?php echo $color; ?>});
                    <?php } ?>

                    $.plot($(".charts_tipo_cliente"), data,
                    {
                        series: {
                            pie: {
                                show: true,
                                highlight: {
                                    opacity: 0.1
                                },
                                stroke: {
                                    color: '#fff',
                                    width: 3
                                },
                                startAngle: 2,
                                label: {
                                    radius:1
                                }
                            },
                            grow: { active: false}
                        },
                        legend: {
                            position: "ne",
                            labelBoxBorderColor: null
                        },
                        grid: {
                            hoverable: true,
                            clickable: true
                        },
                        tooltip: true, //activate tooltip
                        tooltipOpts: {
                            content: function(label, val1){
                                return val1+"%";
                            },
                            shifts: {
                                x: -30,
                                y: -50
                            }
                        }
                    });
                <?php } ?>

                <?php if(isset($this->charts_marketing_financeiro)){ ?>


                    $(function () {

                        var data = [];
                        var ticks = [];
                        <?php foreach ($this->charts_marketing_financeiro as $key => $value) { ?>
                            ticks.push([<?php echo $key; ?>,"<?php echo $this->charts_marketing_financeiro[$key]['categoria'] ?>"]);
                            data.push([<?php echo $key; ?>,<?php echo $this->charts_marketing_financeiro[$key]['total'] ?>]);
                        <?php } ?>

                        //var dataset = [{'data':data}];
                        dataset = [];
                        data.forEach(function(val, i){
                            dataset.push({"label":ticks[i][1]+" (R$ "+formatMoney(val[1])+")","data": [val]});
                        });

                        var options = {
                                bars: {
                                    show:true,
                                    barWidth: 0.5,
                                    fill:1,
                                    align: "center"
                                },
                                yaxis: {
                                    tickFormatter: function (v, axis) {
                                        return "R$ "+formatMoney(v);
                                    }
                                },
                                xaxis: {
                                    axisLabel: "Categorias",
                                    axisLabelUseCanvas: true,
                                    axisLabelFontSizePixels: 12,
                                    axisLabelFontFamily: 'Verdana, Arial',
                                    axisLabelPadding: 10,
                                    ticks: ticks
                                },
                                grid: {
                                    show: true,
                                    aboveData: false,
                                    color: "#3f3f3f" ,
                                    labelMargin: 5,
                                    axisMargin: 0,
                                    borderWidth: 0,
                                    borderColor:null,
                                    minBorderMargin: 5 ,
                                    clickable: true,
                                    hoverable: true,
                                    autoHighlight: false,
                                    mouseActiveRadius: 20
                                },
                                series: {
                                    grow: {active:false}
                                },
                                legend: { position: "ne" },
                                colors: chartColours,
                                tooltip: true, //activate tooltip
                                tooltipOpts: {
                                    content: "%y",
                                    shifts: {
                                        x: -30,
                                        y: -50
                                    }
                                }
                        };

                        $.plot($(".charts_faturamento_marketing"), dataset, options);
                    });

                <?php } ?>

            });
            function formatMoney(amount, decimalCount = 2, decimal = ",", thousands = ".") {
              try {
                decimalCount = Math.abs(decimalCount);
                decimalCount = isNaN(decimalCount) ? 2 : decimalCount;

                const negativeSign = amount < 0 ? "-" : "";

                let i = parseInt(amount = Math.abs(Number(amount) || 0).toFixed(decimalCount)).toString();
                let j = (i.length > 3) ? i.length % 3 : 0;

                return negativeSign + (j ? i.substr(0, j) + thousands : '') + i.substr(j).replace(/(\d{3})(?=\d)/g, "$1" + thousands) + (decimalCount ? decimal + Math.abs(amount - i).toFixed(decimalCount).slice(2) : "");
              } catch (e) {
                console.log(e)
              }
            };
        </script>
    </body>
</html>
